### ISSUE TITLE
Selective reload on policy change

### ISSUE THREAD

**Issue by msxfm** [RequestPolicyContinued/requestpolicy#112]
<a href="https://github.com/jsamuel"><img src="https://avatars.githubusercontent.com/u/1240282?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jsamuel](https://github.com/jsamuel)**
_Thursday Dec 22, 2011 at 18:53 GMT_
_Originally opened as https://github.com/RequestPolicy/requestpolicy/issues/112_

----

    imported trac ticket
    created: 2010-06-02 11:25:23
    reporter: eibwen

Often cross-site requests are either limited to elements on the page itself (eg an img) or are generated by such an element (eg flash).

It would be useful to conserve a little time (and bandwidth) to reload solely those elements that would have no adverse affects from a random reload, such as img and embeded objects?

Granted, randomly reloading other elements, eg scripts, may leave the page in an unknown and potentially undesired state, it seems possible to reload "safe" elements exclusive of the page itself.

The question then becomes:

1. How to conclusively identify whether any "unsafe" elements are affected.
2. Whether policy changes are frequent enough to warrant this.

At least for my use case (continual policy changes due to new round-robin subdomains), this could be addressed through resolution of other existing bugs:

#8 -- Support Wildcards, Regex, CDIR
#63 -- Support Wildcards
#91 -- Rules only honored if specificity matching current strictness
#103 -- Rules only honored if specificity matching current strictness

It should also be noted that #6 (blacklist support) would help to some extent; however, some sites do not use a consistent combination of cross site requests...

For the time being, I guess I could disable auto-reload and trigger manual reload of specific desired elements through javascript; however, this would seem to defeat the purpose of trying to save a little time/bandwidth.

A different use case could be users with non-unlimited bandwidth plans, eg firefox on mobile (speculative).

**Comment by myrdd** [comment]
I don't think I'm going to implement this feature request. Selective reloading won't be a problem on sites with mostly static content. However, when it comes to sites making heavy use of JS and ajax, it's very likely to break things, afaict.

> At least for my use case (continual policy changes due to new round-robin subdomains), this could be addressed through resolution of other existing bugs:

Many of the issues linked are resolved. So this issue might not be needed after all. Closing.
