### ISSUE TITLE
GUI does not show all blocked requests

### ISSUE THREAD

**Issue by msxfm** [RequestPolicyContinued/requestpolicy#156]
<a href="https://github.com/jsamuel"><img src="https://avatars.githubusercontent.com/u/1240282?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jsamuel](https://github.com/jsamuel)**
_Thursday Dec 22, 2011 at 18:56 GMT_
_Originally opened as https://github.com/RequestPolicy/requestpolicy/issues/156_

----

    imported trac ticket
    created: 2011-01-16 21:13:31
    reporter: eibwen

From what I recall of the source, the GUI lists of (blocked?) cross-site requests are guessed from the source of the page (eg src attributes); however, other requests are also possible.

For example, a greasemonkey userscript to parse a page and redirect to another domain will silently fail.  The cause turned out to be that this was considered a cross-site request and shouldLoad() blocked, but there was no GUI indication.

After manually adding the domain as an allowed cross-site request, all worked as expected.  Nevertheless, this behavior is particularly counter-intuitive and the list of blocked requests is incomplete...

**Comment by genodeftest** [comment]
How about XMLHttpRequests (XHRs)? Can they be filtered/blocked?

**Comment by myrdd** [comment]
@genodeftest to my understanding all XHRs are checked by RequestPolicy. Nevertheless we can't be sure whether there are still requests that are bypassing RP. (Currently there's issue #586) – Tools like wireshark should help finding such uncatched requests.

Btw, a list of ideas what could/should be tested you can find in issue https://github.com/RequestPolicyContinued/requestpolicy/issues/487

**Comment by myrdd** [comment]
From what the original poster described, this sounds like a compatibility issue with a greasemonkey script. Since this issue hasn't shown any activity in years, and lacks more detailed informaiton, I'm closing it.
