### ISSUE TITLE
whitelist item deletion from preferences menu doesn't work in some cases

### ISSUE THREAD

**Issue by msxfm** [RequestPolicyContinued/requestpolicy#172]
<a href="https://github.com/jsamuel"><img src="https://avatars.githubusercontent.com/u/1240282?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jsamuel](https://github.com/jsamuel)**
_Thursday Dec 22, 2011 at 18:57 GMT_
_Originally opened as https://github.com/RequestPolicy/requestpolicy/issues/172_

----

    imported trac ticket
    created: 2011-01-31 14:21:17
    reporter: justin

Archaeopteryx reports a problem when using ctrl+a in the whitelist lists in the preferences menu:
   click one element in the list, press ctrl + a, press ctrl click the one element again, then the delete button

The reported problem is that even though all of the correct items appear to be selected (all except the one that was initially selected and then deselected after the "select all"), the selected items don't get deleted when the delete button is pressed.

This was on WinXP with RP 0.5.17 and Fx 4.0b11pre. I haven't had a chance to test on WinXP. I am not seeing this on Linux.

**Comment by myrdd** [comment]
This bug is only affecting 0.5. Closed.
