### ISSUE TITLE
AMO validation warning: on* attribute being set using setAttribute

### ISSUE THREAD

**Issue by msxfm** [RequestPolicyContinued/requestpolicy#228]
<a href="https://github.com/jsamuel"><img src="https://avatars.githubusercontent.com/u/1240282?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jsamuel](https://github.com/jsamuel)**
_Thursday Dec 22, 2011 at 19:01 GMT_
_Originally opened as https://github.com/RequestPolicy/requestpolicy/issues/228_

----

    imported trac ticket
    created: 2011-04-29 10:28:58
    reporter: justin

New warning from the AMO validator:

```
on* attribute being set using setAttribute

Error: To prevent vulnerabilities, event handlers (like 'onclick'
and 'onhover') should always be defined using addEventListener.
chrome/requestpolicy.jar/content/menu.js
  334 menuItem.setAttribute("statustext", statustext);
  335 menuItem.setAttribute("oncommand", oncommand);
  336// menuItem.setAttribute("tooltiptext", node getAttribute("tooltiptext"));
```

**Comment by myrdd** [comment]
fixed
