### ISSUE TITLE
Removal of Unused Functions

### ISSUE THREAD

**Issue by msxfm** [RequestPolicyContinued/requestpolicy#233]
<a href="https://github.com/jsamuel"><img src="https://avatars.githubusercontent.com/u/1240282?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jsamuel](https://github.com/jsamuel)**
_Thursday Dec 22, 2011 at 19:01 GMT_
_Originally opened as https://github.com/RequestPolicy/requestpolicy/issues/233_

----

    imported trac ticket
    created: 2011-06-17 23:11:40
    reporter: eibwen

There appear to be at least 12 (!) functions that are not currently used.  Recommend removal of these functions:

```
''./src/components/requestpolicyService.js''

  _combinedOriginToDestinationIdentifierHasOrigin
  _combinedOriginToDestinationIdentifierHasDestination
  _dumpRejectedRequests
  _dumpAllowedRequests

''./src/content/menu.js''

  _removeExtraSubmenuSeparators
  _disableMenuIfEmpty

''./src/content/overlay.js''

  _contextMenuOnPopupHidden
  _performRedirect

''./src/modules/DomainUtil.jsm:''

  identifierIsInUri
  stripWww
  sameHostIgnoreWww
  destinationIsSubdomainOfOrigin
```

Note that there are additional functions that are not referenced in the extension; however, they are implied to be required by the IDL of an XPCOM component/observer or similar.

**Comment by myrdd** [comment]
cb7367d
