### ISSUE TITLE
How to deal with ajax.googleapis.com?

### ISSUE THREAD

**Issue by msxfm** [RequestPolicyContinued/requestpolicy#267]
<a href="https://github.com/jsamuel"><img src="https://avatars.githubusercontent.com/u/1240282?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jsamuel](https://github.com/jsamuel)**
_Thursday Dec 22, 2011 at 19:03 GMT_
_Originally opened as https://github.com/RequestPolicy/requestpolicy/issues/267_

---

```
imported trac ticket
created: 2011-10-04 22:15:41
reporter: shabbyrobe
```

Many sites depend on jQuery served by google. Can a separate tab be added to requestpolicy to allow resources like this to be loaded from an alternative place? For e.g. I could host my own version of jQuery and point http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js there instead.

I don't know that this is necessarily the solution (hence the vague ticket name, sorry about that), but RequestPolicy breaks websites left right and centre without ajax.googleapis.com whitelisted everywhere and then pow, they're tracking me again whether I like it or not. 

I only installed RequestPolicy an hour ago and I'm already seeing three of my most visited websites (stackoverflow, slashdot and reddit) breaking.

**Comment by nodiscc** [comment]
> An addon that does a local mirror of common js libs (usually fetched from CDNs) would be great, bit outside of scope for RequestPolicy, but definitely wanted.

A possible candidate https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/ (https://github.com/Synzvato/decentraleyes), untested.
