### ISSUE TITLE
Brief: images in feeds are blocked

### ISSUE THREAD

**Issue by msxfm** [RequestPolicyContinued/requestpolicy#29]
<a href="https://github.com/jsamuel"><img src="https://avatars.githubusercontent.com/u/1240282?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jsamuel](https://github.com/jsamuel)**
_Thursday Dec 22, 2011 at 18:46 GMT_
_Originally opened as https://github.com/RequestPolicy/requestpolicy/issues/29_

----

    imported trac ticket
    created: 2009-08-08 19:21:01
    reporter: justin

Aus has [reported](http://forums.mozillazine.org/viewtopic.php?p=7164555#p7164555) that when using RequestPolicy, all images displayed by the Brief rss reader extension are blocked.

**Comment by genodeftest** [comment]
This is not applicable any more. With 1.0 beta8.2 images in brief are not blocked.

**Comment by nodiscc** [comment]
@genodeftest Are you using RequestPolicy in _Default: block_ policy?

**Comment by genodeftest** [comment]
Yes, I am.

**Comment by nodiscc** [comment]
Thanks! This can be closed.
