### ISSUE TITLE
Whitelisting spotify links doesn't work sensibly

### ISSUE THREAD

**Issue by msxfm** [RequestPolicyContinued/requestpolicy#296]
<a href="https://github.com/alexlehm"><img src="https://avatars.githubusercontent.com/u/156144?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alexlehm](https://github.com/alexlehm)**
_Tuesday Mar 20, 2012 at 18:22 GMT_
_Originally opened as https://github.com/RequestPolicy/requestpolicy/issues/296_

---

When accessing Spotify via web e.g. from twitter postings, the link supplied to the client contains a custom url defined by Spotify, e.g. spotify:artist:7K4k5g1ie2qHIH42UMNO7n or spotify:track:4IoqGTH2D6zMrGzg9gW0DL
requestpolicy distinguishes the links completely so each link has to be whitelisted individually, it would be better if it were possible to whitelist e.g. spotify:*

the same issue happens with itunes links (itms:) and probably all kinds of custom links (magnet, irc etc)

**Comment by myrdd** [comment]
@alexlehm: Release [`1.0.beta8.2`](https://github.com/RequestPolicyContinued/requestpolicy/releases/tag/v1.0.beta8.2) adds the `spotify` scheme to its temporary scheme-whitelist.
