### ISSUE TITLE
popup windows display the allow/deny bar in the wrong window

### ISSUE THREAD

**Issue by msxfm** [RequestPolicyContinued/requestpolicy#297]
<a href="https://github.com/alexlehm"><img src="https://avatars.githubusercontent.com/u/156144?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alexlehm](https://github.com/alexlehm)**
_Tuesday Mar 20, 2012 at 18:24 GMT_
_Originally opened as https://github.com/RequestPolicy/requestpolicy/issues/297_

----

when clicking on a link that opens a new empty window and then redirects this windows url to the target url, the yellow message bar with allow/deny is displayed in the opening window, not in the new window. this means that when you click allow, the wrong window displays the opened content.

**Comment by myrdd** [comment]
I think this issue is solved. If not, please reopen.
