### ISSUE TITLE
Clicking on link doesn't open link

### ISSUE THREAD

**Issue by msxfm** [RequestPolicyContinued/requestpolicy#301]
<a href="https://github.com/matham"><img src="https://avatars.githubusercontent.com/u/1644286?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [matham](https://github.com/matham)**
_Sunday Apr 15, 2012 at 01:08 GMT_
_Originally opened as https://github.com/RequestPolicy/requestpolicy/issues/301_

---

I have noticed sometimes that when I click on a link on a webpage the browser completely ignores it, as if I didn't click. I mostly notice it on google search. However, when I right click->open new tab on that same link the link opens fine in the new tab.

The reason why I think RequestPolicy is responsible is that on this wbesite (make sure  first that request policy is stopping any links to google-analytics from that webpage from loading): http://articles.cnn.com/2011-10-19/politics/politics_deportation-record_1_ice-director-john-morton-undocumented-immigrants-criminal-alien-program?_s=PM:POLITICS if you scroll down to the bottom you'll see a link to continue read page two and three of that article. When I click on that (that is the number 2 or 3) nothing happens. When I then go to request policy and allow requests from cnn to google-analytics clicking on the page numbers start working again.

I cannot see what google-analytics has to do with clicking on that link so I think it must be a bug.

Running Firefox 11.0 on win7 with RequestPolicy 0.5.25

Thanks,
m

**Comment by the-rody** [comment]
In Firefox I was also having this issue also, but only when I was clicking on a search result in duckduckgo. The solution I found (and is still working so far) was opening about:config and changing browser.search.openintab from false to true.

Wasn't a RequestPolicy issue after all.

Running Firefox 47.0 and RequestPolicy 1.0.0b3, in addition to NoScript and ABP.

**Comment by myrdd** [comment]
> In Firefox I was also having this issue also, but only when I was clicking on a search result in duckduckgo

Yeah, strangely, in ddg's javascript-enabled version, the "origin" url in the request log differs from the one in the location bar, e.g.:

* location bar: `https://duckduckgo.com/?q=universe&t=hd&ia=meanings`
* request origin when clicking a link: `https://duckduckgo.com/?q=universe&t=hd`

Opening the link in a new tab or window works, as described above.
