### ISSUE TITLE
v1.0 has no menu entry in the context menu (right-click menu)

### ISSUE THREAD

**Issue by msxfm** [RequestPolicyContinued/requestpolicy#353]
#### edit by @myrdd

RequestPolicy 0.5.x had an entry in the right-click context menu, see this screenshot:

![content-area context menu in RP 0.5.x](https://cloud.githubusercontent.com/assets/4286829/5554691/829c6952-8c6c-11e4-85e4-495d3387cdaf.jpg)

In v1.0 beta this additional menu disappeared. **This issue is about getting that menu back.**

---

---

#### original post

<a href="https://github.com/Dinoso"><img src="https://avatars.githubusercontent.com/u/2914040?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Dinoso](https://github.com/Dinoso)**
_Wednesday Nov 28, 2012 at 17:59 GMT_
_Originally opened as https://github.com/RequestPolicy/requestpolicy/issues/353_

----

Hi,

please add an option to have the menu of version 0.5 again. I was familiar with right-clicking whereever I was, move cursor to requestpolicy, do my action (sorting is already filed here, so I won't go into this) and after clicking whatever I wanted to, the menu closed and depending on my preferences the site was reloaded or not. 

I really like the new features, but I want the old (quicker) behaviour again, at least as an option.

**Comment by noisybe** [comment]
Hi, is the right click menu already functional? I have installed the latest beta but there is only a button in the toolbar. I'll downgrade to FF 37.0.2 until this works. Thank you for your efforts.

**Comment by noisybe** [comment]
I was even so desperate to edit the em:maxVersion in the install.rdf of the 0.5.28 release because I want the context menu but it gets blocked anyway.

**Comment by riesza** [comment]
If you don't want to litter your toolbar with the RP icon there's a shortcut to bring up the menu: ctrl+alt+R

**Comment by myrdd** [comment]
@noisybe if you want to use the old 0.5 version, you can try [RPC 0.5](https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-continued/); I've just uploaded it to AMO, it should work – but don't forget to uninstall legacy RP.

The right-click menu is not there yet. It's currently planned for 1.0.beta12

**Comment by noisybe** [comment]
@myrdd wow.. I hadn't found that. Thank you! <3

Looking forward to 1.0.beta12 :)

**Comment by myrdd** [comment]
@noisybe you're welcome! Btw, you did not find it because it's still in the AMO Review Queue.

**Comment by myrdd** [comment]
The next version will have a context menu entry again. When you click it, the "normal" 1.0-style menu will open, just like when you click the toolbar button.

![RP context menu entry](https://cloud.githubusercontent.com/assets/4286829/11961962/7b768800-a8dc-11e5-9f52-480f07b929ab.png)
