### ISSUE TITLE
redirects from links opened in new tabs can show in menu of original page

### ISSUE THREAD

**Issue by msxfm** [RequestPolicyContinued/requestpolicy#36]
<a href="https://github.com/jsamuel"><img src="https://avatars.githubusercontent.com/u/1240282?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jsamuel](https://github.com/jsamuel)**
_Thursday Dec 22, 2011 at 18:47 GMT_
_Originally opened as https://github.com/RequestPolicy/requestpolicy/issues/36_

----

    imported trac ticket
    created: 2009-09-15 08:57:55
    reporter: justin

Aerik Knapp-Loomis writes:

  Currently there's a bug where when you open a new tab and contains a redirect, the tab that you clicked over from will have somehow interacted with RP as if you allowed a request from the second tab.

  For example, every time I'm on google reader and I ctrl+click  on a link to a new tab that's located at feedproxy.google.com, which is always a redirect, the google reader tab will show that I've allowed a request from feedproxy.google.com.

This issue has been known and reported a few times before and it's time to make a ticket for it. However, I'm not sure how to fix it. There are fundamental issues with lacking information that Firefox makes available to us when we block or allow requests. It may be the case that solving this involves using a lot more DOM inspection for generating the menu, which is something we'd like to avoid for simplicity and speed reasons.

I need to spend some time on this, though, to see if there's an easier fix I'm not thinking of that won't involve complicating !RequestPolicy a lot just to deal with this issue.

**Comment by myrdd** [comment]
I think this issue is solved. If not, please reopen.
