### ISSUE TITLE
1.0 menu wastes a lot of screen space

### ISSUE THREAD

**Issue by msxfm** [RequestPolicyContinued/requestpolicy#378]
<a href="https://github.com/tyaremco"><img src="https://avatars.githubusercontent.com/u/709811?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tyaremco](https://github.com/tyaremco)**
_Wednesday Jun 12, 2013 at 06:19 GMT_
_Originally opened as https://github.com/RequestPolicy/requestpolicy/issues/378_

----

Maybe I'm missing something, but why on earth is there a giant white box taking up 2/3 of the UI?  The options to block/enable a destination take up less than 20% of that space on average in my experience.  

Why not just have these options display directly below the selected destination, in the same column?

**Comment by nodiscc** [comment]
Closing as no info has been provided and the menu seems to do the job for most users.
