### ISSUE TITLE
about:healthreport won't work with 1.0.0b3

### ISSUE THREAD

**Issue by msxfm** [RequestPolicyContinued/requestpolicy#399]
<a href="https://github.com/madperson"><img src="https://avatars.githubusercontent.com/u/1524147?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [madperson](https://github.com/madperson)**
_Saturday Oct 26, 2013 at 20:05 GMT_
_Originally opened as https://github.com/RequestPolicy/requestpolicy/issues/399_

----

when  "Block requests by default" is set as default policy, firefox' own internal page about:healthreport won't work & it is apparently not possible to set a rule to work around that.

**Comment by genodeftest** [comment]
As far as I can test this bug is fixed with most recent 1.0.beta8.2

**Comment by nodiscc** [comment]
Thanks @genodeftest it's indeed working.

**Comment by myrdd** [comment]
Yes, that's because of the workaround in #447. However, it's ok to close this issue. Thanks @genodeftest
