### ISSUE TITLE
the project's website

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/requestpolicy#445]
**Summary:**
- the old website is https://www.requestpolicy.com/ (though theSSL/TLS certificate expired)
- currently we offer a *beta* `xpi` extention file on https://sslsites.de/requestpolicy.256k.de/ (it hosts also *update-beta.rdf*)
- it has been suggested to move both files to github, but that's maybe not possible – firefox needs the header to be `Content-type: text/xml` for the *update-beta.rdf* file, which is (I think so) not possible on github.
So what to do?
Additionally, as soon as we have a stable version, it might be nice to have an own domain for PR (which might contain a forum). – no idea if we'll take over *requestpolicy.com* or if we'll have our own.

**long version (so far)**
This copy-pasted discussion is from https://github.com/RequestPolicyContinuedTmp/requestpolicy/commit/d7f4da7fbfbe2abbc82f372e61b9ee848fc60870#commitcomment-7408303
(I'm posting it here because I'll remove the *RequestPolicyContinuedTmp* organization soon.)

> **msxfm** writes:

>>  `<em:updateURL>https://sslsites.de/requestpolicy.256k.de/update-1.x-beta.rdf.php</em:updateURL>` (*src/install.rdf*)

> Hi, can we host this on github please? Maybe using github releases https://github.com/blog/1547-release-your-software. Or store it directly in the dev-1.0 tree?
> 
> I'd prefer the manifest to stay alongside the source (at least same domain). Currently update-1.x-beta.rdf.php is not reviewable from the version control system and it's rather security critical.

> **myrdd:**

> yes, it would be ok for me to host the rdf on github, but will we upload the xpi files to github also? I would say we shouldn't use git to upload a completely new binary file every few days.
> github releases, from what I've seen there, are bound to tags. Same as before, I don't want to create a mess by making a tag every few days.
> In fact, I don't get your point, why do you want to have the rdf in the version control system?

> **nodiscc:**

> why do you want to have the rdf in the version control system?
> 
> - Because it's part of the code (though it's not in the final XPI)
> - Does not depend on a third-party server that can go down, get compromised.. the repo can get compromised but we would likely notice.
> - Changes in the repo are reviewable, we can see when/if/why it breaks. More portable, everyone can fork and add his own XPI url.
> 
> - will we upload the xpi files to github also
> 
> What I would do:
> 
> - wait before we complete the merge discussed in RequestPolicy#407 (comment)
> - move update-1.x-beta.rdf from your server to the root of the repo.
> - Change <em:updateURL> in src/install.rdf to https://github.com/RequestPolicyContinued/requestpolicy/blob/master/update-1.x-beta.rdf
> - build the XPI.
> - Create a release (for example 1.0.0b4-1), add the XPI as attachment. If you attach them to releases, they don't get in the git repo - they are just attached - you can attach an arbitrary binary file to each release. (example)
> - Point <em:updateLink> in update-1.x-beta.rdf to your released XPI on Github.
> 
> You just have to repeat the 2 last steps for each release. We would have everything in the same place, source, update rdf, and XPI.
> 
> - Same as before, I don't want to create a mess by making a tag every few days.
> 
> You are not forced to tag and release every few days, just build the XPI on your side and release it when it's ready/working. Tags do not mess up anything, and the repo already has a few.
> 
> Thanks for your time on this.

> **myrdd:**

> Thanks for your detailed clarification, sounds reasonable and I agree.
> 
> About the tags: until now, I've pushed a new version with every interesting change or bugfix (maximum every day). Continuing like that, we could get a lot of tags. If this matters, we could decide to release beta versions less often. Can you suggest a common/best practice how often to release alpha/beta/stable versions?

> **nodiscc:**

> Yes, we have to think about a clean release process. This likely means a bit of branch cleanup/reordering. I'll think about it and add an issue at https://github.com/RequestPolicyContinued/requestpolicy

> **myrdd:**

> ok :) if you don't mind I'll call the next version 1.0.0b7, which will also be the tag's name (currently it's 1.0.0b6). This way, beta versions already installed will get updated also. ok?

> **myrdd:**

> I think there's a problem about hosting update.rdf on github. When you access a file, like this one (click here), then you'll get a plaintext file. – but: the webserver needs to send the HTTP header Content-type: text/xml, otherwise Firefox doesn't accept the update file. I had this issue when I tested that on my own server. So what to do? Host the xpi on github and host update.rdf externally?

**Comment by nodiscc** [comment]
Followup to https://github.com/RequestPolicyContinued/requestpolicy/issues/593#issuecomment-80500265

I'd prefer keeping `about:config` documentation in the wiki for this reason: I've had time to think about the website: most of the content there (except general addon presentation/features/principles) should go in a separate user documentation. `about:config` prefs should go there, as well as the tutorial, etc.

 * The wiki is really easy to edit (thx markdown), the website a little less.
 * At this point there are already several pages in my branch, and this is _not easily discoverable_. The website should really be only an introduction to RPContinued. There are items on the main page that are actually user documentation. Hence --> wiki.
 * Bonus, when this is done, we could sync the wiki to the main code (`git submodule foreach git pull; git add wiki; git c -m "update documentation"), and let the "Help" links in the menu and preferences point to the local documentation, which should be installed with the addon. If you agree?

The wiki's markdown can be rendered to HTML in-browser thanks to javascript ([Mdwiki](https://github.com/Dynalon/mdwiki), [example](https://nodiscc.github.io/notes/#!jabberhowto.md)) or during build with pandoc for example.

I may open other issues for this

**Comment by myrdd** [comment]
> The website should really be only an introduction to RPContinued.

I can't think of any disadvantages of your suggestion @nodiscc, so I think that would be OK.

> (…) the local documentation, which should be installed with the addon. If you agree?

Yes, I think it would be good to have the documentation offline on the local disk. But note that the wiki currently contains development-specific documentation. I think that shouldn't be delivered via the XPI.

> I may open other issues for this

That would be nice!

**Comment by myrdd** [comment]
@nodiscc is the following still correct?

Your plan for this issue is to complete the website and create a tutorial?
 - tutorial: https://github.com/nodiscc/rp-website/commits/gh-pages
 - current status: https://nodiscc.github.io/rp-website/
 - remaining ToDo: https://github.com/nodiscc/rp-website/blob/gh-pages/draft-tutorial.md

**Comment by nodiscc** [comment]
I've rewritten the site in Markdown to speed things up and make maintenance easier. Once it's complete, it will include contents of the website, the wiki, and some parts of the README that really belong in the documentation. Current status: https://github.com/nodiscc/rp-website/wiki. Then we can proceed to

1. Move this documentation to the project's wiki.
2. Generate static HTML from the markdown and upload it to the website repo (with some extra styling if needed, can be done easily with `pandoc`). The website would actually be a mirror of the wiki.

Remaining todo: move https://nodiscc.github.io/rp-website/tutorial.html, https://github.com/nodiscc/rp-website/blob/gh-pages/draft-tutorial.md, fix formatting, include parts from https://github.com/RequestPolicyContinued/requestpolicy/blob/dev-1.0/README.md, build and upload the new website's static HTML.

@myrdd are you ok with this? I think having everything in one place will be easier to maintain, and easier for users/contributors to look for info.

**Comment by myrdd** [comment]
I think it's a good plan to have everything in one place. Let me know when I should review something.

**Comment by nodiscc** [comment]
The project's website, wiki and README have been merged in https://github.com/nodiscc/rp-website/wiki. I'm working on a build script using [pandoc](http://pandoc.org/) and a few custom CSS adjustments.

**Comment by nodiscc** [comment]
There is still duplicate information at https://github.com/nodiscc/rp-website/wiki/FAQ#how-to-find-relevant-information-about-a-bug and https://github.com/nodiscc/rp-website/wiki/Contributing#testing-reporting-bugs--requesting-new-features

**Comment by nodiscc** [comment]
I'm thinking about re-adding the current website's first section (screenshots and usage overview) at https://github.com/nodiscc/rp-website/wiki#what-does-requestpolicy-continued-do

**Comment by myrdd** [comment]
> Any feedback on the wiki contents/layout is highly appreciated.

So far I've read the pages *main, privacy, security* and half of *quickstart* carefully. This is what I took note of:

#### general note

I think we should speak of „RequestPolicy“ in most cases and shouldn't mention „Continued“. I was going to add a FAQ entry at least to the AMO description, which would be as follows:

> **Is „RequestPolicy“ now named „RequestPolicy Continued“ the new name of the addon?**
> 
> No, the addon may still be called „RequestPolicy“. The word „Continued“ has
been added in some places in order to emphasize that there are *two* addons
called „RequestPolicy“ on the web. As soon as the *continued* version has fully
replaced the previous one, the word „Continued“ will be removed completely from
the addon.

No, the addon may still be called „RequestPolicy“, and it's likely that the word „Continued“ will be removed completely from the addon itself. However, the name of the *project* for now is „RequestPolicy Continued“, or  „RPC“ for short..

#### pages

* main
  * the *subscription* link is dead
  * I think

**Comment by myrdd** [comment]
I've accidentally pushed the submit button, but now my above comment is complete.

**Comment by DJ-Leith** [comment]
> Any feedback on the wiki contents/layout is highly appreciated.

I agree with **myrdd** (just above). 

In

https://github.com/nodiscc/rp-website/wiki/quickstart.md

(one of the 13 pages linked at the 'Top Right' of
https://github.com/nodiscc/rp-website/wiki )

In the section:

> **Allow requests to another.net:** This will allow **all** requests to <code>another.net</code>, from any page, on any domain. This is not recommended unless you are tired to deal with many sites that require allowing requests to <code>another.net</code>.

My suggested wording would be to change the second sentence:

**Allow requests to another.net:** This will allow **all** requests to <code>another.net</code>, from any page, on any domain. This is not recommended unless you keep having to allow requests to <code>another.net</code> from **many**&nbsp;sites.


I understand "you are tired to deal with" but I can't think how to put this is better English.


> *Note: Each action has a Temporarily block/allow alternative. This will add a temporary rule that will be removed when you click the Revoke temporary permissions menu item*

My suggested wording would be to expand this to become:

*Note: Each action has a Temporarily block/allow alternative. This will add a temporary rule that will be removed when you click the Revoke temporary permissions menu item. When you close Firefox all temporary rules are forgotten.*

------ 
Almost off topic - a question about RP rules and e10s: I'm not using e10s (because NoScript can't).

*Will the RP rules be the same for ALL Tabs?* I think they will.

With RP 0.5.28 and RPC 1.0.beta9.3 (and not using e10s) all Temporary Rules are applied (work)  until they are revoked on all Tabs / Windows.

I very rarely add Rules - I nearly always use Temporary Rules.
In my usage these Temporary Rules are lost:
* usually when I close Firefox,
* sometimes when I click the "Revoke all temporary permissions" in the RP Menu,
* very rarely by using the UI to stop an individual Temporary Rule.

------ 

Back to 'quickstart.md page', at the end we have: 
> **That’s it! Now you should be able to do most of the things RequestPolicy is built for. For more advanced topics, you can read the documentation below.**

Please provide a link to more advanced topics (there was no "below" - the text is at the bottom of the page).

**Comment by myrdd** [comment]
+1 for @DJ-Leith's suggestions.
However, note @DJ-Leith that the „Revoke temporary permissions“ button revokes **all** temporary rules as well. That is, clicking „Revoke temporary permissions“ or closing firefox do the same to temporary rules.

Hm, maybe the button should be renamed?
Now it's *„Revoke temporary permissions“*. My suggestion: *„Revoke all temporary rules“*.
So „all“ to clarify, and „rules“ because it's more appropriate.

----------------------

about off-topic:

> Will the RP rules be the same for ALL Tabs?

@DJ-Leith if this was your only off-topic question, the answer is yes.

**Comment by nodiscc** [comment]
Thanks for your very useful review, everything you reported should be fixed. I'll work on it.

**Comment by DJ-Leith** [comment]
> @DJ-Leith if this was your only off-topic question, the answer is yes.

Thanks for confirming, @myrdd.

**myrdd** said:
> However, note **@DJ-Leith** that the „Revoke temporary permissions“ button revokes **all** temporary rules as well. That is, clicking „Revoke temporary permissions“ or closing firefox do the same to temporary rules.

Just to be clear, the word "all" is already in the 'link wording': I had previously said:

> * sometimes when I click the "Revoke all temporary permissions" in the RP Menu,

Next is a screenshot of what I was describing:

![screenshot-revoke-all-temporary-permissions-crop-2015-05-30](https://cloud.githubusercontent.com/assets/12447809/7897773/13f025da-06e1-11e5-890d-89291ebfd48b.jpg)

On this Profile, used for the screenshot, the 'whitelist' does not have any "github.com".
I had 'Temporary allowed' all of the '6 green entries seen - to the githubusercontent subdomains *etc*'.
All of these will be revoked if I click the "Revoke all temporary permissions" link.

> Hm, maybe the button should be renamed?
> Now it's „Revoke temporary permissions“. My suggestion: „Revoke all temporary rules“.
> So „all“ to clarify, and „rules“ because it's more appropriate.

In RPC 1.0.beta9.3, the 'option I was talking about', already has "all".
Perhaps there is another place where it does not have "all"?
If so, I would agree - add the word "all".

As for the 'rules vs permissions' question: I agree, be consistent and call them "Rules".
"Rules" (meaning in the "user.json" or other 'permanent storage file' used by subscriptions),
"Temporary Rules" that 'last until revoked by closing Firefox' - the session,
or by explicit revocation
*e.g.* by clicking the 'soon will be' "Revoke all temporary rules" link
(which is, at the moment, called "Revoke all temporary permissions").

They are called "Active Rules" in <code>about:requestpolicy?yourpolicy</code>
The Temporary ones are in the "Rule Set" called "Temporary".

So, "Rules" is used widely.

@myrdd, if you do change the wording to "Revoke all temporary rules" then
I recommend the @nodiscc should change the website page:

it is (see above):
> *Note: Each action has a Temporarily block/allow alternative. This will add a temporary rule that will be removed when you click the Revoke temporary permissions menu item*

to become:

*Note: Each action has a Temporarily block/allow alternative. This will add a temporary rule that will be removed when you click the "X" to Revoke the temporary rule (in <code>about:requestpolicy?yourpolicy</code>) or you click the "Revoke all temporary rules" link (see screenshot). When you close Firefox all temporary rules are forgotten.*

It would be good to have screenshots to illustrate.

**Comment by myrdd** [comment]
> In RPC 1.0.beta9.3, the 'option I was talking about', already has "all".
> Perhaps there is another place where it does not have "all"?

Oops, that's right. So "all" doesn't need to be added.

---

> Note: Each action has a Temporarily block/allow alternative. This will add a temporary rule that will be removed when you click the "X" to Revoke the temporary rule (in about:requestpolicy?yourpolicy) or you click the "Revoke all temporary rules" link (see screenshot). When you close Firefox all temporary rules are forgotten.

I think this is way too long…
The first sentence is OK, but then I suggest:

*A temporary rule is a rule that gets removed automatically when Firefox gets closed. You can also remove all temporary rules manually by clicking on "Revoke all temporary rules" in the menu.*

Screenshot would be OK for me, but not necessary.

— That's just my two cents.

**Comment by nodiscc** [comment]
Sorry for the lack of updates, I'm short on time :/ 

I've added checkboxes for each point that needs action in the wiki, https://github.com/nodiscc/rp-website/wiki is world-editable, so anyone is free to edit it and I'll review changes after the fact.

**Comment by nodiscc** [comment]
Copied from https://github.com/RequestPolicyContinued/requestpolicy/issues/661#issuecomment-107093705:

 - [ ] Make the 1.x beta download button yellow (![](https://addons.cdn.mozilla.net/static/img/impala/warning-bg.png?b726031))
 - [ ] Subtitle this button with `1.0 is being actively developed, but due to some compatibility issues some users might not want to upgrade yet`
 - [ ] add a smaller (green) download button for 0.5 pointing to https://addons.mozilla.org/firefox/downloads/file/318770/requestpolicy_continued-0.5.29-sm+fx-linux.xpi in this section
 - [ ] subtitle this button with _old version repackaged for current Firefox_

**Comment by myrdd** [comment]
> I've added checkboxes for each point that needs action in the wiki, https://github.com/nodiscc/rp-website/wiki is world-editable, so anyone is free to edit it and I'll review changes after the fact.

Thanks for pointing that out!

Thanks also for your summary.
My suggestion: it's more wise to link to https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-continued/ instead of directly to the file. The version number might increase, no? If you think a direct link would be good, I'll try to remember to update the link.

**Comment by nodiscc** [comment]
Yes, it's more wise to link to https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-continued/ instead of directly to the file. ^

**Comment by DJ-Leith** [comment]
@nodiscc in #665 I have posted some screenshots.
The URLs are 'automatically generated by Github', just right click and "Open Link in New Tab" to find the URL. Feel free to use (or ignore) any or all of them without any attribution - you have explicit permission. Feel free to crop them, resize them *etc*. I have also added text to explain what I did. This is 'full and long winded': I am writing for people who are unfamiliar with RPC.

**Comment by DJ-Leith** [comment]
**nodiscc** said:
> Sorry for the lack of updates, I'm short on time :/ 

I appreciate that. You have still 'done plenty' in the last few days!

> I've added checkboxes for each point that needs action in the wiki, https://github.com/nodiscc/rp-website/wiki is world-editable, so anyone is free to edit it and I'll review changes after the fact.

I was reluctant to 'mess up' your good work.

I did however make two changes to
https://github.com/nodiscc/rp-website/wiki/Quickstart

* Changed spelling "explicitly".
* Added "all" to "... click the `Revoke all temporary permissions` menu item ..." to match what the User sees.

I also saw that there are now two links, "For more advanced topics, you can read the documentation below" at the end for: 

* Updating from RP 0.5.xx to RPC
* Using RequestPolicy with Default Deny and a short Whitelist

Thanks very much.

**Comment by nodiscc** [comment]
>did however make two changes to https://github.com/nodiscc/rp-website/wiki/Quickstart

Go ahead, as I said I'm notified of changes through RSS (with full diffs). Thanks for your fixes @DJ-Leith 

I'll do the button changes soon. The hard part is now to provide a conversion script for Github's wiki markdown -> HTML while preserving links, tables and other formatting, and optionally providing a prettier style than the default wiki style. I'll write a bash script that we could adapt to a Makefile (I'm very bad at makefiles).

**Comment by nodiscc** [comment]
The new website/wiki is live at https://requestpolicycontinued.github.io/ and https://github.com/RequestPolicyContinued/requestpolicy/wiki

    Upload new website/wiki:
     * Base documentation is stored in markdown files
     * On RequestPolicy's github wiki, markdown files are rendered by the wiki engine
     * On requestpolicycontinued.github.io, static HTML documentation must be built using ./build.sh
     * Note that the images URLs in markdown should be absolute URLs, even if the image is in the _media/ directory of the repo. The path defaults to https://raw.githubusercontent.com/wiki/RequestPolicyContinued/requestpolicy/_media/
     * Note that some items in the markdown documentation are still written in plain HTML (notably, tables). CSS rules from _media/github-markdown.css, as well as many HTML tags (divs, spans..) do not render on github wiki. Check the commit message.

     * The update-1.x-beta.rdf should still be present in this repo
     * The master branch should push to both
       * master on https://github.com/RequestPolicyContinued/requestpolicy.wiki.git
       * gh-pages on https://github.com/RequestPolicyContinued/RequestPolicyContinued.github.io


You just have to run `./build.sh`  to build the website from github wiki's markdown files. The wiki and the website should be used as remotes for your local repository. Building static HTML requires [pandoc](http://pandoc.org/).

Please review, report and fix any problem you may find. The wiki is world writable, just clone https://github.com/RequestPolicyContinued/requestpolicy.wiki.git, edit and push your changes, and I will gladly sync the changes to the website repo.

**Comment by myrdd** [comment]
wow @nodiscc great! Thank you for your effort!

A few questions:

 * I guess it's you who updates the website's repo @ https://github.com/RequestPolicyContinued/RequestPolicyContinued.github.io/, no? You know that I still need to edit the `xpi/update-1.x-beta.rdf` file? I hope that won't cause conflicts, it's an important file.
 * I've added some documentation to the wiki a few days ago, but I can't find it anymore. Did you change the wiki's commit history? It was a new section for ["Unit Tests"](https://github.com/RequestPolicyContinued/requestpolicy/wiki/Setting-up-a-development-environment#unit-tests-for-requestpolicy), the section was called "Marionette". Sadly I don't have an offline copy…

**Comment by nodiscc** [comment]
> You know that I still need to edit the xpi/update-1.x-beta.rdf file? I hope that won't cause conflicts, it's an important file.

I know that `xpi/update-1.x-beta.rdf` should be left untouched. The script does not alter this file.

> I guess it's you who updates the website's repo

You can also update it anytime by `git checkout`  the lastest wiki revision, running build.sh and pushing the changes to the website's repo.

> I've added some documentation to the wiki a few days ago, but I can't find it anymore. Did you change the wiki's commit history? It was a new section for "Unit Tests"

:/ I was confident that I had the latest revision. It should still be in my reflog, I'll restore it ASAP.

> I see you've rewritten the history of the website's git repo as well. Why?

I started a fresh branch (orphan) to keep a clean history of the new website. I will restore the old version to a separate branch `legacy` https://github.com/RequestPolicyContinued/RequestPolicyContinued.github.io/issues/5

**Comment by nodiscc** [comment]
Issue list for the website/wiki moved to https://github.com/RequestPolicyContinued/RequestPolicyContinued.github.io/issues

**Comment by myrdd** [comment]
Alright @nodiscc, thanks for your quick reply!

> I was confident that I had the latest revision.

Just speculating: maybe you have checked online the [history of the „Home“ page](https://github.com/RequestPolicyContinued/requestpolicy/wiki/Home/_history) instead of the [complete history](https://github.com/RequestPolicyContinued/requestpolicy/wiki/_history)? The page-specific links are on each wiki page, whereas the latter link is more hidden. In any case, nevermind, just make sure to backup and re-check the current version the next time you'll be „overwriting“ a remote branch. Still, if you have the changes in your reflog, that would be great!

> Issue list for the website/wiki moved to https://github.com/RequestPolicyContinued/RequestPolicyContinued.github.io/issues

Does *this* issue still have a purpose? If not, let's close it. :)
