### ISSUE TITLE
solve URI scheme problems

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/requestpolicy#447]
At the moment, RequestPolicy is designed to deal with Domain Names ([wikipedia](https://en.wikipedia.org/wiki/Domain_name)). But in fact RP has to deal with any kind of URI, and its syntax (see [wikipedia](https://en.wikipedia.org/wiki/URI_scheme#Generic_syntax)) allows quite a lot.

One important part of the URI is the *scheme*; common examples are `http`, `https` and `ftp`, but it includes also `about`, `mailto`, `view-source` and many others. In fact, it could be any arbitrary string, like `UT2004` for example (see #412).

As there are infinite possibilities for *URI schemes*, I'd like to generally block unknown schemes, but give the user the possibility to whitelist them. RP already has some hardcoded scheme rules (e.g. in `shouldLoad`) – the user will have the ability to extend them.

But, we have to keep one fact in mind: there are several non-http schemes which contain an *http URI* as its *path* (!).
Example: `view-source:https://github.com` – `view-source` is the *scheme*, `https://github.com` is the *path* – this is how the specification is.
In that case, we want to extract the "real URL" and check if this one is ok or should be rejected.

**My proposal** is to have several *scheme lists*:
- `normal:` URIs with such schemes are processed as always
- `recursive:` URIs with that scheme will be checked for "child" URIs
- `whitelist:` requests with *destination* URIs with such a scheme are allowed directly
The user may add schemes to the whitelist only.
Requests to unknown schemes will be blocked in general. (user will be informed)

**Example schemes:**
- `normal:` http, https, ftp
- `recursive:` view-source (already implemented (hardcoded))
- `whitelist:` {resource, about, data, chrome, moz-icon, moz-filedata, blob, wyciwyg, javascript} (see `RequestPolicyService.prototype._isInternalRequest`)

**Known schemes:** (list partly taken from [here](https://github.com/RequestPolicyContinued/requestpolicy/issues/410#issuecomment-52673007))
 * `about` – https://github.com/RequestPolicyContinued/requestpolicy/issues/131, https://github.com/RequestPolicyContinued/requestpolicy/issues/377, https://github.com/RequestPolicyContinued/requestpolicy/issues/399, https://github.com/RequestPolicyContinued/requestpolicy/issues/426, (https://github.com/RequestPolicyContinued/requestpolicy/issues/427) – see also [mozillazine](http://kb.mozillazine.org/About_protocol_links) and the `about:about` page
 * `chrome-extension` (#571)
 * `feed` – #395, #313, #386, #372
 * `gopher` (#311)
 * `jar` – https://github.com/RequestPolicyContinued/requestpolicy/issues/409
 * `magnet` – #410
 * `mailto` – #362
 * `mediasource` – #512, RequestPolicy#448 –  ~~(or [blob](http://www.w3.org/TR/FileAPI/#url)?)~~ for [Media Source Extensions](https://dvcs.w3.org/hg/html-media/raw-file/tip/media-source/media-source.html)
 * `mediastream`
 * `nxm`
 * `spotify` (#296)
 * `UT2004` (#412)

**Comment by djarb** [comment]
RequestPolicy breaks the FloatNotes addon, by disallowing requests to floatnotes:blank without providing any way to whitelist them.

**Comment by djarb** [comment]
RequestPolicy breaks the FloatNotes addon, by disallowing requests to floatnotes:blank without providing any way to whitelist them.

**Comment by myrdd** [comment]
@djarb don't you get a notification like shown in [this comment](https://github.com/RequestPolicyContinued/requestpolicy/issues/447#issuecomment-62263343)?

**Comment by myrdd** [comment]
Wait, sorry, I forgot that if that notification comes up, the request has been blocked! So I'll create a hotfix commit (beta8.2) which will whitelist the following schemes:

- `gopher` (#311)
- `spotify` (#296)
- `greasemonkey-script` (see also #562)
- `floatnotes` (https://github.com/RequestPolicyContinued/requestpolicy/issues/447#issuecomment-70780082)

I think the following extensions don't need to be allowed:
- `safari-extension`
- `chrome-extension`

I realize that whitelisting via commits isn't nice… If this issue is not fixed in the near future, a solution might be to have a setting in `about:config` for whitelisting schemes. That setting can be removed when this issue is fixed.

**Comment by myrdd** [comment]
I've released [`1.0.beta8.2`](https://github.com/RequestPolicyContinued/requestpolicy/releases/tag/v1.0.beta8.2) adds the schemes I've mentioned in the previous post to the temporary scheme-whitelist.

@djarb can you please check whether the FloatNotes issue is fixed?

**Comment by djarb** [comment]
Yes, FloatNotes is functional again.

**Comment by myrdd** [comment]
@djarb Great! Thanks for checking.

**Comment by salj** [comment]
I need a whitelist for URIs that look like "bankid:///" + some crypto tokens, which is needed for handling electronic signatures in Sweden through an external application.

**Comment by myrdd** [comment]
I've updated the milestone to `1.0.beta10`. Not sure whether that's possible, but this issue should be fixed in the near future.

**Comment by mikecardwell** [comment]
Was sent here after seeing the following error message:

> This page contains a request with a 'mediastream' scheme which us unknown to RequestPolicy. Please report it.

This page is not publicly available, but is easy to replicate. It contains a minimal video tag:

```html
<video autoplay></video>
```

And a tiny bit of javascript which requests access to the webcam and feeds video/audio into that video tag:

```javascript
navigator.mozGetUserMedia({audio: true, video: true}, function(stream) {
    var video = document.querySelector('video');
    video.src = window.URL.createObjectURL(stream);
}, function(){});
```

This works if I disable Request Policy

**Comment by At-Libitum** [comment]
I have the BetterTTV extension installed which alters the look/feel of twitch.tv
Everytime I visit a twitch channel, the yellow bar appears with the message that the page contains a request with a 'chrome-extension' scheme which it claims to not know about.

**Comment by OrdinaryMagician** [comment]
nexusmods uses the "nxm" scheme for downloading with mod managers.

**Comment by chrcoluk** [comment]
I keep seeing this message on sites.

This page contains a request with a `http` scheme, which is unknown to requestpolicy, please report it.

An example url is

http://forum.kitz.co.uk/index.php/topic,15161.msg281837/topicseen.html#new

**Comment by myrdd** [comment]
@chrcoluk weird, on that page there is an image like this:

```html
<img src="http://" alt="" class="bbc_img" />
```

So whatever the reason is, there seem to be URLs without a host. In this case you can simply ignore that message.

**Comment by chrcoluk** [comment]
well the notifications are annoying, cant they be turned off?

**Comment by myrdd** [comment]
@chrcoluk I understand that, but currently it's not possible to turn the notifications off, sorry. I'm working on it.

**Comment by alexlehm** [comment]
I have received a "this page uses a "https" scheme which is unknown to RP" notification, when looking at the source I think this is because one url is "https://" (probably a mistake by the html author).
That could probably be ignored completely since the host isn't present

**Comment by myrdd** [comment]
> I think this is because one url is "https://" (probably a mistake by the html author).

Exactly. It's the same as with "http" above. So yes, it can be ignored.

**Comment by alexlehm** [comment]
sorry, i missed the http entry above, what I meant was it could be ignored silently

**Comment by cm-mc** [comment]
rp is blocking multi web search (ff addon) scheme (http://multiwebsearch/?s=*)

**Comment by OrdinaryMagician** [comment]
I think requestpolicy might also be responsible for breaking the MEGA add-on.

**Comment by cm-mc** [comment]
Not sure about Mega, I can't load mega.co.nz, but mega.nz works, and if I change mega.co.nz addresses to mega.nz dl works ok, too.

**Comment by alexlehm** [comment]
@OrdinaryMagician there are some problems with urls using resource: as url and also ones that use an empty url (not sure where that comes from), usually this can be determined with the request log.

**Comment by OrdinaryMagician** [comment]
Actually, false alarm. Looks like the MEGA add-on breaking is just a problem with Nightly on Windows (as usual), works fine when I switch to Linux. (Dunno why I was sometimes seeing pop-ups for a "mega" uri scheme)

**Comment by cm-mc** [comment]
Any solution in sight for this problem? And if it can't be easily fixed, can we at least have RP filtering disabled for non-supported schemes, as a stop-gap measure? I really need this gone.

**Comment by myrdd** [comment]
My current plan is to allow rules that specify the scheme only, i.e. without host. In fact it's already possible to add such rules, but they are ignored.
When this is done, I'll create a new release.

The current state (commit 486ad39) is that the special requests we're talking about (requests with URIs without a host) are at least shown in the request log.

As soon as rules for URIs without host are working, those special requests have to be shown in the menu, not only in the request log.

**Comment by cm-mc** [comment]
The link above is dead (https://github.com/RequestPolicyContinued/requestpolicy/tree/dev-restartless-and-e10s).

**Comment by myrdd** [comment]
Which link are you referring to @cm-mc?

**Comment by cm-mc** [comment]
The link to the restartless build (I assume it had some sort of solution for this problem?), but I see now it has been removed.

**Comment by myrdd** [comment]
In this issue I can't find where the restartless build has been mentioned.

> I assume it had some sort of solution for this problem?

No, as far as I remember nothing has changed on the `dev-restartless-and-e10s` branch regarding this issue. But: with commit 486ad39 I've started solving the problem, see my comment above – https://github.com/RequestPolicyContinued/requestpolicy/issues/447#issuecomment-84228189.

> it has been removed.

Yes, I've removed the branch because I had merged it into `dev-1.0` previously. The merge commit is a8dc42e, which has two parent commits. Before the `dev-restartless-and-e10s` branch has been removed, commit cb7367d had been the `HEAD` of the branch.

**Comment by cm-mc** [comment]
Nvm then, thought this pointed to some sort of fix:
myrdd referenced this issue 3 days ago
restartlessness and e10s #489

**Comment by Alexander--** [comment]
Here is a page, that reproduces the issue for me: http://habrahabr.ru/company/dataline/blog/253609/#habracut. Not sure, what exactly triggers it — would be nice, of you were writing the faulty URI to browser console.

**Comment by cm-mc** [comment]
@Alexander: At least that page seems to load correctly; multiwebsearch just gives me a blank page...

**Comment by shirishag75** [comment]
Came across this http://www.off-grid.net/tag/self-sufficiency and was dumped here by requestpolicycontinued.

**Comment by xelaseer** [comment]
Just came across a 'ms-windows-store' scheme for Windows Metro desktop apps. See here http://apps.microsoft.com/windows/en-ca/app/chinese-english-dictionary/51d94dcb-ae64-4277-9b2b-ae0a809a314e.

**Comment by cm-mc** [comment]
Also http://www.startmenu8.com/pt/index.html - the odd thing: this heppened while rp blocking was disabled.

**Comment by anonsubmitter** [comment]
This page contains an unknown https scheme: https://marvel.com/comics
I don't really understand how to gather more info on it though.

**Comment by Cerberus-tm** [comment]
**ms-word** (unknown to Request Policy)
Happens when I tell One Drive (Microsoft's online storage) to open a file directly in Word. I am glad RP stopped it, though, because Word files may contain viruses, and I wouldn't want my browser to open a Word document without asking me! Or perhaps my browser would have asked my anyway based on its own content policies? At any rate, RP asked me to report this, so I did. All praise RP, I love it!

**Comment by Diapolo** [comment]
Just wanted to report ``bank://singlepaymentsepa``...

**Comment by Jiehong** [comment]
New report for unknown http: http://yasep.org/#_node_3_1

**Comment by grinapo** [comment]
http://www.albedo100.com/resellers.html
not that I get any info on what to see.. :frowning:

**Comment by myrdd** [comment]
Thank you for all your comments. Finally the main problem of this issue should be fixed. You will have to wait for the next release though, which should be ready next week.

With that release, as commit aee58a1 says, it's possible to add rules which do not specify a host, but a scheme instead. However, note that there is no menu support yet – it's tracked in issue #619.

------------------

Another part of this issue was about „nested URIs“. As this issue has grown a lot already, I've created a new issue for it, see issue #625.

**Comment by thresheek** [comment]
It still seems broken in youtube with 1.0.beta10.

**Comment by Cerberus-tm** [comment]
@thresheek  What happens on Youtube? Does Youtube use a special scheme?

**Comment by myrdd** [comment]
@thresheek maybe you're seeing this issue: #626

**Comment by Watilin** [comment]
I support this thread. The `about:reader` scheme seems to be affected as well.
For instance, in this [Washingtonpost article](https://www.washingtonpost.com/news/the-switch/wp/2015/10/26/europe-is-about-to-vote-on-net-neutrality-heres-what-you-need-to-know/) there is a photo at the bottom. In reader mode the photo is blocked.

**Comment by myrdd** [comment]
@Watilin please follow #724, as well as #619. You can work around the problem by manually adding an _allow_ rule from `about:` to `*.washingtonpost.com`. See https://github.com/RequestPolicyContinued/requestpolicy/issues/626#issuecomment-121342272 for a similar workaround.
