### ISSUE TITLE
Feature Request: Quick Link to WOT or other Safety Search

### ISSUE THREAD

**Issue by RobotManager** [RequestPolicyContinued/requestpolicy#456]
I'd love if there was a way to check domains with a single button click.

With NoScript you can click on the middle mouse button or the mouse wheel on an entry and it will automatically send you to a NoScript page full of information. This page not only links directly to the domain in question, it also provides links to security and privacy sites (Web of Trust, McAfee SiteAdvisor, Webmaster Tips, Safe Browsing Diagnostic & hpHost Report) and it also lets you allow that domain directly from the page should it appear safe.

With NoScript I can easily make several tabs for any domains I need to investigate, investigate them and then allow them from those tabs should I wish. It's a much easier and simpler process.

**Comment by nodiscc** [comment]
I think this would be the most important change to help users contributing to the subscription lists.

I'd like to add more rules to the current subscriptions (particularly `deny_trackers`) and sometimes visit pages that do a _lot_ of cross-site requests. Check http://www.speedtest.net/ for an example. Without a link to the WOT rankings, or a direct link to the blocked domains, I have to enter these URLs manually and decide for myself if these domains deserve inclusion in the `deny_trackers` subscription. This takes a lot of time.

@myrdd what's required to add this to the menu? Is it a complex change? I've tried a few hacks to add a direct link to `https://www.mywot.com/en/scorecard/$domain` to the menu but this is way over my head... I'd highly appreciate it if it could be part of the next release (the UI draft for this is in https://github.com/RequestPolicyContinued/requestpolicy/issues/601). If you can patch this I'll have a look at your commits to get a better understanding of how the menu works.

<sup>Finishing the website next week</sup>

**Comment by myrdd** [comment]
Yeah, the code for the menu is hard to understand. I'll take a look at this. I'll probably implement it on a separate branch, and WOT will open with middle click.

The "Get more info" button you describe would be slightly more work:

> Clicking on the Get more info link should open another tab with a chrome: page that clearly warns that you're about to send your info request to a third party site.

<sup>:-)</sup>

**Comment by myrdd** [comment]
@nodiscc please take a look at commit 4c7420d (the `issue-456-test` branch). Middle-clicking on origins and destinations should open a new tab.

**Comment by nodiscc** [comment]
Very nice, thanks It will speed things up. Do you think it needs a warning page as described in https://github.com/RequestPolicyContinued/requestpolicy/issues/456#issuecomment-62589476 ?

**Comment by myrdd** [comment]
@nodiscc I think that the user should be informed about the request to the external site, but still, it should be possible to disable that message. When the message is disabled, the myWOT page is opened immediately, which speeds up the workflow.

The message could be like for NoScript, see [here](https://github.com/avian2/noscript/blob/b36f915a90e02835ccce99c73422f7427cb7cfc0/xpi/chrome/locale/en-US/noscript/noscript.properties#L43):
> `You're about to ask for information about the "%1$S" site\nby submitting a query to %2$S.\nDo you want to continue?`

About how to access the page information: I think it should be possible via middle-click. I'm not sure if a link like "Get more info" is appropriate; it would make the menu bigger. On the other side, more users would discover that feature.

**Comment by myrdd** [comment]
The dialog I've been talking about will look like this:

![site-info confirmation dialog](https://cloud.githubusercontent.com/assets/4286829/12079862/ce8d75d8-b248-11e5-9539-b17b4e6c930f.png)

**Comment by nodiscc** [comment]
:clap: I think this is a great improvement. Should I add it to the doc?

**Comment by myrdd** [comment]
Yeah, finally it's merged :) I guess I'll create another pre-release this week.

> Should I add it to the doc?

That would be great! :) You've got the best overview over the docs I think.

**Comment by nodiscc** [comment]
https://github.com/RequestPolicyContinued/requestpolicy/wiki/Quickstart#blocked-destinations
