### ISSUE TITLE
Change or disable keyboard shortcuts

### ISSUE THREAD

**Issue by vzjrz** [RequestPolicyContinued/requestpolicy#460]
I recently upgraded requestpolicy to the newer beta/continued fork and noticed that requestpolicy shares a keyboard shortcut with [restartless restart](https://addons.mozilla.org/en-US/firefox/addon/restartless-restart/). They both use the keyboard shortcut 'ctrl + alt + r'. I installed this other [addon](https://addons.mozilla.org/en-US/firefox/addon/customizable-shortcuts/) to try to change requestpolicy's shortcut (as I'd like to keep 'ctrl + alt + r' for restarless restart) but was unable to find requestpolicy's shortcut entry (I did find restarless restart's). Could you guys add an option to disable this shortcut or to change it.

**Comment by myrdd** [comment]
The next version will bring these new preferences:

`extensions.requestpolicy.keyboardShortcuts.openMenu.enabled`
`extensions.requestpolicy.keyboardShortcuts.openMenu.combo`

Documentation is at https://github.com/RequestPolicyContinued/requestpolicy/wiki/Development-Basics#keyboard-shortcuts

**Comment by netjeff** [comment]
Documentation on keyboard shortcuts is now in the FAQ at https://github.com/RequestPolicyContinued/requestpolicy/wiki/FAQ#how-do-i-change-the-keyboard-shortcut-to-open-the-menu

**Comment by myrdd** [comment]
Right, thank you.
Btw I just released beta11pre4 which includes this change.
