### ISSUE TITLE
sign future XPI files

### ISSUE THREAD

**Issue by kwill** [RequestPolicyContinued/requestpolicy#465]
There are several options for hosting a security-related XPI (see #445):

* unsigned XPI on AMO (most extensions)
* signed XPI, self-hosted (e.g. HTTPS Everywhere)
* both options (e.g. NoScript?)
* signed XPI on AMO (not yet possible, should be possible in the future)

See this link for why EFF do not currently offer HTTPS Everywhere via AMO:

https://lists.eff.org/pipermail/https-everywhere/2014-April/002050.html

> The main reason I haven't put it in AMO *yet* is because AMO offers
> *less* security to users than EFF self-hosting it, ironically. AMO
> doesn't do any code signing for extensions, so they're only protected by
> HTTPS. As we saw with Heartbleed, SSL private keys can be compromised.

**Comment by myrdd** [comment]
`v1.0.beta8.2` was the first signed release.
