### ISSUE TITLE
Change wording for "Disable blocking/Enable blocking" in menu

### ISSUE THREAD

**Issue by nodiscc** [RequestPolicyContinued/requestpolicy#497]
Wouldn't it be clearer to display the _current_ state? (Blocking enabled in black /Blocking disabled in yellow)

**Comment by myrdd** [comment]
@nodiscc Did you close this issue on purpose? 2 days ago you've closed these issues:

#558
#546
#586
#601
#636
#545
#544
#520
#513
#497
#637
#638
#639

**Comment by nodiscc** [comment]
@myrdd Whoops I was mass closing old issues in may main GH issues list, and I messed up :/

https://github.com/RequestPolicyContinued/requestpolicy/issues/636 was closed on purpose (NPAPI plugins are not supported anymore), as well as https://github.com/RequestPolicyContinued/requestpolicy/issues/513, https://github.com/RequestPolicyContinued/requestpolicy/issues/637, https://github.com/RequestPolicyContinued/requestpolicy/issues/638 and https://github.com/RequestPolicyContinued/requestpolicy/issues/639 (the new addon API _will not_ allow modifying FF internal settings anyway, so the workaround I've found and am really happy with is to setup a `user.js` preferences files (you can find my config [here](https://github.com/nodiscc/user.js/blob/dbu/user.js), it's based on [pyllyukko/user.js](https://github.com/pyllyukko/user.js) in which we put a good amount of work/research). Moreover I think RPC should not try to alter these prefs since they are only a small piece of the puzzle as you can see in the `user.js` file. I know RPC already handles prefetching, but that's dubious also, and can provide a false sense of security - do a wireshark/tcpdump capture of Firefox traffic, FF still sends/receives _a lot_ of unsolicited traffic - something that the config file solves.

I suggest that this could be noted somewhere in the config UI 

>RPC does not prevent your Firefox installation from making automatic connections to some services. See [Firefox hardening](https://github.com/pyllyukko/user.js) for ways to disable these automatic connections.

So #558 #546 #586 #636 #601 #545 #544 #520 #497 were closed by mistake, you can reopen them if they are still relevant.

By the way, do you plan to port the addon to WebExtensions? On June 26, 2018 the last Firefox ESR version supporting legacy addons will be gone.
