### ISSUE TITLE
Allow rules are not working if the current contains a port

### ISSUE THREAD

**Issue by alexlehm** [RequestPolicyContinued/requestpolicy#504]
When the current url contains a port, it looks like the allow rules added manually are not working.

I am using plex.tv on my local machine, which uses a url like http://windows7:32400/web/ but references its own assets with the ip address like this http://192.168.178.21:32400/... so an allow rule from source to destination is necessary. It doesn't work with a news rss link pointing to the url of the service, so it's probably the source port, not the dest port (or its both)

this doesn't work at all, the only way to get this working is to disable request policy for this.

**Comment by myrdd** [comment]
@alexlehm is this still a bug? It works for me right now, using beta11.1

**Comment by alexlehm** [comment]
@myrdd i am still seeing the issue in beta 11.1

e.g. I have a site with the url http://localhost:4000/ that uses a few resources from http://example.com/xxx

when adding a rule for from localhost to *.example.com, the requests are blocked, only when I enable all requests to *.example.com, the requests are possible.

**Comment by myrdd** [comment]
I see. Please try also specifying the origin's port, or `*` as a wildcard. Specifying no port means "default port", which is port 80 for http.

The needed rule cannot be added through the menu, yet. See https://github.com/RequestPolicyContinued/requestpolicy/issues/473

**Comment by alexlehm** [comment]
that works, thanks.

**Comment by myrdd** [comment]
Ok, so the bug is fixed. The remaining issue is that currently the menu does not reflect the behavior, i.e. the menu doesn't show the non-default port. For that, refer to #473.
