### ISSUE TITLE
description of Subscription Policies

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/requestpolicy#510]
on `chrome://requestpolicy/content/settings/subscriptions.html` the english text currently is:

> Subscription policies are sets of rules maintained by us with help from the community. These rules are updated automatically and aim to minimize website breakage while blocking requests that impact your privacy.

I suggest to change it:

> Subscription policies are sets of rules maintained by ~~us with help from~~ the community.
> **You can subscribe to different rulesets which for example** aim to minimize website breakage ~~while blocking~~ **or block** requests that impact your privacy.
> All subscriptions you subscribe to are updated automatically from [there](https://github.com/RequestPolicyContinued/subscriptions). You are very welcome to help us maintain the lists.

What do you think? Suggestions?

**Edit:** The identifier of the string in the `*.properties` files is `subscriptionPoliciesDefinition`.
Besides the english version, there are only [italian](https://github.com/RequestPolicyContinued/requestpolicy/blob/dev-1.0/src/locale/it/requestpolicy.properties#L84) and [chinese](https://github.com/RequestPolicyContinued/requestpolicy/blob/dev-1.0/src/locale/zh-CN/requestpolicy.properties#L84) translations of the text.

**Comment by myrdd** [comment]
> It would be better to point to the "Subscriptions" paragraph that will be included in the website, on the "How to use" page (I'm currently working on it)

@nodiscc I am going to take your description from above and link to the subscriptions repo. As soon as the website is ready, we can change that link. So now the text will be:

> Subscription policies are preset rules maintained by the community. These rules are updated automatically and can fulfil different needs, such as blocking known web browsing tracking sites, or allowing requests to allow certain sites to display/work properly. [Learn more about subscriptions.](https://github.com/RequestPolicyContinued/subscriptions/)

Is this ok @nodiscc? May I close this issue then?

**Comment by nodiscc** [comment]
Ok! I updated https://github.com/RequestPolicyContinued/requestpolicy/issues/445 with current info on the website
