### ISSUE TITLE
look through old issues and categorize

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/requestpolicy#511]
RequestPolicy has been continued in July 2014. There are still more than 200 open issues, so I think it's desirable to go through them and see if thay are relevant for the [1.0 milestone](https://github.com/RequestPolicyContinued/requestpolicy/issues/446) or if they can be closed.

I'd divide this issue into several tasks, see below. The order is not important. We're finished as soon as all of the links below don't show a result.
- [x] [issues not updated since they have been imported](https://github.com/RequestPolicyContinued/requestpolicy/issues?q=is%3Aopen+updated%3A%3C2014-07-08). (imported from [here](https://github.com/RequestPolicy/requestpolicy/issues) on 2014-07-07)
- [x] [unlabeled issues](https://github.com/RequestPolicyContinued/requestpolicy/issues?q=is%3Aopen+is%3Aissue+no%3Alabel)
- [ ] [unconfirmed bugs](https://github.com/RequestPolicyContinued/requestpolicy/issues?q=is%3Aopen+is%3Aissue+label%3Aunconfirmed)
- [ ] [issues without a milestone](https://github.com/RequestPolicyContinued/requestpolicy/issues?q=is%3Aopen+is%3Aissue+no%3Amilestone) (not all issues need a milestone)

If you want to help, simply write a comment to the issue you think should be closed/is relevant/is not reproducible/… Thank you!

**Comment by Zero3K** [comment]
There's still more than 200 open issues.

**Comment by myrdd** [comment]
The most important issues are labeled already. Labeling *all* issues is not necessary, I'll label them when necessary. The amount of open issues does not matter right now. Closing.
