### ISSUE TITLE
sync user rules and prefs through Firefox Sync

### ISSUE THREAD

**Issue by nodiscc** [RequestPolicyContinued/requestpolicy#520]
There is a "RequestPolicy Sync" addon on addons.mozilla.org: https://addons.mozilla.org/fr/firefox/addon/reqpolsync/?src=api. It used to work with 0.5x. Now that the rule storage backend has changed (`user.json` file), I guess it will not work anymore.

It would be nice to have a sync option for users of Firefox Sync. For reference, Greasemonkey added sync capabilities for it's userscripts some time ago (syncs the gm_scripts directory): https://github.com/greasemonkey/greasemonkey/issues/1573.

**Comment by tYYGH** [comment]
I'd be interested as well.
I'm curently using "RequestPolicy Sync", but since RequestPolicy is not an option anymore on Firefox 38, I'm going to switch to whichever extension is going to support FF sync first: either RequestPolicyContinued, or uMatrix…

**Comment by tskirvin** [comment]
Just adding my +1 here.  Is this on anybody's radar?  Or should I look at other products?

**Comment by code-kot** [comment]
+1

**Comment by myrdd** [comment]
> Is this on anybody's radar?

Yes. As I can see, Sync integration is a feature that many people will welcome. Still, I'm currently focusing on other issues, see the [milestones](https://github.com/RequestPolicyContinued/requestpolicy/milestones). If there would be many people voting for this issue, I'd consider implementing this feature sooner.

> I'm curently using "RequestPolicy Sync", but since RequestPolicy is not an option anymore on Firefox 38, I'm going to switch to whichever extension is going to support FF sync first

@tYYGH if RP 0.5.28 still fulfills your needs, you could try [the fork I've created](https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-continued/) in conjunction with RP-Sync. Tell me if it works!

**Comment by ivan-kolmychek** [comment]
Yes, that would be nice to have. :+1:

**Comment by tYYGH** [comment]
@myrdd : I installed rpcontinued 0.5.29beta. It picked my former rp settings correctly, so I suppose sync will be fine. I'll use this for now. Thank you very much!

Still, this is "undead"/zombie code :-D I hope that I'll have some better solution in the future…
