### ISSUE TITLE
add option to allow all redirects

### ISSUE THREAD

**Issue by msxfm** [RequestPolicyContinued/requestpolicy#53]
<a href="https://github.com/jsamuel"><img src="https://avatars.githubusercontent.com/u/1240282?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jsamuel](https://github.com/jsamuel)**
_Thursday Dec 22, 2011 at 18:48 GMT_
_Originally opened as https://github.com/RequestPolicy/requestpolicy/issues/53_

---

```
imported trac ticket
created: 2009-11-05 18:34:45
reporter: black_ps
```

2 more option for start like option to allow images on all pages,this option is in firefox and to allow all pages redirect this option is in firefox too,this will be great,the addon is great,but it need at last this 2 option for start..

**Comment by rezad1393** [comment]
if there was a vote button here I would vote for this.
having to allow redirect is very annoying. I do understand the need for security reasons but its very frustrating specially now that every news website goes through many redirects to get to the intended web-page.

if this is implemented it would be a very needed feature for me.
it could be allowed globally and then deny the domains that user specifies( like dns hijacking and ISP search hijacking pages)

it would be a great option that security minded people would not enable and people like me would enable.

thank you.

**Comment by nodiscc** [comment]
If this gets implemented, I imagine you could set up rules like `{"o":{"h":"*.wiktionary.org"},"r":{"h":"*.wikimedia.org"}},` (notice the `r` for redirection rules, instead of `d` which is used for all cross-site requests). This would allow **redirects** from `o` to `r`. Example of such rules:

`{"o":{"h":"google.com"},"r":{"h":"*"}}, // allow all redirects from google domains`
`{"o":{"h":"*"},"d":{"h":"*"}},` // allow all redirects. unsafe.`

**Comment by myrdd** [comment]
What you describe @nodiscc is a solution for #173. The solution for this issue will be a pref. (That pref can be removed as soon as #173 is solved.)

**Comment by myrdd** [comment]
Voilà, it's implemented. Please try it at https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-continued/versions/1.0.beta13.1.1869.r5697d0e2.pre
