### ISSUE TITLE
not working at all for me

### ISSUE THREAD

**Issue by banther7** [RequestPolicyContinued/requestpolicy#530]
using firefox ESR Version 31.3.0 on windows 7 64 bit OS
it doesn't show all the site requests like it used to do in firefox ESR version 24.8.1. and you can tell its not blocking them because ABP shows those sites that is supposed to show to be blocked but never does.

**Comment by banther7** [comment]
i found the problem. its No-script. when ever both is enabled RS breaks.

**Comment by myrdd** [comment]
> when ever both is enabled

you mean both Noscript and Adblock Plus?

> RS breaks

What is RS?

**Comment by banther7** [comment]
i mean when No-script and Request policy is enabled it breaks request policy's functionality. also the RS was a typo i ment to say RP (request policy)
