### ISSUE TITLE
there is no changelog with the file. 

### ISSUE THREAD

**Issue by shirishag75** [RequestPolicyContinued/requestpolicy#539]
Hi all, 
Can somebody make a changelog. The last changelog is limited to  :-

    Version 0.5.28 - 2013-30-07
    
    Improvements:
    * Added lv-LV (Latvian) translation (thanks to Aleksandrs Ļedovskis).
    * Added "Support RequestPolicy" menu item
    
    Misc:
    * Removed research study code.
    
    --------------------------------

This is on debian in /usr/share/doc/xul-ext-requestpolicy on requestpolicy 1.0-b7 . While I am going to ask the maintainer to package 1.0-b8 I thought it would be beneficial if we could have a changelog.gz as well to better trace what was done.  

I have shared the changelog at dropbox, if possible make a new changelog from the old one, thank you. 

https://www.dropbox.com/s/n3v4z5o6t2li3dd/changelog.gz?dl=0

**Comment by nodiscc** [comment]
You should be able to assemble a full changelog with the command mentioned above and the more precise changelog at https://github.com/RequestPolicyContinued/requestpolicy/blob/dev-1.0/ChangeLog.md.

Closing this issues, please tell if you'd like it reopened.
