### ISSUE TITLE
Strictness can't be changed

### ISSUE THREAD

**Issue by Drugoy** [RequestPolicyContinued/requestpolicy#541]
STR:
1. After installing RP I selected 'Full domain' strictness level.
2. Later I changed it to 'Base domain' level.
3. I added 'cloudfront.net' to Whitelist > Destinations.
4. I visited http://instagram.com/p/wiXQ3GinGF/

Expected result: the page should get displayed.

Actual result: the page is not displayed because RP blocks the requests from instagram.com to a sub-domain of cloudfront.net: 
<img src="https://i.imgur.com/V3zJR8U.png">

**Comment by myrdd** [comment]
Hi @Drugoy I'm very sorry for this late answer!

- First, you're using version 0.5.x of RP. We do not provide support for that version.
- Second: The term "Base Domain" refers to the Public Suffix list – see [here](https://github.com/RequestPolicyContinued/requestpolicy/wiki#good-to-know). `cloudfront.net` is in the list just like `com`. So this isn't a bug, it's a security feature.

If you have any questions, don't hesitate to ask.

**Comment by nodiscc** [comment]
@Drugoy feel free to test the latest version from https://requestpolicycontinued.github.io/

**Comment by Drugoy** [comment]
jeez, new version looks so yummy!
