### ISSUE TITLE
Add a file containing Contributing Guidelines

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/requestpolicy#542]
I suggest to add a `CONTRIBUTING.md` file. Copied from https://github.com/RequestPolicyContinued/requestpolicy/issues/484#issuecomment-66748094:

> [CONTRIBUTING.md](https://github.com/RequestPolicyContinued/requestpolicy/blob/dev-1.0/CONTRIBUTING.md) should contain info on high priority bugs, how to report issues, debug, and donate to each individual [contributor](https://github.com/RequestPolicyContinued/requestpolicy/graphs/contributors).

I've stumbled upon this „template“: https://github.com/contribute-md/contribute-md-template/blob/master/contribute.md (website: http://contribute.md/)

Sidenote: As soon as such a file is created, a link to that file is displayed when a contributor creates an Issue or opens a Pull Request [1].

[1] https://github.com/blog/1184-contributing-guidelines

**Comment by nodiscc** [comment]
This issue is being worked on at https://github.com/RequestPolicyContinued/requestpolicy/pull/578
