### ISSUE TITLE
Wildcard "*" does not work as destination

### ISSUE THREAD

**Issue by nodiscc** [RequestPolicyContinued/requestpolicy#560]
The rule for allowing/blocking all requests from `forums.craigslist.org` ([test page](https://forums.craigslist.org/?act=Q&ID=255941720)) should be entered/created as follows:
 * Origin host: `forums.craigslist.org`
 * Destination host: `*`

Currently creating this rule (e.g. in the _Create rule_ form) **does not work**: requests are not blocked/allowed from forums.craigslist.org. **The destination host has to be blank for the rule to work**.

 _"All destinations"_ should be noted as `*`, not blank.

 * Combined to https://github.com/RequestPolicyContinued/requestpolicy/issues/559 this can be very confusing (in `Default policy: allow` as there is no menu entry, you have to add the rule manually and will fail). Creating allow rules is also affected in `Default policy: Block`.
 * It's also confusing to have rules with a blank destination in the _Active rules_ list.
 * It's also confusing to have rules with a blank destination in `user.json`
   * (rules generated by the menu actions are in the form `{"o":{"h":"*.dmz.se"}}`, they should be in the form `{"o":{"h":"*.dmz.se"},"d":{"h":"*"}}`

Found thanks to https://github.com/RequestPolicyContinued/requestpolicy/issues/556.

**Comment by myrdd** [comment]
Using `*` as the destination host has already been fixed (https://github.com/RequestPolicyContinued/requestpolicy/commit/977012d31f04aeb90e5b24d3d4ccef38f9068943).

> _"All destinations"_ should be noted as `*`, not blank.
> (...)
> It's also confusing to have rules with a blank destination in the _Active rules_ list.

I like that idea. However, see #802. Closing in favor of #803.

> * It's also confusing to have rules with a blank destination in `user.json`
>   * (rules generated by the menu actions are in the form `{"o":{"h":"*.dmz.se"}}`, they should be in the form `{"o":{"h":"*.dmz.se"},"d":{"h":"*"}}`

`host = "*"` is not the same as `host = undefined`. For details and comments, please see #802.
