### ISSUE TITLE
Show the redirection bar only on explicit user interaction

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/requestpolicy#561]
Currently the redirection notification bar is displayed if *any* request in a Tab causes a redirect. But instead, it should only be displayed in case of an explicit user interaction. Examples for *explicit user interaction*:
  - an url has been entered in the location bar
  - a link has been clicked
  - a form has been submitted
  - back/forward buttons
  - page reload
  - …

A mozmill test has already been created, but it's disabled for now.

For details, see commit 2022377

**Comment by genodeftest** [comment]
What is non-explicit user interaction?
Some websites (sorry, I don't have an example available) work like this:
1. you load the web site, focus the search field and enter a search term
2. a new URL (same server) is loaded.
3. server sends a HTTP redirect to another web server

In this case the redirect is no direct result of a user interaction. Would it be filtered/blocked by RP anyway?

**Comment by myrdd** [comment]
I think the point is that there might be an embedded object, such as an image, that might cause a redirect which is blocked by RP. If you see a redirection notification and you click on "Allow", your browser will navigate to the image – but instead, you just wanted to display it on the website.

So maybe the title of this issue should be: „Show the redirection bar only **if a new document should be loaded**“ – the document could be either the "top level" document or a document in an iframe.

**Comment by myrdd** [comment]
If this bug gets fixed, #630 gets fixed as well.

**Comment by Gittyperson** [comment]
I also getting a persistent top pop-up with the very recent new version(s) in my start.me start page. No problem in the previous version (beta 3 I think?).

![requestpolicy](https://cloud.githubusercontent.com/assets/7165208/7435970/66018e8c-f051-11e4-9af8-14e67721bc5a.jpg)

**Comment by Gittyperson** [comment]
Forgot to mention I've added an Allow *.start.me user rule (no destination). Top notification also occurs on another site where's I've added the same Allow rule.

**Comment by myrdd** [comment]
@Gittyperson that's exactly what this issue is about. In your case there's an inline element which causes the redirect. As the notification bar says, the request's origin domain is `www.google.com`.

BTW, if you've got a "deny" rule to `*.doubleclick.net` then #630 affects you as well.

**Comment by ansell** [comment]
Would the redirect happen if the bar didn't show up, or would it just be more difficult to get to it? 

I don't like the idea of websites redirecting any requests to other servers without my knowledge, and stopping that happening automatically is one of the main reasons I use RPC. If an embedded object is able to redirect freely then it opens up a large number of security cases involving iframes.

**Comment by myrdd** [comment]
> Would the redirect happen if the bar didn't show up, or would it just be more difficult to get to it?

@ansell you're talking about redirects of inline elements, no? When using "default deny" any redirect is blocked, except if there's an "allow" rule that matches.

When this issue is fixed, the bar would never show up for "inline redirects", but the redirect would be blocked nevertheless. But that "redirect request" will still go into the menu, like any other request.

**Comment by Gittyperson** [comment]
Thanks myrdd. Using the default Allow policy and haven't manually blocked anything. Only a few manual allow rules (no destination), including start.me. Had to revert to beta 8.2 due to this issue.

**Comment by myrdd** [comment]
I think I've found a way to fix this problem, so I guess there will be another bugfix release.

**Comment by myrdd** [comment]
I've committed a fix.
@Gittyperson and @Whissi (via #630) if you have some time, please check if it works for you. The fix is currently on branch [`hotfix-1.0.beta9.2`](https://github.com/RequestPolicyContinued/requestpolicy/tree/hotfix-1.0.beta9.2).

**Comment by Whissi** [comment]
Looks good! I don't get the bar anymore... Thanks!

**Comment by Gittyperson** [comment]
Sorry, feel a bit stupid but can't figure out where/how to download/install it.

**Comment by Whissi** [comment]
You need to build the add-in from source on your own. Follow the readme.

Or if you trust me, you can use my version: https://www.dropbox.com/s/rhm3uscw5nvj2kq/requestpolicy_be41aa5eb5.xpi?dl=1

**Comment by Gittyperson** [comment]
Thank you Whissi and thanks a lot for the fix myrdd, not getting the top bar any more.

**Comment by myrdd** [comment]
Thanks for testing. I'm glad it helped! :)

The hotfix release is out. Happy surfing! :)
