### ISSUE TITLE
RP 1.0b8.1 doesn't play nicely with GM_getResourceURL?

### ISSUE THREAD

**Issue by carlclark** [RequestPolicyContinued/requestpolicy#562]
https://github.com/RequestPolicyContinued/requestpolicy/issues/447#issuecomment-66747728 seems to have experienced this already, but I'm not sure it's really quite the same issue. Anyway, a script that tries to put an img with a GM_getResourceURL src silently fails, and whitelisting `*://example.com` -> `greasemonkey-script://*` doesn't seem to do the trick. Nor does the request log show anything.

However, disabling RP does, of course, fix the problem.

**Comment by myrdd** [comment]
@carlclark could you please tell me:
- Do you use AdsBypasser? / Is this problem related to [AdsBypasser](https://greasyfork.org/en/scripts/4881-adsbypasser)?
- Does the `greasemonkey-script` URI have a host? If it has a host, it looks like `greasemonkey-script://this.is.the.hostname.com/`, otherwise there are three consecutive slashes.

> whitelisting `*://example.com` -> `greasemonkey-script://*` doesn't seem to do the trick

I'm not sure if this works at all, as #447 is not fixed yet.

> disabling RP does, of course, fix the problem

so it's definitely a RP problem

**Comment by carlclark** [comment]
@myrdd It's a custom script I'm writing; the intended use is dynamic favicons, but I'd be satisfied with just getting an img to work. The generated URL looks like `greasemonkey-script:2b656ef8-f67f-4a80-bbf5-a936da3fb0be/off`; I'm still on 1.15.

The whitelisting was just a shot in the dark, since I know problems with Keefox are resolvable that way.

**Comment by myrdd** [comment]
> `greasemonkey-script:2b656ef8-f67f-4a80-bbf5-a936da3fb0be/off`

This definitely is a scheme without a host.
FYI: More on URI schemes: https://github.com/RequestPolicyContinued/requestpolicy/wiki#good-to-know

But… isn't there a notification bar just like in this example:?

![notification of mediasource being an unknown scheme](https://cloud.githubusercontent.com/assets/4286829/4964726/a80aa5ea-676a-11e4-9976-23fe276a8f64.jpg)

> I'm still on 1.15

is this a greasemonkey version?

**Comment by carlclark** [comment]
There's no notification bar, no.

1.15 is the best available GM version for Pale Moon.

**Comment by myrdd** [comment]
I can confirm that in Pale Moon – but also in Firefox – there's no notification bar. I'll see if I can fix this bug for the next version.

**Comment by myrdd** [comment]
@carlclark: Release [`1.0.beta8.2`](https://github.com/RequestPolicyContinued/requestpolicy/releases/tag/v1.0.beta8.2) adds the `greasemonkey-script` scheme to its temporary scheme-whitelist. Please check if it works after updating. If not, you can reopen this issue.
