### ISSUE TITLE
[restartless/e10s] Option to allow requests to the same domain stopped working

### ISSUE THREAD

**Issue by nysatrok** [RequestPolicyContinued/requestpolicy#564]
At the moment the option to allow requests to the same domain doesn't work anymore on the dev-restartless-and-e10s branch with current Firefox Nightly.

**Comment by Link-Satonaka** [comment]
Confirmed, bug happens under firefox 35.0 as well

**Comment by myrdd** [comment]
Fixed by `ee73cef` on `dev-restartless-and-e10s`.
