### ISSUE TITLE
[restartless/e10s] Blocked own (sub?)domain

### ISSUE THREAD

**Issue by ldgbc** [RequestPolicyContinued/requestpolicy#567]
Using: RP e10s : latest commit a2d1bdf
Firefox 34.0

Test URL: https://github.com/RequestPolicyContinued/requestpolicy/

RP is blocking "assets-cdn.github.com" which is a subdomain(?)
![rules list](https://cloud.githubusercontent.com/assets/1805303/5676141/a9c99546-9823-11e4-9fae-e34c3caae0f8.jpg)

**Comment by myrdd** [comment]
Yes I know, it even happens when you enter `google.com` – it shows a redirection notification to `www.google.com`.

Btw thank you for testing!

**Comment by myrdd** [comment]
Fixed by `ee73cef` on `dev-restartless-and-e10s`.
