### ISSUE TITLE
[restartless/e10s] Allow adding non-temporary rules when using Private Browsing Mode

### ISSUE THREAD

**Issue by ldgbc** [RequestPolicyContinued/requestpolicy#568]
Using: RP e10s : latest commit a2d1bdf
Firefox 34.0

Test URL: https://github.com/RequestPolicyContinued/requestpolicy/

Although the setting "Menu > Allow adding non-temporary rules when using Private Browsing Mode"
is enable, only "Temporarily allow" option is offer, see #567 or #566 image

**Comment by myrdd** [comment]
Seems like this works correctly on 3e995480b69c3ef6540d385a35b73ecb0ced232f. If think this is not fixed, please reopen the issue.
