### ISSUE TITLE
[e10s] Help/About menu does not open URL in e10s tab

### ISSUE THREAD

**Issue by ldgbc** [RequestPolicyContinued/requestpolicy#569]
Using: RP e10s : latest commit a2d1bdf
Nightly: 37.0a1 (2015-01-08)

In RP option, clicking on "About" or "Help" will open a new tab to the following URL, however using e10s windows in Nightly URL will not open, it will just open a blank tab.
https://requestpolicycontinued.github.io/#about
https://github.com/RequestPolicyContinued/requestpolicy/wiki#help-and-support-for-users-and-developers

**Comment by myrdd** [comment]
This is only a bug when e10s is enabled, so I'll update the title. See also my comment here: https://github.com/RequestPolicyContinued/requestpolicy/issues/489#issuecomment-71337456

**Comment by ldgbc** [comment]
Closing this, it seem to be working with
Nightly 39.0a1 (2015-03-20)
RP: https://github.com/RequestPolicyContinued/requestpolicy/commit/581e2b8547917df903a8d4664728f1c469a5109e

**Comment by myrdd** [comment]
Indeed, thanks for rechecking!
