### ISSUE TITLE
[restartless/e10s] Enable/Disable blocking problem

### ISSUE THREAD

**Issue by ldgbc** [RequestPolicyContinued/requestpolicy#570]
Using: RP e10s : latest commit a2d1bdf
Firefox: 34.0
Test URL: https://github.com/RequestPolicyContinued/requestpolicy/

1) Using RP icon > Click "Disable Blocking"
RP icon will turn from the "Red" color to the "Yellow" color and will be stuck in this color till browser reset.

2) Disable blocking does not seem to work either, after clicking "disable blocking", closing the menu by clicking outside of it and re-open RP context menu will indicate that blocking is still enable

2.1) Clicking "disable blocking", try clicking it again on "enable" blocking does nothing.

**Comment by myrdd** [comment]
It's fixed by commit 0825bbd :)
