### ISSUE TITLE
twitch

### ISSUE THREAD

**Issue by JoceOne** [RequestPolicyContinued/requestpolicy#571]
Hi, let me report this as recomended on the RP chrome banner :
![twitch rp](https://cloud.githubusercontent.com/assets/8218764/5743471/cd9e915c-9c19-11e4-8ef9-30f915cebcec.JPG)

is it related to a "Stylish" custom css stylesheet that I use for this website ?

thx

**Comment by myrdd** [comment]
Hi @JoceOne thank you for reporting this. This message will not show up again as soon as issue https://github.com/RequestPolicyContinued/requestpolicy/issues/447 is solved. `chrome-extension` is an URI scheme used by Google Chrome and has nothing to do with your stylesheet.

**Comment by myrdd** [comment]
I close this issue as it's discussed in #447.
