### ISSUE TITLE
[restartless/e10s] Request Log empty

### ISSUE THREAD

**Issue by ldgbc** [RequestPolicyContinued/requestpolicy#575]
Firefox 35
RP: https://github.com/RequestPolicyContinued/requestpolicy/commit/beafc6076947096d5528c6875f27f6a21da1d2a0
Test URL: https://requestpolicycontinued.github.io/

"Request Log" does not list any block/allow list. It just empty

**Comment by myrdd** [comment]
fixed in de355b8
