### ISSUE TITLE
[restartless/e10s] about:requestpolicy / Preferences empty in e10s

### ISSUE THREAD

**Issue by ldgbc** [RequestPolicyContinued/requestpolicy#576]
Nightly: 38.0a1 (2015-01-18)
RP: https://github.com/RequestPolicyContinued/requestpolicy/commit/beafc6076947096d5528c6875f27f6a21da1d2a0

When opening RP's preferences or "about:requestpolicy", RP setting can be configure there. In e10s mode the preferences is empty (no text) and blank "checkbox"

**Comment by myrdd** [comment]
this works for me on `beafc60`. Can you please check the Browser Console and/or stderr output?

**Comment by ldgbc** [comment]
I can't seem to reproduce it. Closing this then.

**Comment by myrdd** [comment]
Okay. However, the problem you've described is familiar to me. The pref page looks like you described when there's a crash somewhere.
