### ISSUE TITLE
RP icon moving to adress bar on its own.

### ISSUE THREAD

**Issue by LtPinback** [RequestPolicyContinued/requestpolicy#580]
Nightly 38.0a1 (2015-01-23)
RP 1.0.beta8.1

On opening Firefox or opening a new window the RP icon which I have located at my addon bar via classic theme restorer moves itself to the address bar. No other addon does this.

**Comment by acrobat1** [comment]
Have you checked "Movable status panel" in CTR preferences? It's in the General UI page of CTR options.

**Comment by myrdd** [comment]
@LtPinback I can confirm this, but it's solved on the [`dev-restartless-and-e10s`](https://github.com/RequestPolicyContinued/requestpolicy/tree/dev-restartless-and-e10s) branch which will be merged for the next beta release, so I'll close this issue.
