### ISSUE TITLE
Ruleset fails to load due to _addDomain throwing TypeError on "*.ad.watch.impress.co.jp"

### ISSUE THREAD

**Issue by codeman38** [RequestPolicyContinued/requestpolicy#582]
It appears that `subscriptions/official/deny_trackers.json` is being completely ignored in version 1.0.beta8.1, despite being present in my profile directory and included in `subscriptions.json`.

Steps to reproduce:
1. Install RequestPolicy.
2. In *Manage Policies* -> *Subscriptions*, check "Block destinations that can track you".
3. Go to http://www.cheezburger.com/, view the request log, and note that all of the trackers defined in `deny_trackers.json` are getting through.

Firefox version: 35.0, Mac OS X

**Edited to add:** Found the cause of this. One of the entries in `deny_trackers` is `*.ad.watch.impress.co.jp`, and for some reason, this causes `Ruleset._addDomain` to throw a TypeError - which causes the parsing of the entire ruleset to end prematurely.

**Edit 2:** Added some debugging statements to test this, and *ouch* - because "watch" is a property name predefined by Mozilla's JavaScript engine, it looks like `_lower['watch']` returns a predefined function:

```
nextLevel = function watch() {
    [native code]
}
```

**Comment by codeman38** [comment]
Tested this further; it looks like the `allow_*` subcriptions are working fine when the default is deny, just not the other way around.

**Comment by codeman38** [comment]
Pull request to fix this: #583

**Comment by myrdd** [comment]
wow, great work @codeman38! Thanks for the pull request it works. I'll create a hotfix (1.0.beta8.2).

I'll keep in mind to use `hasOwnProperty` whenever possible.

**Comment by myrdd** [comment]
New version [`1.0.beta8.2`](https://github.com/RequestPolicyContinued/requestpolicy/releases/tag/v1.0.beta8.2) is released. This bug is fixed in that version. Thanks again @codeman38
