### ISSUE TITLE
[restartless/e10s] version AMO's Available Update Check & Offer

### ISSUE THREAD

**Issue by ldgbc** [RequestPolicyContinued/requestpolicy#584]
Not sure if this can be consider a bug or not but it wasn't a problem in older version.

Using FF35
RP https://github.com/RequestPolicyContinued/requestpolicy/commit/25a61e0ae9896b1a3941d0d1e76072bb5202b48d

Using Add-ons Manager to check for RequestPolicy update, it will offer the update release for "Master" branch, ie. RP1.0beta8.2

Which it really shouldn't be doing that considering it different branch and it outdated.

**Comment by myrdd** [comment]
whoops, you are right. I'll set the version to something infinite

**Comment by myrdd** [comment]
okay, the version string is now `1.x.dev`. I just shouldn't forget to change the string back to something like `1.0.beta8.2` before releasing, otherwise there would be the opposite problem: the extension does not update anymore.

**Comment by ldgbc** [comment]
@myrdd Just tried https://github.com/RequestPolicyContinued/requestpolicy/commit/a3d31c1b890aa1fec8881367f0bc0fb2e5e69cc0
The version name is changed to 1.x.dev but checking for update using AMO still offer 1.0.beta8.2

**Comment by myrdd** [comment]
Sorry @ldgbc I made wrong assumptions and did no testing. Commit d2c9d835e228e01d61f98ddda17a070ee400f122 should now really fix this issue.
