### ISSUE TITLE
[restartless/e10s] "blank" rules when Javascript disable.

### ISSUE THREAD

**Issue by ldgbc** [RequestPolicyContinued/requestpolicy#590]
Using FF35
RP 25a61e0

Test URL: https://board.jdownloader.org/search.php

Step: 
Disable Javascript either using "about:config / javascript.enabled;false" or something like NoScript.
Open RP context menu; it will just show "https", 

Note: This is "Google's Recaptcha" being blocked here but when JavaScript is disable RP will display it just as "https"
However it seem to be only on certain select site, for example, http://forums.mozillazine.org/ucp.php?mode=register also use Google Recaptcha but doesn't have this problem.

**Comment by myrdd** [comment]
I think you've just discovered a bug on the jdownloader site. They've put an invalid URI into their `<noscript>` part in html. On https://board.jdownloader.org/search.php the html is:

```html
	<noscript>
		
			<iframe src="https://https://www.google.com/recaptcha/api/noscript?k=(…)" height="300" width="400" frameborder="0"></iframe>
		
	   <br />
	   <textarea name="recaptcha_challenge_field" rows="3" cols="40">
	   </textarea>
	   <input type="hidden" name="recaptcha_response_field" value="manual_challenge" />
	</noscript>
```

whereas on http://forums.mozillazine.org/ucp.php?mode=register after clicking on *I agree* the html is:

```html
		<noscript>
		<div>
			<object data="http://www.google.com/recaptcha/api/noscript?k=(…)" type="text/html" height="300" width="500"></object><br />
			<textarea name="recaptcha_challenge_field" rows="3" cols="40"></textarea>
			<input type="hidden" name="recaptcha_response_field" value="manual_challenge" />
		</div>
		</noscript>
```

`https://https://www.google.com` definitely is *no* valid URI. So this is not a RP issue.
