### ISSUE TITLE
Completely disable RPC on select sites? (incl. Other Origins)

### ISSUE THREAD

**Issue by Gittyperson** [RequestPolicyContinued/requestpolicy#604]
Hello, newbie question here. There a few websites that I want all of their ads displayed and nothing blocked. I can't find a way to enable some blocked items reported in the "Other origins" box just for select websites from the UI, looks like I'll have to globally enable them. These items block ads (doubleclick.net, googleanalytics etc). Maybe it's possible via 'Manage Policies'? Thanks a lot.

**Comment by nodiscc** [comment]
Hi @Gittyperson can you send a screenshot of the RP menu when you're on that site?

**Comment by Gittyperson** [comment]
Thanks nodiscc. Selecting "Stop blocking requests to *.googlesyndication.com will show ads again on that site for example (while there are still "Other origin" requests being blocked). That creates a user rule with no origin and *.googlesyndication.com as Destination and I assume that rule will apply to all website. I guess I'm looking for a way to disable some or all "Other origin" entries just for specific website.
![request policy continued box](https://cloud.githubusercontent.com/assets/7165208/6513027/a5c16acc-c380-11e4-8ccb-7dda12789e28.jpg)

**Comment by nodiscc** [comment]
If I understand well, you want to block requests to `googlesyndication.com` from everywhere, except when you're on `thepressproject.gr`?

**Comment by Gittyperson** [comment]
Thanks. Yes, I think that's it although these are just examples. It'd be nice if some or all "Other origins" blocked items could be allowed from the UI for specific websites. Also, I'm not sure if it can be done manually in Manage Policies.

**Comment by nodiscc** [comment]
Ok. I just got it. I should have asked what your default policy was, and if you had subscriptions enabled. Your default policy seems to be _Allow_ and you seem to have the _Deny trackers_ subscription enabled.

This seems to be bug https://github.com/RequestPolicyContinued/requestpolicy/issues/491. You cannot combine multiple policies for a specific destination.

Does that description match your problem?

**Comment by Gittyperson** [comment]
It looks a lot like my issue, although my configuration is a different (you described it correctly) and the description confused me a bit. My hopefully more simple explanation is: currently, everything that falls in the "Other Origins" category cannot be handled (allowed or disabled) on a per site basis, but only globally. When I say "per site", I mean the site we are currently navigating in the browser, not the sites listed in "Other Origins".

**Comment by nodiscc** [comment]
Things start to get clearer :) I think you expect an option like:

`Allow requests from *.doubleclick.net to *.googlesyndication.com when current tab is on thepressproject.gr`

Right?

**Comment by Gittyperson** [comment]
Yes that's it, thanks again. Hope you could also consider an Allow/Block all "Other origins" for current tab option, to avoid having to select each and every one of them on each website. This would also help if additional "Other origin" requests appear at a later date, and the user hasn't manually selected them. More briefly, an "Always Allow/Block All Other origin requests for current tab" option.

**Comment by nodiscc** [comment]
@Gittyperson I'm not the developer @myrdd has been busy these days and I just do some maintenance/bug triaging/other stuff.

I personnally don't think this is a good thing to add (have you seen that action text? `Allow requests from *.doubleclick.net to *.googlesyndication.com when current tab is on thepressproject.gr`). Things could get very complicated in the menu. By the way, RPContinued only works on the `origin -> destination` model and I'm fine with that. Just allow `doubleclick.net -> googlesyndication.com` everywhere if you need it (do you really want to allow ads/trackers?). Allow `thepressproject.gr -> googlesyndication.com` and block it everywhere else.

Have you tried the default _Block_ mode? It's got easier to use with some recent changes to the [ subscriptions](https://github.com/RequestPolicyContinued/subscriptions).

**Comment by Gittyperson** [comment]
Thanks for the suggestions nodiscc. Basically, I'm only looking to *completely* disable RPC on select websites I really like, just to support them with their ad revenue or whatever it is they get. This is common practice with Ad-blockers for example. I've tried the privacy-conscious Block mode, but it's too much work (for me at least) to make many websites work again, whereas with Allow mode almost everything works fine, there's excellent default blocking and I'd only have to whitelist a few websites for the above reasons. Perhaps if a way was found to "turn off" RPC on user-selected websites instead of messing with multiple, complicated rules, would make this easier.
I'll give the Block mode another try though.

**Comment by nodiscc** [comment]
When/if https://github.com/RequestPolicyContinued/requestpolicy/issues/491 is fixed, you could disable ad blocking on selected sites, and keep them blocked everywhere else (_Deny trackers_ subscription). I also have this problem.

Feel free to click the subscribe button on https://github.com/RequestPolicyContinued/requestpolicy/issues/491 to get updates about this issue. If there's still a _Other origins_ menu problem after the fix (I think there is one), we can open another issue.

**Comment by myrdd** [comment]
@Gittyperson I understand this as a feature request. I've created #605.
