### ISSUE TITLE
change the extension ID

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/requestpolicy#609]
This is part of #543.

The ID could be for example `rpc@requestpolicy.org`, see [here](https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#id). Currently it's `requestpolicy@requestpolicy.com`.

-----------------------

I think the extension with the new ID should **not** use the "old" preferences and rules, but instead **copy** them:

 - preferences: the prefix will change from `extensions.requestpolicy.` to `extensions.rpcontinued.`
 - rules: the folder name will be e.g. `requestpolicy-continued/` instead of `requestpolicy/`.

This guarantees there will be no conflicts. In addition, both old and new versions could be installed at the same time. Any thoughts? What do you think @nodiscc?

**Comment by nodiscc** [comment]
I'd say:

 * Check if `extensions.rpcontinued.migrated` exists and is set to true.
 * If yes, do nothing.
 * If no, copy `extensions.requestpolicy.` prefs to `extensions.rpcontinued.` prefs, copy the whole `requestpolicy` directory to `requestpolicy-continued/`, then write `extensions.rpcontinued.migrated = true`

This prevents overwriting your RPContinued rules with the legacy RequestPolicy ones if it's already done, and saves time by skipping these checks/migrations.

`rpcontinued@requestpolicy.org` would make sense as the addon ID.

**Comment by myrdd** [comment]
I like your idea about `extensions.rpcontinued.migrated`, but I think we don't need it. There are the two cases:

- When `false`, we need to
  - check if there is data from RP
  - check if there is already data from RPC ⇒ if yes, this is a conflict!
- When `true`, we need to
  - check if there is already data from RPC ⇒ if not, we need to create the prefs and folders.

So in any case RPC needs to check for RPC's prefs and folders. It needs to check for RP's prefs and folders if and only if RPC's prefs and folders are not present.

In any case, I think the `migrated` pref would mainly answer „Is this RPC's first run?“, but there are other possibilities to check whether it's the first run of RPC.

> saves time by skipping these checks/migrations

Afaict those checks are quite fast compared to other tasks in RPC. :)

> `rpcontinued@requestpolicy.org` would make sense as the addon ID.

Agreed!

**Comment by nodiscc** [comment]
Ok your solution is much simpler :)

 * Check if RPC prefs and folders exist.
 * If no, check if corresponding RP prefs and folders exist, migrate them to RPC.
 * If no old prefs/folders exist, create new RPC ones using the defaults.

Is this right?

> both old and new versions could be installed at the same time

This would have interesting results... should it be allowed/discouraged?

**Comment by myrdd** [comment]
> Is this right?

Precisely!

> This would have interesting results... should it be allowed/discouraged?

I've thought about disallowing having both RP and RPC installed at the same time, but I think allowing is the better way, regardless of whether this "feature" is used or not. We just need to make sure that there won't be conflicts. So any names that are global in the browser must be unique, i.e. any usage of the name `requestpolicy` will be `rpcontinued` instead. For example RPC's settings will be at `about:rpcontinued`. Some more locations where names will be changed:

 - all IDs and class names of chrome or content DOM elements. Many but not all of them are in the [CSS file](https://github.com/RequestPolicyContinued/requestpolicy/blob/v1.0.beta8.2/src/skin/requestpolicy.css), for example.
 - the [overlay](https://github.com/RequestPolicyContinued/requestpolicy/blob/v1.0.beta8.2/src/content/overlay.js#L41) which is added to each `window` object
 - the names and IDs of [chrome registrations](https://developer.mozilla.org/en-US/docs/Chrome_Registration#content-instruction), such as `content://rpcontinued/` and the IDs of XPCOM Components
 - maybe more which I did not think of

So essentially – at least internally – the word `requestpolicy` won't be used anymore.

**Comment by myrdd** [comment]
I've done some work on a branch named `new-extension-id`. Note that the current state is *definitely* not for production use – especially because there's no import functionality yet. Implementation of the import of "old" rules will be the main work before there can be a new release.

**Comment by myrdd** [comment]
I've been thinking about the proposed changes. Until now I've been suggestig to change the following user-facing interfaces:

| what? | current value | ~~future value~~ (?) |
| ---------- | --------- | -------- |
| settings URL | `about:requestpolicy` | `about:rpcontinued` |
| subdirectory in the profile-dir | `requestpolicy` | `requestpolicy-continued` |
| prefix of the preferences | `extensions.requestpolicy.` | `extensions.rpcontinued.` |

The tradeoff whether to change the values (table above) or not is:

 - **changing them…**
  - …might confuse the users. IMO Confusion about the different versions of RP and RPC is already high enough.
  - …could break users' tools, in case they access the prefs and/or the subdirectory directly.
  - …would emphasize RPC being something different that RP, but I intend to rename RPC back to „RequestPolicy“ in the long term (see #667). If the settings URL were changed to `about:rpcontinued`, it would make sense to change it back; but that would be bad style, and would probably confuse users.
 - **keeping them…**
  - …might cause problems when both RP and RPC are installed

At the time I've been creating this issue I thought it would be necessary to *change* all those values; I thought the AMO team would require that. But I've talked to AMO editors and it doesn't seem to be a problem. Therefore I'm quite certain that *keeping* the values (in the table) is the better option.
