### ISSUE TITLE
Block count increase after refresh webpage

### ISSUE THREAD

**Issue by ldgbc** [RequestPolicyContinued/requestpolicy#611]
RP: https://github.com/RequestPolicyContinued/requestpolicy/commit/581e2b8547917df903a8d4664728f1c469a5109e
Firefox 36.0.4
Test website: http://forums.mozillazine.org/viewforum.php?f=23

Open RP, it will say, "mozillazine.org 40 blocks" at first visit.
Refresh test website http://forums.mozillazine.org/viewforum.php?f=23 it will be "mozillazine.org 61 blocks"
Keep refreshing and count will increase.

**Comment by SkySkimmer** [comment]
On my computer F5 refresh doesn't increase the count (although it varies by ~10 up and down).
Going to the URL bar and hitting enter does increase the count.

**Comment by ldgbc** [comment]
You're right, thanks for the clarification. Ctrl+R also does nothing too.

**Comment by myrdd** [comment]
Confirmed. I will write a test using [`iframe_3.html`](https://github.com/RequestPolicyContinued/requestpolicy/blob/dev-1.0/tests/content/iframe_3.html). Milestone to fix this is the next release.

**Comment by myrdd** [comment]
This problem still exists.

* E10s disabled: Going to the URL bar and hitting enter does increase the count.
* E10s enabled: Any way of refreshing the URL increases the count.
