### ISSUE TITLE
Hotkey Conflict - Ctrl+Alt+R - Reading List

### ISSUE THREAD

**Issue by ldgbc** [RequestPolicyContinued/requestpolicy#612]
With Nightly 39.0a1 there is a feature call "Reading List", the sidebar can be activate by using hotkey Ctrl+Alt+R, RP also used this (hotkey) to open up the context menu.

**Comment by acrobat1** [comment]
Which context menu? I don't have a context menu, as in _right-click_ menu.

**Comment by nodiscc** [comment]
Ctrl+Alt+R opens the requestpolicy menu (toolbar menu)

What can be done to prevent this? Make the RP hotkey configurable?

**Comment by acrobat1** [comment]
That would be good.  Ctrl+Alt+R also conflicts with a restart extension, which is quite inconvenient -although,  I've always used the toolbar icon for RP so far.

**Comment by nodiscc** [comment]
Blocked by #616

**Comment by myrdd** [comment]
@ldgbc What do you think should be the new default shortcut?

As a workaround you can try to follow that description:
http://superuser.com/questions/145280/firefox-can-i-change-the-keyboard-shortcuts-for-tab-switching/333562#333562
The command for opening RP's menu is: `gBrowser.ownerGlobal.requestpolicy.overlay.openMenuByHotkey()`

**Comment by ldgbc** [comment]
Since the letter "R" as in "RequestPolicy" is quite important, I think "Alt+R" work quite well. 

Default Firefox and/or with my current Add-on setup I see no Hotkey conflict using "Alt+R". Furthermore this combination is one (1) key less so it should be more convenient compared to the current default hotkey (Ctrl+Alt+R).

**Comment by myrdd** [comment]
Okay, I think `Alt + R` is good.

> I'm uncertain if there any other add-on that uses Alt+R though.

For sure. That's why the shortcut should be configurable – #616.

**Comment by myrdd** [comment]
The shortcut will be Alt+R by default in the next release. See commit 4e80782.

**Comment by myrdd** [comment]
I've just read that `Alt-Letter` combinations would be a problem on Macintosh, so the shortcut will be `Alt-Shift-R`.

> Alt-Letter combinations are reserved for entering special characters in text

See https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/hotkeys#Hotkey%28options%29
