### ISSUE TITLE
Adblock Plus in FAQ

### ISSUE THREAD

**Issue by davidhedlund** [RequestPolicyContinued/requestpolicy#613]
Perhaps you want to add "Adblock Plus (ABP) and ABP-based add-ons" to https://requestpolicycontinued.github.io/#faq-noscript

Please do not confuse "Adblock" (that is forked of ABP) with "Adblock Plus".

**Comment by nodiscc** [comment]
Hi @davidhedlund we have a link to other addons at https://requestpolicycontinued.github.io/#other-addons. The noscript chapter is just about the differences between noscript and requestpolicy

**Comment by davidhedlund** [comment]
Yes but you can add a new chapter about the difference between RP and ABP as its a very popular add-on.

**Comment by nodiscc** [comment]
I wouldn't know what to add as RP and ABP have almost nothing in common. RPContinuned gives you a default policy for cross site requests; ABP/µBlock blocks content based on URL patterns from lists. But you could send a Pull Request for https://github.com/RequestPolicyContinued/RequestPolicyContinued.github.io with the changes you suggest?

**Comment by davidhedlund** [comment]
On 2015-03-30 17:37, nodiscc wrote:
>
> RP and ABP have almost nothing in common.
>


This is good info for the end users of your program. Its enough.

**Comment by nodiscc** [comment]
@myrdd what do you think? (about content. Page organization is another subject, I'm working on it)

**Comment by myrdd** [comment]
I think the main reason why NoScript is mentioned is that it's an important complementary addon in terms of security and privacy. In addition to that, NoScript and RP both are designed for user control, i.e. they both have a menu which gives control to the user. ABP *might* have some of the aspects I've mentioned, but not to the extent of NoScript & RP. I encourage to link to the prism-break project for a list of addons.

I however am willing to answer any question arising. I guess your question has been answered @davidhedlund? I'm closing this issue.
