### ISSUE TITLE
Keefox and RequestPolicy Continued Conflict

### ISSUE THREAD

**Issue by chinaar** [RequestPolicyContinued/requestpolicy#615]
Hi there,
It appears that there is a conflict between Keefox and RequestPolicy Continued with regards to blocking of websockets which Keefox uses to communicate with the Keepass database. I continually get a websockets disabled error which occurs whenever RPC is enabled and blocking by default. It doesn't appear that there is a way to override this. Not sure if this is actionable due to the nature of Websockets, but I thought that it was notable nonetheless.
Thanks

**Comment by Radagast** [comment]
Have you seen [RequestPolicyContinued#427](https://github.com/RequestPolicyContinued/requestpolicy/issues/427)

**Comment by chinaar** [comment]
@Radagast yeah that appears to be the issue I am having. Thanks for the link, the workaround is working for me.
