### ISSUE TITLE
Make the RP menu keyboard shortcut configurable

### ISSUE THREAD

**Issue by nodiscc** [RequestPolicyContinued/requestpolicy#616]
Either through the prefs GUI, or from an about:config setting.
It would slove https://github.com/RequestPolicyContinued/requestpolicy/issues/612 and future hotkey conflict problems

**Comment by myrdd** [comment]
With the [`sdk/hotkeys`](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/hotkeys) high-level API it should be quite easy to make it user-configurable.

**Comment by myrdd** [comment]
The next version will bring these new preferences:

`extensions.requestpolicy.keyboardShortcuts.openMenu.enabled`
`extensions.requestpolicy.keyboardShortcuts.openMenu.combo`

Documentation is at https://github.com/RequestPolicyContinued/requestpolicy/wiki/Development-Basics#keyboard-shortcuts

**Comment by nodiscc** [comment]
https://github.com/RequestPolicyContinued/requestpolicy/wiki/FAQ#how-do-i-change-the-keyboard-shortcut-to-open-the-menu

**Comment by myrdd** [comment]
Thank you nodiscc! You're right, the FAQ is the better place for the documentation. BTW is there a reason why we put the list of preferences to "Development Basics"?

**Comment by nodiscc** [comment]
> BTW is there a reason why we put the list of preferences to "Development Basics"?

No, it was just stuffed there at the time. I believe should rather be in the end-user documentation (that would be the FAQ page, I guess).

**Comment by myrdd** [comment]
> No, it was just stuffed there at the time. I believe should rather be in the end-user documentation (that would be the FAQ page, I guess).

Okay, I've moved the list to the FAQ. https://github.com/RequestPolicyContinued/requestpolicy/wiki/FAQ#what-are-requestpolicys-configuration-settings-on-aboutconfig
