### ISSUE TITLE
Provide build instructions

### ISSUE THREAD

**Issue by nysatrok** [RequestPolicyContinued/requestpolicy#618]
I'd appreciate some information about the build dependencies. When I try to compile RP, I get this error:

    preprocess src/content/lib/utils/strings.jsm > build/normal/content/lib/utils/strings.jsm
    /bin/sh: preprocess: command not found
    Makefile:253: recipe for target 'build/normal/content/lib/utils/strings.jsm' failed
    make: *** [build/normal/content/lib/utils/strings.jsm] Error 127

**Comment by myrdd** [comment]
Sorry it's not documented yet. You need `npm` and its [`preprocessor`](https://www.npmjs.com/package/preprocessor) package. So for a debian system:
```bash
sudo apt-get install npm
sudo npm install -g preprocessor
```
Tell me if that solved your problem and I'll update documentation.

**Comment by nysatrok** [comment]
It works now. Thanks!
