### ISSUE TITLE
1.0.beta9 html5 playback broken

### ISSUE THREAD

**Issue by riesza** [RequestPolicyContinued/requestpolicy#626]
![2015-04-29_23-41-27](https://cloud.githubusercontent.com/assets/1399263/7402159/04cc003a-eeca-11e4-8d0b-283f393a1750.png)

Latest Nightly. This appears now. Disabling blocking helps, as well as disabling the addon altogether (obviously).

From the log: 
![2015-04-29_23-52-31](https://cloud.githubusercontent.com/assets/1399263/7402289/e9d9f164-eeca-11e4-81f3-28712caa3311.png)

**Comment by myrdd** [comment]
You can work around this problem by manually adding a rule from  host `*.youtube.com` to destinations with scheme `mediasource`. The main issue for this problem is to be discussed in #625.

**Comment by riesza** [comment]
Thank you, that workaround helped.

**Comment by myrdd** [comment]
Good, so the workaround works. However, I think I will change the code so that `mediasource` will be treated like `view-source` until #625 is fixed. So I reopen this issue, and I set a milestone.

**Comment by myrdd** [comment]
I've just figured out that the URI `mediasource:https://www.youtube.com/.....` is *not* a nested URI, so we have to live with the workaround above until #619 is fixed. Closing this issue again.

**Comment by netjeff** [comment]
Here's a screenshot that shows how to create the workaround rule discussed above:

![screenshot](https://cloud.githubusercontent.com/assets/3266932/8681990/da0ff27c-2a27-11e5-92a1-8141a7cf4afd.jpg)

**Comment by myrdd** [comment]
Thanks for that screenshot @netjeff. I've referenced your screenshot in the first post of this issue.
