### ISSUE TITLE
1.0.beta9 seems to be blocking keefox...

### ISSUE THREAD

**Issue by Radagast** [RequestPolicyContinued/requestpolicy#627]
When using 1.0.beta8 I had a rule for keefox based on the information from https://github.com/RequestPolicyContinued/requestpolicy/issues/427, however, the update to 1.0.beta9 seems to have broken this.

In the request log I see:

resource://gre-resources/hiddenWindow.html - ws://127.0.0.1:12546/

As blocked.

**Comment by innologi** [comment]
I can confirm the issue, updating from the previous beta release to 1.0.beta9, regardless of having a previously working rule.

**Comment by myrdd** [comment]
So you have a rule as described in https://github.com/RequestPolicyContinued/requestpolicy/issues/427#issuecomment-69008797? Is there maybe something logged to the Browser Console?

**Comment by innologi** [comment]
This is all I have:
![requestpolicy-keefox](https://cloud.githubusercontent.com/assets/3001833/7410568/5a89c690-ef30-11e4-8962-9a2e236d5d5b.png)

**Comment by myrdd** [comment]
Thank you @innologi; I've just figured out that I can reproduce the problem, and I'm currently debugging it.

**Comment by myrdd** [comment]
I've localized the source of the problem. You can expect a hotfix release in the next few hours.
Thanks for reporting this bug so quickly.

**Comment by innologi** [comment]
@myrdd Thank *you* for your quick response!

**Comment by myrdd** [comment]
The new release is out. The update should work without a restart.

**Comment by innologi** [comment]
After the (restartless) update, KeeFox immediately connected. Thanks again!

**Comment by myrdd** [comment]
great! :)

**Comment by Radagast** [comment]
Thank you for the quick fix :)
