### ISSUE TITLE
latest beta got worse

### ISSUE THREAD

**Issue by chrcoluk** [RequestPolicyContinued/requestpolicy#629]
Some bad issues with latest version.

So is a site I use which has a deny rule for a domain it links to.

Previously before I updated a few days ago it blocked as expected without any alerts.

Now every time I load the page I get a message at the top of the page asking me if I want to deny, allow or make a rule for something I already have a deny rule for.  If I choose to make a rule the only options are to add an allow rule not a deny rule.

Whats going on?

**Comment by myrdd** [comment]
> Now every time I load the page I get a message at the top of the page asking me if I want to deny, allow or make a rule for something I already have a deny rule for.

I think I know what you mean: a page contains some element, e.g. an image, and its location *redirects* to another location.

There is already an issue about that: #561. However, I can see that the notification bar *always* shows up, so I created issue #630.

> If I choose to make a rule the only options are to add an allow rule not a deny rule.

That's true. But if #561 is fixed, it's not necessary anymore to have entries for adding a "deny" rule.

--------------

So please watch #561 and #630 – I'm closing this issue, discussion goes on in the two other issues. Until they are fixed, you can simply ignore that notification bar in such cases. Thanks for your report, sorry for the confusion.
