### ISSUE TITLE
Redirect notification bar shows up even if there is a blocking rule

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/requestpolicy#630]
**Steps to reproduce:**
Go on a page that has an „inline redirect“, e.g. an image whose URL redirects to another URL.
Then a redirect notification bar shows up; this should not happen, but there's issue #561 for it.
However, for *this* issue, add a "deny" rule for that particular request and reload.

**Actual result:**
Even if there is a "deny" rule, the notification bar shows up.

**Expected result:**
The notification bar for „inline redirects“ should be hidden in case a "deny" rule exists.

----------------

If #561 would be fixed, this issue would be fixed as well.

Edit: @chrcoluk has found this bug; see #629.

**Comment by Whissi** [comment]
I guess I am experiencing the same bug: I am noticing that many sites are now trying to redirect `www.google-analytics.com` to `stats.g.doubleclick.net`. I don't think that so many sites have turned on Google's retargeting feature at the same time...

Also, I have a blocking rule so I shouldn't see such requests, but it seems like this is not working (as expected):

![rp_rule](https://cloud.githubusercontent.com/assets/729436/7443057/cfa1be22-f130-11e4-952c-7dc409e9b2cf.jpg)

and the redirect prompt

![rp_redirect](https://cloud.githubusercontent.com/assets/729436/7443058/de546c8a-f130-11e4-89c2-79d76d91bd58.jpg)

Not the same bug? Should I create a new issue for that problem?

**Comment by myrdd** [comment]
@Whissi it's exactly this bug.
