### ISSUE TITLE
1.0.beta9 seems to be blocking Youtube HTML5 playback.

### ISSUE THREAD

**Issue by Radagast** [RequestPolicyContinued/requestpolicy#631]

**Comment by Radagast** [comment]
For some reason 1.0.beta9 seems to be preventing firefox from using HTML5 on Youtube. I have the same rule set I was using with the prior release of RPC which worked. If I disable blocking HTML5 works. What I see in RPC is a single destination called 'null' and I can't seem to do anything with it. 

! [image](http://i.imgur.com/CakEBmL.jpg)

**Comment by myrdd** [comment]
See #626.
