### ISSUE TITLE
Unblocked cross-site request on bbc.com?

### ISSUE THREAD

**Issue by michaelweiner** [RequestPolicyContinued/requestpolicy#632]
When visiting bbc.com for the first time (i.e. when having no cookies from bbc.com, bbc.co.uk, 2o7.net), there is one request to 2o7.net. According to the history, it is from

https://bbc.112.2o7.net/b/ss/bbcwglobalprod/1/H.22.1/s8795093672597?AQB=1&bw=1920&bh=625&c=24&cc=USD&cdp=2&ce=UTF-8&ndh=1&s=1920x625&events=event2&t=1%2F5%2F2015%2017%3A6%3A55%205%20-120&g=http%3A%2F%2Fwww.bbc.com%2F&r=&pageName=bbc%20-%20homepage&k=N&v=Y&v31=desktop&v55=bbc.com&v57=yes&v5=INDEX&v6=homepage&v7=homepage&v8=homepage&v3=na&v10=na&v32=not%20available&AQE=1

to

https://bbc.112.2o7.net/b/ss/bbcwglobalprod/1/H.22.1/s8795093672597?AQB=1&pccr=true&&bw=1920&bh=625&c=24&cc=USD&cdp=2&ce=UTF-8&ndh=1&s=1920x625&events=event2&t=1%2F5%2F2015%2017%3A6%3A55%205%20-120&g=http%3A%2F%2Fwww.bbc.com%2F&r=&pageName=bbc%20-%20homepage&k=N&v=Y&v31=desktop&v55=bbc.com&v57=yes&v5=INDEX&v6=homepage&v7=homepage&v8=homepage&v3=na&v10=na&v32=not%20available&AQE=1

Surprisingly, I did not find any request from BBC domains to 2o7.net .

This only happens if no cookies from BBC/2o7 are set.

My default policy is deny, and I am using the community rules, which allow, for example, requests to bbci.co.uk: I can find such a rule in the ruleset, but I could not find any rule matching 2o7.net.

Versions:
 - RequestPolicy 1.0.beta9.1
 - Firefox 37.0.2

Why is the request to 2o7.net not blocked? How can a request from 2o7.net appear as a source without having any request from bbc to 2o7 first?

Thanks for your help!

**Comment by myrdd** [comment]
Hi @michaelweiner. First of all, please tell me if I understand you correctly:

 - You've got RPC's *request log* opened.
 - It shows a request from `bbc.112.2o7.net` to `bbc.112.2o7.net`.
 - There's no request from `bbc.com` to `*.2o7.net`.

If this is the case for you, I cannot reproduce that. I don't see any request from/to `*.2o7.net`.
By the way, I've opened the [Network Monitor](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor) as well, and it doesn't show `*.2o7.net` either.
Might it be possible that a page in another tab creates that request? Please test it again with only one tab opened.

> How can a request from 2o7.net appear as a source without having any request from bbc to 2o7 first?

Correct, there has to be a request to `2o7.net` *before* `2o7.net` can be the origin of another (subsequent) request.

**Comment by michaelweiner** [comment]
Yes, you all three items correctly.

I reproduced it now, with only one tab open. Both RPC and Network Monitor show the request; I'll attach a screenshot.

## How I reproduced this behavior
 1. Open up empty tab
 2. Close all other tabs
 3. Clear all cookies
 4. Open the RPC request log and the Network Monitor
 5. go to www.bbc.com

## Notes
### 1 and 2
I figured out that when clearing cookies while having bbc.com open, at least one cookie is continuously set; therefore, at least it seems mandatory not to be on bbc.com while clearing cookes, so I wanted to have my test setup as clean as possible.

### 3
I only see the request to 2o7.net if no cookies are set from 2o7.net and bbc.co.uk and bbc.com. I have not tested what happens when only some of the three are there. Again, to have the cleanest starting point possible, I cleared all cookies for that test.

### 5
as a double-check, the described behavior occurs only if the BBC web page shows the cookie message.

![rpc_2o7](https://cloud.githubusercontent.com/assets/2922189/7483116/a744b332-f37c-11e4-96d3-20432b4af11c.png)

**Comment by michaelweiner** [comment]
Now I went through all my plugins, and found out that the request to 2o7.net does not happen when HTTPS Everywhere is disabled. Therefore, I assume this issue is not related to RPC. Thank you for your help and effort to reproduce this behavior.

**Comment by myrdd** [comment]
Alright @michaelweiner that was a really nice description :)

Btw I also wondered why your network monitor shows only eight requests. In my case – having the same configuration like you – it shows 71 requests.
