### ISSUE TITLE
Icon disappeared

### ISSUE THREAD

**Issue by SkySkimmer** [RequestPolicyContinued/requestpolicy#634]
The toolbar icon just disappeared.
On 1.0.beta9.2

EDIT: now it's back.

**Comment by myrdd** [comment]
You mean the icon has disappeared in browser windows which had been already open before you did the upgrade?
I've never seen the icon being disappeared; maybe you have some more information, e.g. some error in the Browser Console?
If you can't figure out more information, please close this issue.
