### ISSUE TITLE
Requests using HTML5 Media Source Extensions (i.e. Youtube) not handled correctly

### ISSUE THREAD

**Issue by flussence** [RequestPolicyContinued/requestpolicy#640]
With MSE enabled (on bydefault for YT since Fx36, I believe), I see requests in the log to URLs like `mediasource:https://www.youtube.com[...]`.

In the RP menu and the policy list they show up as the name "null" with no protocol/port. The only way I can seem to get media to play is by whitelisting the entire originating domain. Whitelisting anything to "null" has no effect.

**Comment by nodiscc** [comment]
Hi @flussence please check https://github.com/RequestPolicyContinued/requestpolicy/issues/626 and https://github.com/RequestPolicyContinued/requestpolicy/issues/619.

> You can work around this problem by manually adding a rule from  host `*.youtube.com` to destinations with scheme `mediasource`.
