### ISSUE TITLE
Documentation/Interface: make priorities more clear, i.e. subscription vs. custom/preset rules

### ISSUE THREAD

**Issue by Korodny** [RequestPolicyContinued/requestpolicy#645]
I like the subscription idea (that is new in RPC, right? can't remember that from RP), but the interface needs to make it more clear what the priorities are: if a subscription rule clashes with a custom one, who wins?

**Comment by acrobat1** [comment]
I asked the same question not long ago, the short answer should be that custom rules always override subscription rules.

see: https://github.com/RequestPolicyContinued/requestpolicy/issues/614#issuecomment-90469216

**Comment by myrdd** [comment]
Yes, user rules always have precedence over subscription rules.

I agree that this should be documented. I suggest to change the text on the "Subscriptions" page in the settings. The current text is:

>  Subscription policies are preset rules maintained by the community. These rules are updated automatically and can fulfil different needs, such as blocking known web browsing tracking sites, or allowing requests to allow certain sites to display/work properly. [Learn more about subscriptions.](https://github.com/RequestPolicyContinued/subscriptions/)

My proposal is to add a sentence like *„In case there is a user rule that conflicts with a subscription rule, the user rule always wins.“* Do you think that is appropriate?

**Comment by nodiscc** [comment]
> In case there is a user rule that conflicts with a subscription rule, the user rule always wins

I've added this sentence to the documentation on subscriptions. It will be live when I push the new wiki/website next week.

@Korodny @myrdd Feel free to close this issue if this solution fits your needs.

**Comment by Korodny** [comment]
Yeah, sounds good to me - thanks.

**Comment by myrdd** [comment]
Thanks for that @nodiscc. But don't you think the text on `about:requestpolicy?subscriptions` should be updated as well?

**Comment by Korodny** [comment]
Ah, I'm sorry - misread nodisc's statement when closing the issue. ITA, adding a hint to the interface certainly wouldn't hurt, IMHO.

**Comment by nodiscc** [comment]
Ok well I misread the issue. A hint on the settings page would be welcome.

**Comment by myrdd** [comment]
Ok then. My proposal is below, the new sentence is bold.

Is there any native english speaker who could check the wording/phrasing? I'd appreciate that!

> Subscription policies are preset rules maintained by the community. These rules are updated automatically and can fulfil different needs, such as blocking known web browsing tracking sites, or allowing requests to allow certain sites to display/work properly. **Any subscription rule can be overridden by user rules, that is, user rules in general have higher precedence.**  [Learn more about subscriptions.](https://github.com/RequestPolicyContinued/subscriptions/)

My previous proposal was: *„In case there is a user rule that conflicts with a subscription rule, the user rule always wins.“*

**Comment by acrobat1** [comment]
I would just write:  *"User rules by default override subscription rules"* -but that's maybe a tad too cryptic.

**Comment by nodiscc** [comment]
_When a subscription rule and an user-defined rule conflict, only the user-defined rule is applied_

**Comment by Korodny** [comment]
*subscription rules act as a supplement to user defined rules: if no user defined rule applies, *

**Comment by myrdd** [comment]
I stumbled opon this issue and saw it's not resolved yet. I suggest to use Korodny's suggestion. The full description on the "Subscriptions" settings page will be:

> Subscription policies are preset rules maintained by the community. These rules are updated automatically and can fulfil different needs, such as blocking known web browsing tracking sites, or allowing requests to allow certain sites to display/work properly. Subscription rules act as a supplement to user defined rules, that is, if no user defined rule applies, RequestPolicy will check if a subscription rule does. [Learn more about subscriptions.](https://github.com/RequestPolicyContinued/subscriptions/)

**Comment by myrdd** [comment]
@beriain @ma2moto @matreex The translations of `subscriptionPoliciesDefinition` will be reset to the new english version. It would be nice if you could translate it again. Just post the new string in this issue.

Below you can find the old strings. You probably can reuse them.

---

Previously the english string was:

> Subscription policies are preset rules maintained by the community. These rules are updated automatically and can fulfil different needs, such as blocking known web browsing tracking sites, or allowing requests to allow certain sites to display/work properly.

Now the enlish string is:  (only one sentence was added, marked in bold)

> Subscription policies are preset rules maintained by the community. These rules are updated automatically and can fulfil different needs, such as blocking known web browsing tracking sites, or allowing requests to allow certain sites to display/work properly. __Subscription rules act as a supplement to user defined rules, that is, if no user defined rule applies, RequestPolicy will check if a subscription rule does.__

---

The old __basque__ translation:

> Harpidetza politikak komunitateak mantendutako aurre-ezarritako arauak dira. Arau hauek automatikoki eguneratzen dira eta behar ezberdinak bete ditzakete, nabigazio jarraipena egiten duten gune ezagunak blokeatu, edo gune ezagunak zuzen ikusi/funtziona dezaten eskaerak baimentzea bezala.

---

The old  __japanese__ translation:

> サブスクリプション ポリシーとはコミュニティからの助けを借りて私達が保持しているルール セットです。ルール セットはあなたのプライバシーに影響を与えるリクエストを禁止しつつ Web サイトの表示のくずれを最小限に抑えることを目的としており、ルールは自動的に更新されます。

---

The old __simplified chinese__ translation:

> 订阅策略预设规则由社区来维护。这些规则是自动更新的，能满足不同的需求，比如阻止众所周知的网络追踪站点，或着允许请求某些站点的显示与正常工作。

**Comment by beriain** [comment]
Hi! thank you for pinging, here is the basque translation for the full string:

Harpidetza politikak komunitateak mantendutako aurre-ezarritako arauak dira. Arau hauek automatikoki eguneratzen dira eta behar ezberdinak bete ditzakete, nabigazio jarraipena egiten duten gune ezagunak blokeatu, edo gune ezagunak zuzen ikusi/funtziona dezaten eskaerak baimentzea bezala. **Harpidetza arauak erabiltzaileak zehaztutako arauen gehigarri gisa lan egiten dute dute, hau da, erabiltzaileak zehaztutako araurik ez balego, RequestPolicy harpidetza arauren bat bilatuko du.**
