### ISSUE TITLE
RequestPolicy incompatible with Firefox 38.0.

### ISSUE THREAD

**Issue by ericoporto** [RequestPolicyContinued/requestpolicy#646]
I have RequestPolicy 0.5.28 Add-on installed on Firefox, but my firefox updated to 38.0 and now exhibits a message saying: " RequestPolicy is incompatible with Firefox 38.0. " I use Ubuntu Linux 14.04.

**Comment by nodiscc** [comment]
Hi @ericoporto the legacy RequestPolicy addon is incompatible with Firefox 38+. The RequestPolicyContinued project is a continuation of the 1.x branch and will stay compatible with future versions. Check https://requestpolicycontinued.github.io/ and feel free to install it and give some feedback. There are some compatibility issues with the 0.5 branch (your old rules may not be imported)

**Comment by ericoporto** [comment]
Thank you! I didn't know the one installed in this computer was still the legacy! Good to know! Just installed the new one and it appears to be working flawlessly. Good work!

**Comment by baptx** [comment]
@ericoporto if RequestPolicy 0.5.x rules where not imported, see https://github.com/RequestPolicyContinued/requestpolicy/issues/354#issuecomment-102092303

**Comment by nodiscc** [comment]
I'm glad you find it useful. I'm closing this issue and will redirect future duplicate questions here.
