### ISSUE TITLE
Right click menu

### ISSUE THREAD

**Issue by doublezeta** [RequestPolicyContinued/requestpolicy#653]
I hide my toolbar, including the "File Edit View" menu. The old RequestPolicy had a context menu option to Allow or Deny third-party referrers. Please add this to the add-on, so users don't need a toolbar icon to change their settings.

**Comment by nodiscc** [comment]
Hi @doublezeta this is a duplicate of https://github.com/RequestPolicyContinued/requestpolicy/issues/353. Please follow this issue instead.
