### ISSUE TITLE
Add ability to override auto-reload upon change to whitelist

### ISSUE THREAD

**Issue by jdgalt** [RequestPolicyContinued/requestpolicy#656]
Where a web page references some currently-blocked outside site, I want to be allowed to enable that reference without causing a reload.  This is important on sites like e-rewards.com where reloading a page causes what you were doing to be irreversibly lost.

**Comment by nodiscc** [comment]
@jdgalt you can disable autoreload on the preferences pages ` about:requestpolicy?basicprefs`. Does it solve your problem?

**Comment by jdgalt** [comment]
It's a decent workaround, but I'd like to be able to do it on the fly.

**Comment by nodiscc** [comment]
> ut I'd like to be able to do it on the fly.

How can it be done? A checkbox _disable auto-reload_ in the menu?

**Comment by klemens** [comment]
> How can it be done?

Because the reload happens when the menu is closed, a button "Close without reload" would be enough.

**Comment by myrdd** [comment]
> a button "Close without reload" would be enough.

I doubt many people would use that button, but think some people will like it. Still, I wouldn't put that button in the menu by default. See  #601 for a summary of proposed menu UI changes.

If RPC one day has the feature of customizing the menu, the "close without reload" button can definitely be part of it.

**Comment by nodiscc** [comment]
There is another workaround for this: open the menu, click the rule you'd like to modify (eg `block all requests to *.crap-ad-site.com`), then click the `Preferences` menu item. Your rule will register but the page won't reload. <sup>100% not a hack</sup>

> Still, I wouldn't put that button in the menu by default

Yes there's a risk of menu "bloat" (though this feature is useful), although most new switches/buttons could be made simple icons (no text, but with a tooltip), which would save space. Kinda like a toolbar inside the menu (would also work with the `get more info about $domain` button).

**Comment by myrdd** [comment]
Another idea: closing the menu via clicking on the flag could mean "close without reload". What do you think? Would this work for you @jdgalt and @klemens?

Besides that, would you like a

> although most new switches/buttons could be made simple icons (no text, but with a tooltip), which would save space

I agree. So there could be a simple icon for switching "auto-reload" on/off.

**Comment by jdgalt** [comment]
I'll try it nodiscc's way.  Thanks!
