### ISSUE TITLE
Mark temporary permitted destination appear yellow

### ISSUE THREAD

**Issue by sataevr** [RequestPolicyContinued/requestpolicy#670]
![Example](https://pp.vk.me/c625822/v625822891/34340/YjpblkvTkGc.jpg)

**Comment by ivan-kolmychek** [comment]
:+1: for this issue, that would be really nice.

Also, we can put them to separate group "Temporary allowed destinations".

**Comment by jdgalt** [comment]
I vote for the second method.  Or you could show the "temporarily allowed" site in italics, the way NoScript does.

**Comment by nodiscc** [comment]
There was another suggestion, which was to add a timer icon next to temp. rules, see https://github.com/RequestPolicyContinued/requestpolicy/issues/601 and https://github.com/RequestPolicyContinued/requestpolicy/issues/167

**Comment by myrdd** [comment]
> see #601

To have it here visually:

![timer-icon](https://cloud.githubusercontent.com/assets/4286829/8194970/76fc8442-147f-11e5-85e3-e289fb072e91.png)

---

I think a yellow icon is a bad idea. Two reasons:

 * Temporary *deny* rules may exist. Should the blocking icon be yellow? I wouldn't like that.
 * The color „yellow“ is already used for the „disabled“ flag: ![disabled-flag](https://raw.githubusercontent.com/RequestPolicyContinued/requestpolicy/v1.0.beta9.3/src/skin/requestpolicy-icon-disabled.png). I'd prefer not to use „yellow“ anywhere else.

Personally I like the timer icon most.

---

When you have more ideas: Be aware of the three cases:

 1. Only permanent rules have applied.
 2. Only temporary rules have applied.
 3. Both permanent and temporary rules have applied.

In case of the „timer“, we also need an icon for the third case. Maybe a clock that is only partly visible?

**Comment by nodiscc** [comment]
Closing in favor of #167. Feel free to comment there if the proposed solution doesn't suit you.
