### ISSUE TITLE
allow to free memory

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/requestpolicy#673]
Some users have memory problems with RequestPolicy, see #588. To free the memory they currently need to restart the browser. Decreasing memory usage is the aim of #588. Until this is achieved, I propose the following:

 * create a page with URL `about:requestpolicy?experimental`, which will be used for *this* and future experiments
 * that page will show some numbers indicating memory usage, e.g. how many request objects exist
 * that page will allow to free memory

*Freeing memory* will mean to remove all information about past requests. It will reset `RequestSet`s, `_clickedLinks` etc. – see also [`performance`](https://github.com/RequestPolicyContinued/requestpolicy/labels/performance)-related issues.

**Comment by sander85** [comment]
Following.. :)
