### ISSUE TITLE
About translate to simplified chinese

### ISSUE THREAD

**Issue by ghost** [RequestPolicyContinued/requestpolicy#677]
I found in "/locale/zh-CN/requestpolicy.properties" that
{
subscriptionPolicies=Subscription Policies
subscriptionPoliciesDefinition=Subscription policies are preset rules maintained by the community. These rules are updated automatically and can fulfil different needs, such as blocking known web browsing tracking sites, or allowing requests to allow certain sites to display/work properly.

learnMoreAboutSubscriptions=Learn more about subscriptions.
and
dontIndicateBlacklisted=Exception: images blocked by a blacklist
}
havn't still been translated to chinese, so... I would have translated it to simplified chinese.
dontIndicateBlacklisted=例外：黑名单中的图像不显示被阻止标识
subscriptionPoliciesDefinition=订阅策略预设规则由社区来维护。这些规则是自动更新的，能满足不同的需求，比如阻止众所周知的网络追踪站点，或着允许请求某些站点的显示与正常工作。
learnMoreAboutSubscriptions=了解更多的订阅策略

If like this, please will they add to "/locale/zh-CN/requestpolicy.properties", thanks.

**Comment by myrdd** [comment]
Thank you @Matreex, I will take the changes into the next release, beta10, which will be released within the next ~8 days.

**Comment by Matreex** [comment]
No thanks, @myrdd, I like requestpolicy, and particular anti redirect. :+1:

**Comment by matreex** [comment]
Oh, sorry, and this:
redirectNotificationWithOrigin=The URL %1$S has asked to redirect to %2$S
redirectNotificationWithOrigin=链接 %1$S 已被重定向到 %2$S
Please add it, so thanks.

**Comment by matreex** [comment]
I replace the "requestpolicy.properties" to "requestpolicy-1-0-beta9-3.xpi", but firefox points: "This add-on could not be installed because it appears to be corrupt", excuse me, @myrdd, can u tell me why?

**Comment by myrdd** [comment]
@matreex I'll add that, too.
If installation does not work, maybe the `requestpolicy.properties` you've added to the xpi file is erroneous. If you paste it here, I could check. Nevertheless, I guess I'll release beta10 later today, so your changes will be included.

**Comment by matreex** [comment]
extensions.requestpolicy@requestpolicy.com.description=控制允许哪些跨站点的请求。改进您浏览时的隐私保护。确保自己不被跨站点请求伪造（CSRF）攻击和其他攻击。
extensionConflictWarning=冲突的扩展：%S
noOrigin=[无源]
allowOrigin=允许从 %S 的请求
allowDestination=允许到 %S 的请求
allowOriginToDestination=允许从 %1$S 到 %2$S 的请求
allowOriginTemporarily=临时允许从 %S 的请求
allowDestinationTemporarily=临时允许到 %S 的请求
allowOriginToDestinationTemporarily=临时允许从 %1$S 到 %2$S 的请求
stopAllowingOrigin=停止允许从 %S 的请求
stopAllowingDestination=停止允许到 %S 的请求
stopAllowingOriginToDestination=停止允许从 %1$S 到 %2$S 的请求
denyOrigin=阻止所有从 %S 的请求
denyDestination=阻止所有到 %S 的请求
denyOriginToDestination=阻止从 %1$S 到 %2$S 的请求
denyOriginTemporarily=临时阻止所有从 %S 的请求
denyDestinationTemporarily=临时阻止所有到 %S 的请求
denyOriginToDestinationTemporarily=临时阻止从 %1$S 到 %2$S 的请求
stopDenyingOrigin=停止阻止所有从 %S 的请求
stopDenyingDestination=停止阻止所有到 %S 的请求
stopDenyingOriginToDestination=停止阻止从 %1$S 到 %2$S 的请求
unrestrictedOrigin=不能阻止从 %S 的请求
redirectNotification=此网页要求重定向到 %S
redirectNotificationWithOrigin=链接 %1$S 已被重定向到 %2$S
allow=允许
allow.accesskey=A
deny=拒绝
deny.accesskey=D
more=更多...
more.accesskey=M
indentedText=%1$S %2$S
requestLogIsEmpty=请求日志是空的。
requestLogDirections=当您访问网页时，这里将出现日志条目。
actionForbidden=禁止动作
urlCanOnlyBeCopiedToClipboard=此网址只能被复制到剪贴板。
preferences=设置
managePolicies=管理策略
about=关于
help=帮助
basic=基础
advanced=高级
indicateBlockedImages=标示已阻止的图像
dontIndicateBlacklisted=例外：黑名单中的图像不显示被阻止标识
autoReload=白名单更改后重新载入当前页面
webPages=网页
menu=菜单
allowAddingNonTemporaryRulesInPBM=允许在使用隐私浏览模式时添加永久性白名单
advancedPreferences=高级设置
linkPrefetching=链接预取
dnsPrefetching=DNS 预取
enabled=启用
disableOnStartup=在启动时禁用
restoreDefaultOnUninstall=RequestPolicy 卸载时恢复默认
menuPreferences=菜单设置
menuSorting=目标排序
sortByNumRequests=依照请求数量
sortByDestName=仅依照域名
noSorting=不排序
hint=提示：
menuSortingHint=在禁用排序的情况下，域列表的顺序是依照网站请求的顺序。这通常有助于在默认拒绝模式下寻找必须允许的请求，网站先发出的请求更可能是必不可少的。
menuIndicatedInformation=指示信息
menuIndicateNumRequests=显示每个目标的请求数量
yourPolicy=您的策略
defaultPolicy=默认策略
subscriptions=订阅
search=搜索
scheme=模式
host=主机
port=端口
type=类型
origin=来源
destination=目标
block=阻止
temporary=临时
addRule=添加规则
addRule.accesskey=R
learnMoreAboutRules=了解更多规则
learnMore=了解更多。
defaultPolicyDefinition=在您没有为匹配请求设置“允许”或者“阻止”规则时，这将是 RequestPolicy 的默认行为。
allowRequestsByDefault=默认允许请求。
blockRequestsByDefault=默认阻止请求。（仅限高级用户。会导致很多网站出现问题。）
allowRequestsToTheSameDomain=允许同一域的请求（www.example.com -> static.example.com）。
differentSubscriptionsAreAvailable=更改您的默认规则即改变订阅规则。
manageSubscriptions=管理订阅。
subscriptionPolicies=订阅策略
subscriptionPoliciesDefinition=订阅策略预设规则由社区来维护。这些规则是自动更新的，能满足不同的需求，比如阻止众所周知的网络追踪站点，或着允许请求某些站点的显示与正常工作。
learnMoreAboutSubscriptions=学习更多的订阅策略
privacy=隐私
usability=可用性
browser=浏览器
subscriptionDenyTrackersDescription=阻止目标跟踪你的网上活动
subscriptionAllowSameOrgDescription=允许与网页来源同属一个组织的目标
subscriptionAllowFunctionalityDescription=允许网站正常工作所必需的请求
subscriptionAllowEmbeddedDescription=允许嵌入的图像、视频等内容的请求
subscriptionAllowMozillaDescription=允许有关 Mozilla 和 Firefox 的请求
subscriptionAllowExtensionsDescription=允许其他扩展正常工作所必需的请求
welcomeToRequestPolicy=欢迎使用 RequestPolicy
forMostUsersDefaultsAreIdeal=大多数人应该使用 RequestPolicy 的默认规则
youCanConfigureRequestPolicyToBeMoreStrict=但是，您也可以配置 RequestPolicy 使其更加严格（只建议高级用户使用）。
teachMeHowToUseRequestPolicy=教我如何使用 RequestPolicy
returnToBrowsing=返回浏览
configureRequestPolicy=配置 RequestPolicy
yesUseSubscriptions=是的，使用订阅策略。（推荐）
noDoNotUseSubscriptions=不，不使用订阅策略。
removeOldRules=删除旧版本 RequestPolicy 遗留的未使用规则。
importOldRules=导入旧规则
deleteOldRules=删除旧规则
showOldRuleReimportOptions=显示重新导入选项
yourOldRulesHaveBeenDeleted=您的旧规则已删除。
ruleSet=规则集
filterRules=过滤规则
policy=策略
rp.menu.revokeTemporaryPermissions=撤销所有临时允许
rp.menu.blockedDestinations=阻止目标
rp.menu.allowedDestinations=允许目标
rp.menu.mixedDestinations=混合目标
rp.menu.otherOrigins=其他来源
rp.menu.enableBlocking=启用阻止
rp.menu.disableBlocking=禁用阻止
rp.menu.help=帮助
rp.menu.preferences=设置
rp.menu.managePolicies=管理策略
rp.requestLog.title=请求日志
rp.requestLog.clear=清除

**Comment by matreex** [comment]
I use gedit to edit the requestpolicy.properties, so thanks for your help. :+1:

**Comment by matreex** [comment]
"Nevertheless, I guess I'll release beta10 later today, so your changes will be included."
That's great! :dancers:

**Comment by myrdd** [comment]
I can't reproduce your problem. If you want to debug, you could take a look at the browser console – https://developer.mozilla.org/en-US/docs/Tools/Browser_Console

**Comment by matreex** [comment]
I can't find it too, I don't know why, so... I will the requestpolicy.properties add to xpi, and rename to requestpolicy@requestpolicy.com, copy to extensions of firefox. :(
