### ISSUE TITLE
Can't whitelist data URIs

### ISSUE THREAD

**Issue by ashleyholman** [RequestPolicyContinued/requestpolicy#680]
Some sites have inline images that looks like "<img src="data:image/gif;base64;..."

Although the images don't load when RequestPolicy is enabled, there's no option to whitelist them.  I've tried to manually add a policy to allow the 'data' scheme but the images still don't load.  I can only load them when I temporarily allow all requests.

I would have thought that inline images should always show as they don't result in any cross-domain requests.

**Comment by myrdd** [comment]
> I would have thought that inline images should always show as they don't result in any cross-domain requests.

Yes, that should be the case. I suppose the actual URI of the image that got blocked is a "normal" http URL. Any blocked image is replaced by a `data` uri, see in the code [here](https://github.com/RequestPolicyContinued/requestpolicy/blob/v1.0.beta10/src/content/ui/frame.blocked-content.js#L27) and [here](https://github.com/RequestPolicyContinued/requestpolicy/blob/v1.0.beta10/src/content/ui/frame.blocked-content.js#L46).

When you hover the image, the actual `prePath` of the image's uri should be displayed. Does this solve your problem?

**Comment by ashleyholman** [comment]
Oh I see.  Yes that explains the issue I was having.  Thanks :)
