### ISSUE TITLE
Cannot install Request Policy Continued on Firefox 40 Beta

### ISSUE THREAD

**Issue by bz922x** [RequestPolicyContinued/requestpolicy#684]
When attempting to install Request Policy Continued on Firefox 40 Beta, the installation fails with "RequestPolicyConttinued could not be installed because Firefox cannot modify the needed file."

**Comment by nodiscc** [comment]
@bz922x I am still on 39.0 (40 not available for my distribution yet) so unfortunately I can't test this. Can you try the following https://requestpolicycontinued.github.io/FAQ.html#how-to-find-relevant-information-about-a-bug (particularly, create a new firefox profile and tell us if you're still able to reproduce the bug)

**Comment by bz922x** [comment]
False alarm. RPC installed without issue when I created a new, clean profile. I then tried opening up permissions on files (which did not work). Finally I clicked the "Refresh Firefox" button on about:support and reloaded all of my extensions. At no point was I able to identify what file "Firefox cannot modify", but I suppose that is a Firefox issue, not an RPC issue.

**Comment by nodiscc** [comment]
Thanks for reporting back.
