### ISSUE TITLE
Menu does not show reason for blocked "Options, Sync, Create Account"

### ISSUE THREAD

**Issue by netjeff** [RequestPolicyContinued/requestpolicy#687]
This is probably closely related to the #619 but the symptoms are slightly different, so I wanted to capture them.  Feel free to close this against #619.

I run with "block all requests by default".  I went to the Options "page", then chose "Sync".  When I click on "Create Account" I get a blank page.   The RP menu shows nothing at all.  The request log shows a blocked request from `about:accounts?action=signup&entrypoint=preferences` to `https://accounts.firefox.com/...`.   See screenshot.

I manually created a rule for origin scheme `about` and destination `accounts.firefox.com`, and things work fine now.  

In some ways this is similar to #619 where menu shows URI without host as "null".  I'm pretty sure that the origin `about:` URI is the source of the problem, but the menu does not even show "null".  If this is close enough to #619, feel free to close this one.

![screenshot](https://cloud.githubusercontent.com/assets/3266932/8712533/8e20a9c6-2b1a-11e5-99d3-f13b8ea1e3f1.jpg)

**Comment by myrdd** [comment]
This is indeed closely related to #619, but I'd keep it separated, as #619 is more urgent (IMHO). So #619 is about requests *to* URIs without host, this issue is about the *origin* URI. Thanks for the report @netjeff.

**Comment by Marc05** [comment]
![rpc_sync_bug](https://cloud.githubusercontent.com/assets/1699133/17537296/6166bcda-5e69-11e6-82e3-6dd05ea21320.png)

This is the same as #426 and is still a problem on Firefox 48.0

**Comment by myrdd** [comment]
This issue had in fact already been fixed by commit 9854d0a0db96a9787fd8b8377226f9d7f894acdf, but now has been reintroduced due to a new domain. Thanks @Marc05 for posting here, and for mentioning the duplicate. A compatibility rule from `https://accounts.firefox.com/` to `https://accounts.cdn.mozilla.net/` will be included in the next version.
