### ISSUE TITLE
Block https to http content

### ISSUE THREAD

**Issue by msxfm** [RequestPolicyContinued/requestpolicy#69]
<a href="https://github.com/jsamuel"><img src="https://avatars.githubusercontent.com/u/1240282?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jsamuel](https://github.com/jsamuel)**
_Thursday Dec 22, 2011 at 18:49 GMT_
_Originally opened as https://github.com/RequestPolicy/requestpolicy/issues/69_

----

    imported trac ticket
    created: 2010-01-19 05:51:06
    reporter: phq

Block http content from a https site.

This would hopefully take care of the annoying firefox warning about "some insecure content". So instead of loading the insecure content RequestPolicy would block it.

This filter would have to be applied to same domain requests.

**Comment by genodeftest** [comment]
I think using security.mixed_content.block_display_content and security.mixed_content.block_active_content properties (from about:config) should be preferred.

**Comment by nodiscc** [comment]
Yes [Mixed content blocking](https://blog.mozilla.org/tanvi/2013/04/10/mixed-content-blocking-enabled-in-firefox-23/) is enabled by default since Firefox 23. Thanks for reminding us!
