### ISSUE TITLE
Firefox 41 disables unsigned extensions/addons

### ISSUE THREAD

**Issue by IT-Sumpfling** [RequestPolicyContinued/requestpolicy#697]
Hi,
starting with FireFox Dev 41 (I got the update today) unsigned addons are disabled, so I think you should start working on signing it ;-)

As of Firefox 41, there is a setting in about:config (xpinstall.signatures.required) to allow for unsigned addons, but this will be removed in the next version (Firefox 42) according to:
https://wiki.mozilla.org/Addons/Extension_Signing

**Comment by myrdd** [comment]
Hi @IT-Sumpfling, yes, I'm working on it. #600. :) I need to change some code for the addon to be approved.
