### ISSUE TITLE
need to sign extension

### ISSUE THREAD

**Issue by danielmotaleite** [RequestPolicyContinued/requestpolicy#699]
Firefox 40+ require signed extensions to work, so RequestPolicyContinued need to submit the package to mozilla for review and ask for signing. As right now, nightly and aurora releases can not use this extension due the lack of signing

http://mzl.la/1J7Lcsp
https://developer.mozilla.org/en-US/Add-ons/Add-on_guidelines
https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews

So please issue a new release  and ask the signing

Thanks for help and for the extension!

**Comment by Cephel** [comment]
+1, signature is _required_ now.

**Comment by nodiscc** [comment]
Hi @danielmotaleite @Cephel this is tracket in issue https://github.com/RequestPolicyContinued/requestpolicy/issues/600
