### ISSUE TITLE
Dealing with external requests?

### ISSUE THREAD

**Issue by Radagast** [RequestPolicyContinued/requestpolicy#700]
Not sure is this is an issue really...

Is there a way to deal with external browser requests, other than creating individual rules for each request? Let me give an example.

I use an external RSS reader, which is set to open links in firefox. However, for each link selected I get a prompt from RPC asking to allow the origin and destination. using this method could, ultimately, lead to quite a few rules. I could choose to allow all requests from the origin but that seems a bit broad. Just wondering if there's a better way?

Here's an image showing the type of prompt I receive for links:

![Imgur](http://i.imgur.com/g8urYT7.jpg)

**Comment by myrdd** [comment]
Hi @Radagast, sorry for the late reply. Not sure what you actually mean by „external browser requests“. I guess you're talking about cross site redirections, that is, redirections from one domain to a different one, e.g. from `lxer.com` to `www.datamation.com`. Take a look at issues #173 and #299, I think they propose a solution for your problem.

**Comment by myrdd** [comment]
> I use an external RSS reader, which is set to open links in firefox

Oh I see. I doubt it's easy or even possible to detect if a new tab has been opened by an external program. Regarding the redirect in general, see the issues in my previous reply.

Closing as wontfix
