### ISSUE TITLE
_blank links don't work any more when RP is installed

### ISSUE THREAD

**Issue by mote0230** [RequestPolicyContinued/requestpolicy#702]
Since yesterday's build of firefox dev edition having requestpolicy installed breaks links that use target="_blank" from working. Nothing happens when clicked. Changing settings in request policy does not help, nor does clicking 'Disable all blocking'. Only disabling the extension works. 
Tested with old requestpolicy 1beta and requestpolicy continued 1.0beta10, on win8.1

**Comment by myrdd** [comment]
Hi @mote0230, I can't reproduce your issue. Could you please try again in a clean profile? See [_contributing_](https://github.com/RequestPolicyContinued/requestpolicy/wiki/Contributing#testing-reporting-bugs--requesting-new-features).

**Comment by myrdd** [comment]
please reopen the issue when you've got more information
