### ISSUE TITLE
wish: Add support for more web browsers

### ISSUE THREAD

**Issue by vv221** [RequestPolicyContinued/requestpolicy#703]
As of now RequestPolicy can be installed on Firefox only.
It is actually the only reason I keep using Firefox : I know of no other browser + extension that allow me to manage cross-domain requests via a whitelist.

It would be nice if this extension could be installed on other browsers, I’m thinking in particular about QupZilla:
http://www.qupzilla.com/

I’m not a coder, even if I know one of two tricks, but be assured that I will help for this to the best of my abilities.

**Comment by myrdd** [comment]
I didn't know QupZilla yet, sounds like a nice project. However, it's not possible to support QupZilla and Firefox with the same code. QupZilla is written completely in C++, RP's code is JavaScript. This means that if you want RP in QupZilla you'd need to rewrite it from scratch. I won't do that. I'll focus RP development on Mozilla-based browsers, i.e. Firefox or SeaMonkey.

**Comment by vv221** [comment]
I wasn’t aware that the differences in languages would be a blocker, looks like I’ll have to find the time to port your plug-in to QupZilla myself. It won’t be done soon, but when I have something usable I’ll make sure to give you a heads up.

At least I gave you the opportunity to learn about QupZilla, so the signal-to-noise ratio of this issue is not that bad ;)

**Comment by myrdd** [comment]
Cool. Yes, please let me know when you've got a dev channel or a alpha/beta version. In case you've got questions about RP's code I'd be glad to help.

> At least I gave you the opportunity to learn about QupZilla, so the signal-to-noise ratio of this issue is not that bad ;)

Haha, nice one.
