### ISSUE TITLE
Bring back the ability to see requests recently blocked by the add-on

### ISSUE THREAD

**Issue by jdgalt** [RequestPolicyContinued/requestpolicy#706]
... so that I can set rules for them.  This is especially important when RP is preventing the use of other add-ons.

**Comment by myrdd** [comment]
Hi @jdgalt, are you talking about the Request Log? It's still there. You need to open it and reload the page – see also feature request #163.

**Comment by nodiscc** [comment]
@jdgalt can you confirm?

**Comment by jdgalt** [comment]
I've just been all through NoScript's options menus, and I can't find a way to turn on a Request Log.

**Comment by nodiscc** [comment]
@jdgalt This is about RequestPolicy

**Comment by jdgalt** [comment]
That's what I meant.

**Comment by nodiscc** [comment]
@jdgalt Step 1. Click the red flag button

![](https://requestpolicycontinued.github.io/media/rp-1.png)

Step 2. Click _Request Log_ on the bottom right corner.

![](https://requestpolicycontinued.github.io/media/menu.png)

Can you see it now?

**Comment by jdgalt** [comment]
Yes, thanks, I'll give it a try.

**Comment by nodiscc** [comment]
I think we should try to document the user interface a bit more, so I opened https://github.com/RequestPolicyContinued/RequestPolicyContinued.github.io/issues/25. Feel free to reopen this issue if you need more info
