### ISSUE TITLE
Blocked destination: "null"

### ISSUE THREAD

**Issue by Dezaimasu** [RequestPolicyContinued/requestpolicy#714]
Sorry if it's not the problem with your extension but just with my settings.
I see it on youtube, I'm not sure this "null" is exactly the reason why youtube won't enable html5-player for me instead of old flash-player, but there's nothing else blocked left. If I choose "enable all requests from youtube", html5 is working, and this "null" is in Allowed destinations. But I can't enable/disable this "null", there's no options for it.

![image2](https://cloud.githubusercontent.com/assets/1636242/10263764/435192bc-6a02-11e5-9243-72a0261c1ecf.png)

**Comment by netjeff** [comment]
Duplicate of #626, which includes the following as a workaround:

> You can work around this problem by manually adding a rule from host `*.youtube.com` to destinations with scheme `mediasource`.
>
> Here's a screenshot:
> ![screenshot](https://cloud.githubusercontent.com/assets/3266932/8681990/da0ff27c-2a27-11e5-92a1-8141a7cf4afd.jpg)

The main tracking issue is #619

**Comment by Dezaimasu** [comment]
Thanks. Sorry about duplicate.

**Comment by netjeff** [comment]
I also logged this as a duplicate, too.  Which is why I knew about the workaround.  :-)
