### ISSUE TITLE
Firefox Hello doesn't work in Block by default mode

### ISSUE THREAD

**Issue by Arinelle** [RequestPolicyContinued/requestpolicy#715]
There's a workaround here: (http://feeding.cloud.geek.nz/posts/making-firefox-hello-work-with-noscript-request-policy/)
But maybe it could work at startup or be an option for the user, without making them find this.

**Comment by nodiscc** [comment]
MOved to #716

**Comment by myrdd** [comment]
Reopening because #716 is just about the Firefox Accounts login screen.

Fixing Firefox Hello requires #742 because we need a wildcard rule. We need at least:

```
"about:loopconversation" → "https://hlg.tokbox.com"
"about:loopconversation" → "https://anvil.opentok.com"
"about:loopconversation" → "wss://*.tokbox.com"
```
