### ISSUE TITLE
Firefox services don't work in Block by default mode

### ISSUE THREAD

**Issue by Arinelle** [RequestPolicyContinued/requestpolicy#716]
I get an infinitely loading page instead of the service's login screen. Because it's not really a page but a frame, RequestPolicy doesn't offer me the option to allow anything, and I don't know what to manually allow.

**Comment by nodiscc** [comment]
From #715 

> There's a workaround here: (http://feeding.cloud.geek.nz/posts/making-firefox-hello-work-with-noscript-request-policy/)
But maybe it could work at startup or be an option for the user, without making them find this.

**Comment by myrdd** [comment]
The easy solution is just to add those rules to the other hard-coded compatibility rules in [`request-processor.compat.js: initializeApplicationCompatibility()`](https://github.com/RequestPolicyContinued/requestpolicy/blob/v1.0.beta10.1-signed/src/content/lib/request-processor.compat.js#L194)


    about:loopconversation -> opentok.com
    about:loopconversation -> tokbox.com
    firefox.com -> mozilla.com
    firefox.com -> opentok.com
    firefox.com -> tokbox.com

**Comment by Arinelle** [comment]
These rules are just for Firefox Hello and not for Firefox sharing services, though. Source: I added the rules manually, sharing services still don't work.

So… I'm not so sure about the issue merge nor about the easy label.

**Comment by myrdd** [comment]
@Arinelle if you want to help, you could take a look at RP's Request Log and then step-by-step add each rule necessary. Tell me if you need help.
