### ISSUE TITLE
RequestPolicyContinued not working on latest nightly

### ISSUE THREAD

**Issue by zeorin** [RequestPolicyContinued/requestpolicy#719]
FF 44.0a1.

Not sure what the issue is, but possibly related to the same issue KeeFox is having: https://github.com/luckyrat/KeeFox/issues/562 "changes to let, var, and const.", as I experienced them after the same update.

I saw no errors in the browser console, though, but I'm not sure if that's because one of my other extensions might be interfering with the browser console (I'm also running FireBug 3 alpa).

**Comment by myrdd** [comment]
Thanks for your report. I've seen those issues. They are already fixed, see commits c98af40 and 00b5521, currently available at [myrdd/requestpolicy/mozmill-marionette-migration](https://github.com/myrdd/requestpolicy/tree/mozmill-marionette-migration). I'll probably create a bugfix-release this weekend.

**Comment by myrdd** [comment]
Fixed in version _1.0.beta10.2_, which I've released just now.
