### ISSUE TITLE
Suggestion: Option to load blocked content anyway

### ISSUE THREAD

**Issue by jdgalt** [RequestPolicyContinued/requestpolicy#734]
This option, if turned on, would have the web site send blocked content even though we're not going to process or display it.  The point of doing so is to fool sites (such as Yahoo mail) which detect ad-blockers and disable some functionality when they find them.

**Comment by nodiscc** [comment]
You could allow the request, but still use element hiding/cosmetic filtering on your ad blocker to prevent displaying them.

**Comment by jdgalt** [comment]
RP *is* my ad blocker.  I expect it to do the job.

**Comment by nodiscc** [comment]
> RequestPolicy is a Firefox extension that gives you control over cross-site requests.

RP is not an ad blocker. It just applies an allow/deny policy to network requests. It can either block the request (some pages will detect it as ad blocking), or allow it (if the request loads an image resource, it will display if the DOM says so).

What you want is a filter for _displayed elements_, which is out of scope for RequestPolicy. Some ad blockers feature cosmetic blocking, but there are other addons that allow you to do so. RP works on a network level, and I think adding display filtering/DOM modification capabilities would impact the project's complexity and usability. 

@myrdd @jdgalt I suggest this to be marked as wontfix.

**Comment by ivan-kolmychek** [comment]
If you need an adblocker, don't you think that you should actually use the adblocker?

I use both RequestPolicy to block unwanted 3rd-party requests (which includes any 3rd party advertisment system) and ad-blocker (AdBlock+) for advertisment that are loaded from the same site.

**Comment by nodiscc** [comment]
You could also try the browser's `Block images from..` feature (`Right-click image > Image information > `)

**Comment by jdgalt** [comment]
Adblock+ just does a subset of what RP does, while giving you fewer choices.  Using both would be thick.

**Comment by myrdd** [comment]
I agree with @nodiscc and @ivan-kolmychek, an adblocker should be used to do what you want.

> Adblock+ just does a subset of what RP does

Not exactly, RP currently lacks support of URI paths and regex rules, Which means you can't hide elements coming from the same domain.

> Using both would be thick.

In terms of memory usage and processor time, you could disable all lists in the adblocker and only use your own list. However, you'll have a slightly worse usability when using multiple blockers and you actually _don't want_ something to be blocked.

Closing as wontfix.

**Comment by nodiscc** [comment]
@jdgalt uBlock Origin is miles ahead from Adblock+ and should be recommended instead.
