### ISSUE TITLE
Rule works one time and does not work second time

### ISSUE THREAD

**Issue by Myppomeu** [RequestPolicyContinued/requestpolicy#738]
RequestPolicy Continued 1.0.beta11pre2
Firefox ESR 38.4.0

Steps to reproduce:
* Set default policy to allow requests by default.
* Create two new rules:

Policy | Source | Destination
------------ | ------------- | -------------
Allow | *.vk.com | *.vk.com
Block |  | *.vk.com

* Try to click on link on vk.com to external site.

**What I expect:**
That external link will be opened without requests.

**What I get:**
First time I click on link, it opens without requests. Second time RequestPolicy asks me that vk.com/bla-bla1 has asked to redirect to vk.com/bla-bla2. Third time I click on link, it opens without requests. Etc.
Bug reproduces ablosulely stable.

**Comment by myrdd** [comment]
Umm, actually the redirection notification appears/disappears _each second time_.

I don't know why, but the HTTP response only contains a "Location" header each second time the link is clicked. The different behaviour comes from the different implementation of "normal request" vs. "redirect request" checkings in RP. That inconsistency issue is tracked in #623.

**Comment by myrdd** [comment]
The bug should be fixed in `1.0.beta11pre3`, which is released now.
