### ISSUE TITLE
ability to show full domains  in the menu and then to allow either full or 2nd level

### ISSUE THREAD

**Issue by msxfm** [RequestPolicyContinued/requestpolicy#74]
<a href="https://github.com/jsamuel"><img src="https://avatars.githubusercontent.com/u/1240282?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jsamuel](https://github.com/jsamuel)**
_Thursday Dec 22, 2011 at 18:50 GMT_
_Originally opened as https://github.com/RequestPolicy/requestpolicy/issues/74_

----

    imported trac ticket
    created: 2010-01-27 22:01:37
    reporter: al_9x

It is helpful when making whitelisting decisions to see the full domain, but then to be able to chose either full or 2nd level to allow in the sub-menu

**Comment by myrdd** [comment]
I'm closing this issue in favor of #688.

The requested option here regarding version 1.0 and regarding https://github.com/RequestPolicyContinued/requestpolicy/issues/688#issuecomment-128519307 would be:

* **default policy:** deny
* **strictness:** full domain
* **left menu column:** full domain
* **right menu column:** show base domain
