### ISSUE TITLE
Redirect from same site or domain: broken

### ISSUE THREAD

**Issue by orbisvicis** [RequestPolicyContinued/requestpolicy#740]
#### Versions:
  Firefox 42.0, windows and linux*
  RequestPolicy continued 1.0beta11pre2

\* Firefox pre 42.0 remains unaffected.

#### When:
  After upgrading to firefox 42, and also possibly upgrading RequestPolicy Continued.

##### Redirect from same site:
* Reload previously opened tab, if "show my windows and tabs from last time" is enabled
* Jumping to an anchor
* Opening a link in a new tab (whether or not same domain)
* Loading pages from the tab's history (whether or not same domain)

Occurs randomly but frequently. If triggered for URI.X, a message bar is shown: "This webpage has asked to redirect to URI.X [allow] [deny] [add rule]", where URI.X represent the exact same URI.

##### Fails to allow requests to the same domain, despite having configured the extension to do so:

Occurs randomly but less frequently. Must select "Temporarily allow requests from *DOMAIN.X" for each affected tab, where DOMAIN.X is the domain of the tab's URI.

#### Settings (these are the default settings):
extensions.requestpolicy.autoReload;true
extensions.requestpolicy.defaultPolicy.allow;false
extensions.requestpolicy.defaultPolicy.allowSameDomain;true
extensions.requestpolicy.indicateBlacklistedObjects;false
extensions.requestpolicy.indicateBlockedObjects;true
extensions.requestpolicy.lastAppVersion;42.0
extensions.requestpolicy.lastVersion;1.0.beta11pre2
extensions.requestpolicy.log;false
extensions.requestpolicy.log.level;0
extensions.requestpolicy.log.types;1023
extensions.requestpolicy.menu.info.showNumRequests;true
extensions.requestpolicy.menu.sorting;numRequests
extensions.requestpolicy.prefetch.dns.disableOnStartup;false
extensions.requestpolicy.prefetch.dns.restoreDefaultOnUninstall;true
extensions.requestpolicy.prefetch.link.disableOnStartup;true
extensions.requestpolicy.prefetch.link.restoreDefaultOnUninstall;true
extensions.requestpolicy.privateBrowsingPermanentWhitelisting;false
extensions.requestpolicy.startWithAllowAllEnabled;false
extensions.requestpolicy.welcomeWindowShown;true

**Comment by myrdd** [comment]
Hi, I could not reproduce the problem. Please try to reproduce the problem with all other add-ons disabled and/or in a new profile. It might be an add-on incompatibility. Details you can find [here](http://requestpolicycontinued.github.io/Contributing.html).

**Comment by myrdd** [comment]
any update?

**Comment by myrdd** [comment]
please reopen the issue when you got more information
