### ISSUE TITLE
Document whitelist file format

### ISSUE THREAD

**Issue by mk-pmb** [RequestPolicyContinued/requestpolicy#743]
I skimmed through the dev docs but couldn't find where the format of the whitelist file (for export/import) is explained. An exported sample looked quite easy to understand, however I'm wondering about how to insert comment lines. I could test some usual line comment prefixes and see how they work for import, but I'd prefer an officially declared comment syntax, to ensure future compatibility.

**Comment by myrdd** [comment]
First of all, I'm not sure you're talking about the 1.0 branch, are you? 0.5 isn't supported anymore, so I'll talk about 1.0.

The file format is JSON. Sadly json does not support comments. An example you can find here: https://github.com/RequestPolicyContinued/requestpolicy/blob/dev-1.0/src/content/lib/ruleset.jsm#L55, but yes, so far the format is undocumented.

Without changing the file format it's not possible to have line comments. However, it could be possible to assign a comment to a rule, is this what you're looking for? – This is what I once suggested in that comment: https://github.com/RequestPolicyContinued/requestpolicy/issues/339#issuecomment-62297970

**Comment by mk-pmb** [comment]
> 0.5 isn't supported anymore

Sorry I didn't check, I'm on 0.5 indeed. I trusted Firefox's addon manager claiming it was the latest version, probably because it's also the latest one that its addon search can find. Looks like I'll have to read up on how to install RPC then. :-/

That 1.0 config format looks a lot like what I had in the old RequestPolicy before I discovered "Continued". (I think that was 0.3.x or similar.)

The example code seems to be in a format much more friendly to versioning than JSON is:
```js
    "deny" : [
      {'d':{'h':'google-analytics.com'}},
      {'o':{'s':'https'},'d':{'s':'http'}},
    ]
```
With JSON, that last comma would have to be omitted. If the saved files are in JSON, by default, the semi-last line would flicker when a last line is added or removed. Could be mitigated by putting commas on a line by themselves (probably considered ugly) or by adding a constant terminator at the end of the list, which could be a comment.

I support the idea of using a `comment` key on the objects. Docs should clarify how RPC will treat keys that it doesn't know. I'd say it should ignore them, as they might be imported from a future version's export function. If that's a problem, maybe at least ignore the `"#"` and `""` (empty string) keys.

In the array of rules (which are objects), I'd like to have strings allowed and ignored, at least strings that are either empty or start with `#`. That will help me process blocks of rules with `sed`.

**Comment by myrdd** [comment]
> Sorry I didn't check, I'm on 0.5 indeed. I trusted Firefox's addon manager claiming it was the latest version, probably because it's also the latest one that its addon search can find.

Yeah, it's because RP 0.5 still officially is the "stable" version. This is due to some missing backwards feature compatibility which 1.0 has, see https://github.com/RequestPolicyContinued/requestpolicy/issues?q=is%3Aopen+is%3Aissue+label%3A%221.0+vs+0.5%22

> With JSON, that last comma would have to be omitted. If the saved files are in JSON, by default, the semi-last line would flicker when a last line is added or removed.

For the `user.json` saved by RP itself you'll have to live with that.

> I support the idea of using a comment key on the objects.

By "objects" you mean "rules"? Like this?

```json
    "deny" : [
      {"d":{"h": "google-analytics.com"}, "comment": "my comment"}
    ]
```

> Docs should clarify how RPC will treat keys that it doesn't know. I'd say it should ignore them, as they might be imported from a future version's export function.

True. I'll need to ensure that. I've added issue https://github.com/RequestPolicyContinued/requestpolicy/issues/745

> In the array of rules (which are objects), I'd like to have strings allowed and ignored, at least strings that are either empty or start with #.

As long as you keep the json file a valid json file there should be no problem.

**Comment by mk-pmb** [comment]
>> I support the idea of using a comment key on the objects.

> By "objects" you mean "rules"? Like this?

The rules are of most importance, but I'd prefer support for comments on all objects in the config file, with the [JSON definition](http://json.org/) of "object" (= dictionary).

**Comment by myrdd** [comment]
> I'd prefer support for comments on all objects in the config file

When issue #745 is fixed you can put additional key-value-pairs on any object – which is comments in your case.

Btw what's the purpose of this issue now? Should be documented how `user.json` looks like? That is, https://github.com/RequestPolicyContinued/requestpolicy/blob/dev-1.0/src/content/lib/ruleset.jsm#L55? I think it could go to the FAQ: https://github.com/RequestPolicyContinued/requestpolicy/wiki/FAQ

**Comment by mk-pmb** [comment]
> Btw what's the purpose of this issue now?

My original concern was how to build git filters for `user.json` in a future-proof manner. Since I now use a generator instead, that doesn't greatly matter to me any longer.

**Comment by myrdd** [comment]
I see, so I'll close this issue. Thanks for your input.
