### ISSUE TITLE
New icon (color) for "all blocked only by user policies"

### ISSUE THREAD

**Issue by wilkowy** [RequestPolicyContinued/requestpolicy#744]
Could you add a separate icon/state to differentiate between:
- RP blocked requests because of "Block requests by default" policy (suggestion: red flag as now it is)
- RP blocked only requests marked by the user for blocking (and none by default policy) (suggestion: blue flag or gray flag with red exclamation)

In case of mixed blocks (default policy and user policy) standard red flag would be used.

**Comment by myrdd** [comment]
> gray flag with red exclamation

Something like that will be implemented I guess. There's been some discussion, please take a look at it – issue https://github.com/RequestPolicyContinued/requestpolicy/issues/98. I'm closing this as a duplicate.

There were multiple suggestions. I'm in favor of @nodiscc's proposal – https://github.com/RequestPolicyContinued/requestpolicy/issues/98#issuecomment-61994963
