### ISSUE TITLE
Missing placeholder for images on some sites

### ISSUE THREAD

**Issue by AtTheGates** [RequestPolicyContinued/requestpolicy#747]
Hello,

I noticed missing placeholder for images on some sites. One site I remember recently is: http://www.hardwareluxx.de/community/f19/zeigt-eure-zimmer-wohnung-774499-260.html#post24187801

As you can see on the screenshot, the placeholders for the images of "vf-d.de" are missing.

![placeholder_rp0 5 30](https://cloud.githubusercontent.com/assets/9346225/12108124/06db283c-b374-11e5-83a6-f0d31afa8d88.png)

With Policeman v0.18.1.1 the placeholders are shown correctly:

![placeholder_pm0 18 1 1](https://cloud.githubusercontent.com/assets/9346225/12108127/0bae08de-b374-11e5-8614-5d7a9896eac2.png)

Tested with RequestPolicyContinued v0.5.30 and v1.0.beta11pre4 in a new, clean profile (without any other extensions) and Firefox v43.0.3.

Hope that helps. Thank you in advance. :-)

**Comment by myrdd** [comment]
Thank you for the report. I can confirm the bug. It happens when you load an URL with a "fragment" part, e.g. `http://example.com/#this-is-a-fragment`

**Comment by myrdd** [comment]
Fixed in the latest nightly release

**Comment by AtTheGates** [comment]
Great! Thank you very much.

Will it also be fixed in the 0.5 branch?

Greets

**Comment by myrdd** [comment]
> Will it also be fixed in the 0.5 branch?

Sorry, no. RP 0.5 isn't supported anymore. It's just there for those who want to use it, but as soon as [E10s](https://wiki.mozilla.org/Electrolysis) reaches Firefox Stable, RP 0.5 won't work anymore, unless you disable e10s.

**Comment by AtTheGates** [comment]
Ok, no problem. Thank you and keep up the good work. :-)
