### ISSUE TITLE
A few problems

### ISSUE THREAD

**Issue by charmparticle** [RequestPolicyContinued/requestpolicy#758]
I had the "Privacy" subscription enabled in RequestPolicy, and went to visit facebook.com. In my configuration, facebook.com should be able to connect with fbcdn.com, but the privacy subscription rule prevented the connection from happening. It would appear that different rulesets can create conflicts, such that one supercedes another.

Another thing I've noticed is that http redirects always invoke a prompt. Is there any way to simply allow redirects globally, so that I can click a link and get to the destination site without being prompted?

**Comment by myrdd** [comment]
> I had the "Privacy" subscription enabled in RequestPolicy, and went to visit facebook.com. In my configuration, facebook.com should be able to connect with fbcdn.com, but the privacy subscription rule prevented the connection from happening. It would appear that different rulesets can create conflicts, such that one supercedes another.

Please see #746.

> Another thing I've noticed is that http redirects always invoke a prompt.

Whether a redirection invokes a prompt or not depends on your policy. In default-deny mode without any rules you should see not only a prompt for cross-domain requests, but also for `http <-> https` on the same domain.

The feature request for redirection-specific rules is #173.

> Is there any way to simply allow redirects globally

Not yet. Watch #53.
