### ISSUE TITLE
issue the breaks part of wunderground.com

### ISSUE THREAD

**Issue by alexredmonjr** [RequestPolicyContinued/requestpolicy#773]
At issue is a severe weather alert popup at the wunderground.com's Full Screen radar, not confused said's Interactive Radar, (which works fine). When I click on a highlighted country that pop up doesn't work, instead I get an error in error console.

18:11:03.787 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.wunderground.com/US/PA/038.html?view=USAlertTextBubble. (Reason: missing token 'x-requested-with' in CORS header 'Access-Control-Allow-Headers' from CORS preflight channel).1 <unknown>

**Comment by myrdd** [comment]
The same-origin policy has nothing to do with RP, it's a webbrowser security mechanism:

* same-origin policy: [MDN](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy), [wikipedia](https://en.wikipedia.org/wiki/Same-origin_policy)
* CORS: [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS), [wikipedia](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing)
* [Mozilla source-code search for `CORSMissingAllowHeaderFromPreflight`](https://mxr.mozilla.org/mozilla-central/search?string=CORSMissingAllowHeaderFromPreflight) – that's your specific error message code.

Try reproducing the error in a fresh profile. If the problem persists, it's a problem with the website. If the problem goes away, there's something "wrong" with your profile. Might be some add-on, or might be a preference.

**Comment by alexredmonjr** [comment]
My response: Add-on in question is your add-on when I uninstall it, error goes away.. My profile was refreshed a few days ago.

**Comment by myrdd** [comment]
Okay, so please provide step-by-step instructions how to reproduce the bug. I'm not going to learn how the website works.
https://requestpolicycontinued.github.io/Contributing

**Comment by alexredmonjr** [comment]
I'm sorry for the last response, have further troubleshooting the problem. I have fixed my issue, by changing my saved bookmark for said web site.
I like to thank you for your great extension, and if I see anything else, I'll let you know. However this issue is resolved.
