### ISSUE TITLE
Referer changing within the same site 

### ISSUE THREAD

**Issue by gineadai** [RequestPolicyContinued/requestpolicy#777]
When you check browser with `Version 0.5` on  [ip-check.info](http://ip-check.info) for atribute `Referer` it show value `hidden (changed when switching the website)` which is `good` rating, but with `Version 1.0` it show  value `Referer hidden (changed when switching the domain or subdomain)` which is a `medium` rating.

Website recommends that the referer should be hidden if you move to another website. It should remain unchanged as long as you move within the same website. What is `Version 1.0` not does.

**Comment by gineadai** [comment]
I understand now what i need.  `Version 0.5` has `Strictness` or `extensions.requestpolicy.uriIdentificationLevel` where you can change the level of classification to use for allowing same-site request. And  `Version 0.5` use by default level `Base domain (requestpolicy.com)`, when `Version 1.0` use 'Full domain (www.requestpolicy.com)' and you can't change it.  Can you implement this in current version?

**Comment by myrdd** [comment]
Your instructions were still incomplete. Well, you've found out the issue yourself. You're right, strictness still needs to be implemented. See #474. I'm closing this as a dupe.

> Can you implement this in current version?

I'm currently working on it.

> Version 1.0 use Full domain (www.requestpolicy.com)'and you can't change it

In fact v1.0 uses base domain strictness, but indeed, you can't change it.
