### ISSUE TITLE
Right-click policy edit capability

### ISSUE THREAD

**Issue by jhvance** [RequestPolicyContinued/requestpolicy#779]
I want the ability to change an existing policy by right-clicking on that entry, which then pops up options to "allow" or "block".  I believe this is a necessary feature because there are a number of pre-installed "allow" policies following installation of Firefox onto a new WIndows 10 (Home) laptop which I cannot seem to easily change, now that Request Policy Continued has been installed.  The only way to do so at present would appear to be an incredibly laborious process by entering information in three different boxes for each orign-destination option, and with a large number of policies which are now allowed that I wish to block, far too tedious an effort to accomplish in reasonable time.

[Added] A right-click option to simply delete a policy would be okay, too -- next time the request arose, it could be dealt with as desired.

**Comment by myrdd** [comment]
> there are a number of pre-installed "allow" policies

Those are subscriptions. You can disable them in RP's settings.

> [Added] A right-click option to simply delete a policy would be okay, too -- next time the request arose, it could be dealt with as desired.

There _should_ be a button (in the menu) to change the policy from allow to block, or vice versa. If not, please provide a screenshot.

**Comment by myrdd** [comment]
no response, closing.
