### ISSUE TITLE
some destinations no longer appearing

### ISSUE THREAD

**Issue by banther7** [RequestPolicyContinued/requestpolicy#781]
dont know why but for several sites i go to i notice request policy isnt blocking specific sites anymore or isnt working properly. it will allow the sites i allowed to work still but blocked stuff doesnt seem to work. its hard for me to explain sorry.

**Comment by myrdd** [comment]
> its hard for me to explain sorry.

A screenshot of the menu could help. What's your browser, browser version, and RP version?

**Comment by myrdd** [comment]
no response, closing.
