### ISSUE TITLE
FF + Request Policy and Sandboxie - Direct Access to config files

### ISSUE THREAD

**Issue by Quassar89** [RequestPolicyContinued/requestpolicy#785]
Welcome im using Firefox with Program Sandboxie

What is Sandboxie:
Sandboxie isolate all incoming files / changes during Firefox sesion if i close and restart FF again, 
All settinings and other changes will back to start point before i used Sandboxie(started specific program inside)..

My problem:
I wanna save all my white/black list and other changes in Request Policy
For that i have set in sandboxie direct access 
http://www.sandboxie.com/index.php?ResourceAccessSettings#file

i use also NoScript, for no Script i had add this 2 files and it work :)
http://www.wilderssecurity.com/threads/direct-access-to-noscript-in-sandboxie.334954/#post-2137184

So which,& where RequetPolicy storage files with configuration 

I hope my info is enought: detailed to let you understand miine situation and help resolve my problem :*
Im wating for help

**Comment by myrdd** [comment]
> So which,& where RequetPolicy storage files with configuration

If you are using the __1.0 branch__, the rules are stored in the `<profile_dir>\requestpolicy\` directory. The file  `<profile_dir>\requestpolicy\policies\user.js` is the actual user-rules file. However, I recommend you to whitelist the whole `requestpolicy` directory.

If you are using the __0.5 branch__ instead, the rules are stored in the `<profile_dir>\prefs.js` file.

For both branches, the preferences are stored in `<profile_dir>\prefs.js`.

`<profile_dir>` is `%AppData%\Mozilla\Firefox\Profiles\*\` in your case.

**Comment by Quassar89** [comment]
Ok i tested it i needed add both path

full direct for folder \requestpolicy and prefs.js
