### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by stepshal** [RequestPolicyContinued/requestpolicy#786]
It' doesn't show up with `requestpolicy` in github search results. You have to open https://github.com/RequestPolicyContinued/RequestPolicyContinued.github.io, then click to https://github.com/RequestPolicyContinued, and then you end up here at last. You can rename it to `requestpolicycontinued`, or `RPContinued` i don't know.

**Comment by TPS** [comment]
This isn't actually a problem with RPc, but _is_ a longstanding problem with @GitHub, & has been reported many times, e.g., https://github.com/isaacs/github/issues/24, https://github.com/isaacs/github/issues/152, https://github.com/isaacs/github/issues/562, https://github.com/isaacs/github/issues/621, just to choose https://github.com/isaacs/github.  [Contact @GitHub](https://github.com/contact) supporting 1 or more of the above, & hope they choose to fix it! :smile:

**Comment by myrdd** [comment]
@stepshal Not really a solution, but a workaround if you know it: You can search for [`requestpolicy fork:true`](https://github.com/search?q=requestpolicy+fork%3Atrue). See [Github help](https://help.github.com/articles/searching-repositories/#search-based-on-the-number-of-forks-the-parent-repository-has)
