### ISSUE TITLE
Requests to and from null domain

### ISSUE THREAD

**Issue by djarb** [RequestPolicyContinued/requestpolicy#787]
After updating RequestPolicy Continued on 2016-06-07, Firefox extensions such as FloatNotes are again being blocked with no way to allow them to operate correctly.

When looking at the sources and destinations, I see that they are now producing requests to and from a domain called 'null'. That in itself would not be a problem, except that even after creating rules to allow those requests, RequestPolicy still blocks the requests from the null origin. This prevents the extension from correctly accessing it's CSS and other resource files.

**Comment by myrdd** [comment]
Hi @djarb, I suppose a change in FloatNotes created this incompatibility. I will provide a fix for this. Until then, you need to add the following rules. You need to add them manually on "about:requestpolicy?yourpolicy".

* Rule 1:
  * __Origin:__ all fields empty
  * __Destination:__ scheme: floatnotes
* Rule 2:
  * __Origin:__ scheme: floatnotes
  * __Destination:__ scheme: chrome / host: floatnotes_note

Please tell me if this works.

**Comment by djarb** [comment]
That does work. My apologies for bringing up an already solved problem.

**Comment by myrdd** [comment]
> That does work. My apologies for bringing up an already solved problem.

Good! No worries, this is a valid issue, since I want add-ons to work
out-of-the-box.

**Comment by myrdd** [comment]
@djarb Looks like FloatNotes does not exist anymore [1], so I close this issue.

[1] https://addons.mozilla.org/en-US/firefox/addon/floatnotes/

**Comment by djarb** [comment]
The issue applies to every similar addon I've tested, so closing it may be
a bit premature.

**Comment by myrdd** [comment]
@djarb which add-ons?

---

In your first post you wrote:

> After updating RequestPolicy Continued on 2016-06-07, (...)

I guess you mean 2016-06-27, because 2016-06-20 was the release date of `v1.0.beta12.0`. See the [version history](https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-continued/versions/1.0.beta12.0).

> When looking at the sources and destinations, I see that they are now producing requests to and from a domain called 'null'.

Please check the request log for the full URI of the blocked resources.

---

Feel free to reopen this issue when posting more information.

**Comment by djarb** [comment]
Sticky Notes ( https://addons.mozilla.org/en-US/firefox/addon/sticky-notes/
) for certain, and a couple similar ones if memory serves, but I don't have
a record of which.

**Comment by myrdd** [comment]
@djarb I cannot find any issue with Sticky Notes. Please follow the [contribuiton guidelines](https://requestpolicycontinued.github.io/Contributing), and also provide your RP and browser version numbers.

**Comment by djarb** [comment]
I haven't seen any problem since the upgrade to 1.0beta12.3

**Comment by myrdd** [comment]
Well, perfect! I guess you had a pre-beta12.2 version. Please always verify you've got the most recent version.

**Comment by djarb** [comment]
1.0beta12.3 confirmed
