### ISSUE TITLE
Font transform issue on tampabay.com

### ISSUE THREAD

**Issue by agilbertson1977** [RequestPolicyContinued/requestpolicy#789]
Steps to reproduce:

1. Create a new Pale Moon profile
2. Set RP's default policy to: "deny"
3. Load http://www.tampabay.com/news/breaking/
4. Allow requests to match the attached screenshot showing RP's menu

Story headlines for stories that have a picture included have a weird character (a black circle with a white "+" in the center) that overlaps some of the headline text.

Instead, a "picture" icon should appear and push the headline text over.

Request Policy menu
![font-issue-rpc-menu](https://cloud.githubusercontent.com/assets/5439748/16414243/8d353b9c-3d04-11e6-8eb7-b68e585c00ad.png)

How it should look
![font-issue-no-rpc](https://cloud.githubusercontent.com/assets/5439748/16414242/8d340a10-3d04-11e6-9705-ad72810a87f2.png)

How it does look
![font-issue-rpc-enabled](https://cloud.githubusercontent.com/assets/5439748/16414244/8d37eff4-3d04-11e6-9ff1-7662d1782864.png)

**Comment by myrdd** [comment]
@agilbertson1977 are you still seeing this issue? It works for me now. However, it takes 1-2 seconds until the correct icon appears. Below is my screenshot.

If you're still having this problem, please check the request log to see what happens.

![palemoon](https://cloud.githubusercontent.com/assets/4286829/17083228/9e1c34f8-5198-11e6-9faf-ac1c5cea569a.png)

**Comment by agilbertson1977** [comment]
I'm no longer experiencing this issue.  Thanks for getting this fixed!
