### ISSUE TITLE
DNS Prefetching and network.dns.disablePrefetchFromHTTPS

### ISSUE THREAD

**Issue by wilkowy** [RequestPolicyContinued/requestpolicy#795]
I'm not sure if network.dns.disablePrefetch is superior to (if overrides it) network.dns.disablePrefetchFromHTTPS and if this setting is still used (by default it does not exist, but https://developer.mozilla.org/en-US/docs/Web/HTTP/Controlling_DNS_prefetching mentions it), but RP's UI controls only network.dns.disablePrefetch.

**Comment by nodiscc** [comment]
It seems that both are used.

https://github.com/pyllyukko/user.js/blob/master/user.js#L334

Depending on the scope of RP's planned functionality, this user.js also contains relevant prefs (automatic connections)

**Comment by wilkowy** [comment]
BTW. It is supposed to be „true” always (also when non existent == true) so the only moment it is updated should be when disabling DNS Prefetch then it should be checked if this variable exists and value changed to true (if false).

**Comment by myrdd** [comment]
Although I'm quite sure `network.dns.disablePrefetch` is superior to `network.dns.disablePrefetchFromHTTPS` [1], I think it's a good practice to set the latter pref to `true` anyways – of course only in case it already has a user-defined value of `false`.

[1] See [nsDocument.cpp](https://hg.mozilla.org/mozilla-central/file/ddeb0295df69/dom/base/nsDocument.cpp) lines 3108, 4747-4749

> Depending on the scope of RP's planned functionality, this user.js also contains relevant prefs (automatic connections)

I'd like to improve the system of "recommended prefs" (#749) before cluttering the settings page with checkboxes.

**Comment by myrdd** [comment]
Implemented in [`v1.0.beta12.3.1526.r4013b3b.pre`](https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-continued/versions/1.0.beta12.3.1526.r4013b3b.pre)
