### ISSUE TITLE
Requestpolicy blocks chrome://xxx urls breaking Flash ask to activate function

### ISSUE THREAD

**Issue by alexlehm** [RequestPolicyContinued/requestpolicy#797]
__Environment:__

Requestpolicy continued 1.0.beta 12.2
Firefox 47.0
Windows 10 Home 64 bit

__Steps to reproduce:__

1. Create a new Firefox profile
2. Set RP's default policy to: "deny"
3. set the flash plugin to "ask to activate" in plugin settings
4. go to any site that requires flash, e.g. https://get.adobe.com/flashplayer/

__What happens?__

request policy blocks a host called "pluginproblem", which is actually the url chrome://pluginproblem/content/pluginProblem.xml which keeps the warning message that flash could be loaded to run the content from loading.

__What should happen?__

I think requestpolicy should ignore urls with chrome or resource as this breaks internal functions of firefox. In the case of pluginproblem this can be easily fixed by allowing access to the host from any url, but the same happens with other urls as well, e.g. wich Ghostery which uses a url resource://resources-ghostery-at-firefox/... to load images

**Comment by myrdd** [comment]
Confirmed.

> I think requestpolicy should ignore urls with chrome or resource as this breaks internal functions of firefox. In the case of pluginproblem this can be easily fixed by allowing access to the host from any url (...)

We could do a discussion about that, but if so, please at issue #783. My current policy on `resource://` and `chrome://` issues is to whitelist necessary resources in the code. See for example #788, which also mentions the "pluginproblem" problem.

> (...) the same happens with other urls as well, e.g. wich Ghostery which uses a url resource://resources-ghostery-at-firefox/... to load images

If there is an uri blocked by RP, please report it. However, in my opinion Ghostery could just put `data` uris on the website instead of a firefox-internal uri.

**Comment by myrdd** [comment]
Fixed in [`v1.0.beta12.3.1526.r4013b3b.pre`](https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-continued/versions/1.0.beta12.3.1526.r4013b3b.pre)
