### ISSUE TITLE
Add New Rule Behaviour

### ISSUE THREAD

**Issue by jeronymite** [RequestPolicyContinued/requestpolicy#811]
When RequestPolicyContinued displays an in-window banner that says a site is requesting access to another site and it offers Allow, Deny or New Rule, using Allow usually continues to the requested site; using New Rule to allow the request usually drops out to the empty New Tab that was created -- one then has to go back to the original link and click it again, often landing one back in the same situation for subsequent access requests, or the same request over and over again.

It is as if adding the new rule either completes but does not then continue to the site allowed (as would happen with Allow) or it fails to add the rule at all and just cycles around asking again and again. Only very occasionally does it seem to behave as expected.

Shouldn't New Rule add the rule unequivocally and then definitely drop through to the requested page?

Thanks.

**Comment by myrdd** [comment]
> Shouldn't New Rule add the rule unequivocally and then definitely drop through to the requested page?

Yes, definitely. Sorry this isn't fixed yet. It's already been reported in #808. Closing as duplicate.

**Comment by jeronymite** [comment]
Thanks, and apologies for the duplicate post.
