### ISSUE TITLE
Policy problem with http://riot.im (former vector.im)

### ISSUE THREAD

**Issue by madduck** [RequestPolicyContinued/requestpolicy#823]
I've verified this problem with a fresh FF profile using no other addons than RequestPolicy Continued (v.1.0.beta12.3). The screenshots, however, where made with my full profile. Please excuse…

Riot IM is a Javascript-based in-browser front-end to http://matrix.org, a federated chat/IM protocol. Users can set up their own "homeservers" and the protocol federates between them. My homeserver is https://matrix.madduck.net:8448/.

My RequestPolicy is configured to deny-by-default (as it should be). I have permanent RequestPolicies in place to "allow all traffic **to and from** `*.madduck.net`" (2 user policies yielding "allow").

The gist of the problem I am reporting is that logging in to https://riot.im/app/#/ does not work because RequestPolicy somehow inhibits the Javascript code to talk to my homeserver, and I cannot figure out what the problem is.

First, it seems that the aforementioned policies for `*.madduck.net` are simply being ignored. Loading the site makes the context menu of RequestPolicy offer the choice to "allow traffic from `riot.im`". Despite the aforementioned policies, `madduck.net` is listed as a "blocked destination":

![screenshot1](https://cloud.githubusercontent.com/assets/195073/20859608/2eab1cb2-b95b-11e6-9eab-c9f10dec102f.png)

Second, when I explicitly "allow traffic from `riot.im` to `madduck.net`", it still does not work, as `madduck.net` continues to be a "blocked destination".

I am left with the option to "allow all traffic from `riot.im`, but even then, `madduck.net` is still listed as a "blocked destination":

![screenshot2](https://cloud.githubusercontent.com/assets/195073/20859610/36b7e12e-b95b-11e6-82e8-3bacceea30c0.png)

Only after I "allow all traffic from `riot.im`" (which is not what I want to do) does the login and JS-frontend actually work.

If this is not a bug in the functionality, then at least the UI could communicate better what's going on.

Thanks for this great plugin and your time reading my bug report!

**Comment by myrdd** [comment]
Hello and sorry for my late reply. Please see the [rules help](https://requestpolicycontinued.github.io/Rules.html) and https://github.com/RequestPolicyContinued/requestpolicy/issues/473. You need to explicitly specify the destination port in your case.

**Comment by madduck** [comment]
Okay, thanks @myrdd, specifying the port worked. I will also track #473 from now on.
