### ISSUE TITLE
Broken about:addons page.

### ISSUE THREAD

**Issue by Marc05** [RequestPolicyContinued/requestpolicy#825]
The about:addons page on FireFox 50.1.0 is broken. The log shows that the origin about:addons to destination mozilla.org is blocked. I tried adding a rule with the origin of about:addons, but it did not work.

**Comment by myrdd** [comment]
> The about:addons page on FireFox 50.1.0 is broken. The log shows that
> the origin about:addons to destination mozilla.org is blocked.

You're talking about RPC 1.0.x?

> I tried
> adding a rule with the origin of about:addons, but it did not work.

Be sure to enter "about" in the "scheme" field, and leaving the "host"
of the origin empty. "addons" is the_ path_ part of the uri.

**Comment by metadings** [comment]
I did `git clone [github.com/RequestPolicyContinued/requestpolicy/](https://github.com/RequestPolicyContinued/requestpolicy/)... and I was going to do `make` which is like `make nightly-xpi` and I also did `make beta-xpi`!

The `nightly` didn't work, as in `about:addons` the click on `Einstellungen` was about to redirect to `about:requestpolicy`, which didn't work...

The `beta` actually worked, however, there are two versions of RequestPolicy... There was one with a default menu and a ** nice dialog** for settings. There was another one with a **nice menu** and bullshit settings.

Now which one should I `make`, I didn't find the one with the "nice dialog" ...

**Comment by metadings** [comment]
OHA, you're using `git checkout` A LOT, but no one uses `master` or `dev-1.0`...

Well, now I'm going to look into your CODE ...

**Comment by metadings** [comment]
Now I'm on `dev-1.0-releases` ... however I couldn't succeed.

I've found the one version with a **nice menu**, I couldn't find the one with the **nice dialog** ...

**Comment by myrdd** [comment]
@metadings This is very off-topic. Please create a new issue.

I'm working on the `dev-1.0` branch. The `master` branch is RP Legacy.
If you just want to use RP, please install RP from AMO.
If you want to develop RP, I suggest you to run `make run`. Be sure to disable e10s.
You can also use other Firefox versions, e.g. use `make run app_branch=esr`.
If you just want to get the xpi, `make nightly-xpi` is correct. Again, e10s must be disabled.
No idea what you mean by "nice menu/dialog". There's v0.5 and v1.0.
If you've got further questions, please create a new issue!

**Comment by metadings** [comment]
What is "AMO" and what "e10s"?

**Comment by Marc05** [comment]
>Be sure to enter "about" in the "scheme" field, and leaving the "host" of the origin empty.

This worked, thank you. I suppose the question now is why did it break, or at least, should this not be allowed by default?

**Comment by metadings** [comment]
Yes, thank you. Looks like I'm now diving deeper into RequestPolicy :-)

Looks like you're using a lot of dependencies, so just downloading, `make`ing and then running RequestPolicy isn't that easy.

**Comment by metadings** [comment]
Ya, this looks very well... You're working on the one with the **nice menu** :-)

**Comment by myrdd** [comment]
> I suppose the question now is why did it break, or at least, should this
> not be allowed by default?

It should. What is the exact destination hostname?
RP currently allows requests from "about:addons" to
"https://services.addons.mozilla.org/":

https://github.com/RequestPolicyContinued/requestpolicy/blob/5dc9768405420037a1324a1a73a05390ec7b9e9f/src/content/lib/request-processor.compat.js#L243

**Comment by myrdd** [comment]
> I don't want to install some Firefox-nightly, just to edit the RequestPolicy addon...

To use a custom firefox (or seamonkey, or palemoon), just use:
`make run app_binary=/path/to/my/firefox.exe`
@metadings please continue your questions here: https://github.com/RequestPolicyContinued/requestpolicy/issues/826

**Comment by Marc05** [comment]
The destination is `https://discovery.addons.mozilla.org/en-US/firefox/discovery/pane/50.1.0/WINNT/normal`.

I don't have any rules that have an origin of `about:`, user or preset.
