### ISSUE TITLE
Is RequestPolicy Continued Firefox e10s compatible?

### ISSUE THREAD

**Issue by Diapolo** [RequestPolicyContinued/requestpolicy#828]
Easy question, easy answer I guess :).

Is the current release 1.0beta12.4 (the latest offered via Mozilla addon site) Firefox e10s compatible or when will there be a compatible relase?

**Comment by metadings** [comment]
Well no, in 1.0beta12.4 is `<em:multiprocessCompatible>false</em:multiprocessCompatible>`...

But yes, I tried to do `<em:multiprocessCompatible>false</em:multiprocessCompatible>` also with `browser.tabs.remote.autostart = true` and this seems to work in future versions of RequestPolicy.

**Comment by metadings** [comment]
No... v1.0.beta12.4 is the current release of RequestPolicy continued.

	<em:multiprocessCompatible>false</em:multiprocessCompatible>

However, using javaScript classes `Environment`, `ProcessEnvironment` etc. there are already some thoughts in the code of RequestPolicy, which do seem to have multithreading in mind.

**Comment by myrdd** [comment]
RP is "not really" with e10s. Setting "multiprocessCompatible" activates the so-called shims, which makes an addon not always compatible with e10s. I don't know if RP works with e10s activated, I didn't test that for a while. In any case, because of mozilla's WebExtensions plan, RP needs to be written as a WebExtension, which will make RP e10s-compatible as well.

**Comment by jtracey** [comment]
Just as a point of reference, I've had e10s enabled with RP for months now, with no obvious problems.

**Comment by genodeftest** [comment]
See also: #610.

**Comment by myrdd** [comment]
I'm currently working on a multiprocess compatibility, i.e., on the migration to WebExtension.
Tracking issues are https://github.com/RequestPolicyContinued/requestpolicy/issues/610 and https://github.com/RequestPolicyContinued/requestpolicy/issues/704.
Closing as duplicate.

**Comment by shirishag75** [comment]
#610 is no longer valid, please see/track #704 as #610 seems to be closed.
