### ISSUE TITLE
Can't authorize Discord

### ISSUE THREAD

**Issue by Arinelle** [RequestPolicyContinued/requestpolicy#830]
I can't get Discord to work. The blocked request is from discordapp.com to discord:///invite-proxy. I guess it's the triple slash that keeps me from whitelisting it.
Thanks in advance for looking into this.

**Comment by myrdd** [comment]
try adding a manual rule from scheme `*` to scheme `discord`.

**Comment by myrdd** [comment]
I think you need the following rules to enable discord:

Policy | Origin | Destination
-- | -- | --
Allow | *.discordapp.com | *.discordapp.net
Allow | https://*.discordapp.com | wss://*.discord.gg
Allow | *.discordapp.com | *.discordapp.com

If you want you can open a PR on https://github.com/RequestPolicyContinued/subscriptions

**Comment by myrdd** [comment]
I'm moving this issue to https://github.com/RequestPolicyContinued/subscriptions/issues/57
