### ISSUE TITLE
Only temporary permissions when in incognito mode

### ISSUE THREAD

**Issue by wilkowy** [RequestPolicyContinued/requestpolicy#832]
Feature request:
Similar to NoScript where there is a "permanent allow" checkbox - when it is disabled RP could only make only temporary permissions from UI while using incognito mode.

**Comment by myrdd** [comment]
RP prefs > Basic Prefs > Menu >
Allow adding non-temporary rules when using Private Browsing Mode

**Comment by wilkowy** [comment]
Och dear, you are right, I have overlooked this checkbox...
