### ISSUE TITLE
Request policy prevent snooze tabs from working

### ISSUE THREAD

**Issue by daufinsyd** [RequestPolicyContinued/requestpolicy#833]
Hello, here is my bug

__Steps to reproduce:__

1. Create a new Firefox profile
2. Add Request Policy
3. Enable Snooze Tabs from Firefox test pilot
4. Restart firefox

__What happens?__

Snooze Tabs' icon disappears and doesn't work anymore

http://pix.toile-libre.org/upload/original/1488886143.png

__What should happen?__

Snooze Tabs should work properly

I'm using RequestPolicy 0.5.28.1 signed and running Firefox nightly (54.0a1 03/06/2017, though it seems to also affect Firefox 51)

thx :)

**Comment by Atavic** [comment]
What does RP Menu say?
https://github.com/bwinton/SnoozeTabs/issues/197

**Comment by daufinsyd** [comment]
In the request log I get
Origin
chrome://browser/content/browser.xul 
Destination
moz-extension://aec697d5-7c0a-44ba-8c90-d1ed51cf9def/popup/snooze.html

**Comment by myrdd** [comment]
> 0.5.28.1

try 0.5.31, it should work.
https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-legacy/
