### ISSUE TITLE
Breaks view-source

### ISSUE THREAD

**Issue by operat** [RequestPolicyContinued/requestpolicy#836]
**Browser and Add-ons:**

- Firefox 54.0
- RequestPolicy 1.0.beta12.4

**Steps to reproduce:**

1. Enter `view-source:https://www.example.com/` in address bar
2. See the source code

**What should happen?**

Lines wrap, if `view_source.wrap_long_lines` is set to true. HTML tags and attributes are colored and highlighted.

**What happens?**

With RP 1.0.beta12.4 enabled, view-source doesn't work properly: `view_source.wrap_long_lines` is not respected and HTML tags as well as attributes are neither colored nor highlighted. (No such problems in RequestPolicy 0.5.31, though.)

**Comment by myrdd** [comment]
Thanks for reporting this bug. This has actually already been fixed (https://github.com/RequestPolicyContinued/requestpolicy/issues/788), but released only on the beta (nightly) channel. I'll release beta14 later today.
