### ISSUE TITLE
Prepare for Firefox 57 (make it a web extension)

### ISSUE THREAD

**Issue by Ryuno-Ki** [RequestPolicyContinued/requestpolicy#839]
Hi,

I am really pleased with this AddOn.
Since Firefox 57 will stop support for Legacy AddOns, are there any plans to [port it into a web extension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_legacy_Firefox_add-on)?

You can read more about the [roadmap](https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/) on Mozilla's AddOn blog.

**Comment by myrdd** [comment]
Yes, it's a WIP: #704
