### ISSUE TITLE
Nightly Version 57.0a1 (2017-08-03) (64-bit), on Windows, no "about:requestpolicy?yourpolicy"

### ISSUE THREAD

**Issue by DJ-Leith** [RequestPolicyContinued/requestpolicy#840]
First seen
Version 57.0a1 (2017-08-03) (64-bit)
Name            Firefox
Version         57.0a1
Update Channel  nightly
User Agent      Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

RequestPolicy Continued (RPC) 1.0.beta13.0
E10s are "off"
"Multiprocess Windows 0/19 (Disabled)" shown in "about:support"

**STR**
Use 'RPC Flag', "Manage Policies"
should load the ...\PROFILE\requestpolicy\policies\user.json

For example, on Windows:
C:\Users\UserNameHere\AppData\Roaming\Mozilla\Firefox\Profiles\SALT.Proile_Name\requestpolicy\policies\user.json

'URL Bar', for the Tab, is "about:requestpolicy?yourpolicy"

**Expected result**
The "Your Policy" page with a list of "Active rules".

**Actual result**
The "about:requestpolicy?yourpolicy" Tab is empty.

Possible cause is:

Bug 1385891 "Firefox doesn't load extension's files after upgrade"
https://bugzilla.mozilla.org/show_bug.cgi?id=1385891

So, seen on existing Profiles.
I have not had time to test on a fresh Profile with 'just RPC'.

**Short background information**
I have many Profiles, all have NoScript and RPC (most also have other 'Legacy Extensions' as well).
In April 2017, because I anticipated that not all the Extensions, that I want to keep using, would be ready for Firefox 57, and while 'Release Firefox was at version 52' I moved all my 'Release Profiles' to use 'ESR 52.x.x'.

I also did this for the Users I support (about 20 ESR Profiles).

I also moved all my Aurora Profiles, from 32-bit Aurora, to 64-bit Nightly.

All Profiles are started with a 'specific short cut' to launch Firefox with
a 'specific profile' using the -no-remote switch like this:

"C:\Program Files\Nightly\firefox.exe" -profile "C:\Users\UserNameHere\AppData\Roaming\Mozilla\Firefox\Profiles\z2xh6et5.92-N64" -no-remote

DJ-Leith

**Comment by myrdd** [comment]
Hi DJ-Leith, Fx57 requires add-ons to be written as WebExtensions. I'm currently rewriting RPC as a WE.  The `about:requestpolicy` URI will then change to some `moz-extension://.../` URI. The tracking issue for WE support is #704. I'd be grateful if you could test RPC on Fx57 as soon as a WE-version of RPC is available/ready. You'll know when you follow #704. In the meantime, I'm closing this issue, because the current version of RPC is not supposed to work on Fx57.
