### ISSUE TITLE
WE API: mapping between a `web-extension://` uuid and an extension id

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/requestpolicy#845]
**Summary:**

- Requests by WebExtensions originate from `web-extension://{UUID}/...`.
- `{UUID}` is a context- and extension-specific uuid, that is, the extension has a different uuid for each browsing context (chrome, content, …).
- Knowing which add-on a request comes from is necessary for the "allow_extensions" subscription, see https://github.com/RequestPolicyContinued/subscriptions/issues/62
- There is no such API yet

**ToDo:**

Request a new API—or an addition to "details" in `webRequest.onBeforeRequest`—for RP to know which add-on a request (coming from or going to `web-extension://*/`) corresponds to.

**Links:**

- https://wiki.mozilla.org/WebExtensions/NewAPIs
- https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/onBeforeRequest#details

**Comment by myrdd** [comment]
API requested at https://bugzilla.mozilla.org/show_bug.cgi?id=1400910

**Comment by myrdd** [comment]
The request has been rejected for Fx57. Apparently web requests made by one add-on are **not** seen by webRequest listeners of other add-ons (see [bug comment 4](https://bugzilla.mozilla.org/show_bug.cgi?id=1400910#c4)). I did not check yet if that's true – I suppose it's true at least for the most current version (Fx57 nightly). In that case we'd even need to request being able to block other extensions' requests. (If you've got some time, help is still highly appreciated.)

**Comment by myrdd** [comment]
So RPC currently *can* see other (web-)extensions' requests because it's itself not a WE yet. (RPC still captures requests through nsIContentPolicy.)

**Comment by Watilin** [comment]
So, if I understand correctly, RP in its WE version will not be able to block other extensions content? This is what we want, right?

**Comment by myrdd** [comment]
No, it would be good if RP was capable of blocking other extensions' requests. I suppose most users want all extensions "just to work", which means nothing should be blocked, but personally I'd like to be able to block other extensions' requests.

**Comment by myrdd** [comment]
> API requested at https://bugzilla.mozilla.org/show_bug.cgi?id=1400910

The request has been rejected. As soon as RPC is converted to a WE, other WEs' requests cannot be intercepted anyways. So I'll mark this issue as wontfix. On Firefox <= 56, on SeaMonkey and on PaleMoon RPC will continue to allow the user to block other WEs' requests. However, since RPC v1.0.beta13.1 those requests (i.e., `moz-extension:*` requests) are allowed by default.
