### ISSUE TITLE
Default installation of RequestPolicy breaks Privacy Badger

### ISSUE THREAD

**Issue by ghostwords** [RequestPolicyContinued/requestpolicy#852]
The default installation of RequestPolicy blocks Privacy Badger's internal requests to assets hosted on `eff.org`.

This sounds like a problem that affects all other (WebExtensions) add-ons: Request Policy blocks requests from `moz-extension://` URLs to `https` URLs.

Following up on https://github.com/EFForg/privacybadger/issues/1690#issuecomment-333282180.

**Comment by myrdd** [comment]
Thank you for reporting. I've released RPC `1.0.beta13.1`, which should fix the issue (I've tested it on Fx56). I'll close the issue. If you still have problems, simply reopen this issue.

**Comment by ghostwords** [comment]
Excellent, thank you!
