### ISSUE TITLE
error on accessing "nsIURI.asciiHost"

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/requestpolicy#854]
reported by @genodeftest; copying from https://github.com/RequestPolicyContinued/requestpolicy/issues/704#issuecomment-332257119:

> On every start, I get these lines printed to console:
> ```
> console.debug: 
>   [RequestPolicy] starting up
> console.info: [RequestPolicy] [POLICY] PolicyManager::loadUserRules loading user rules
> console.info: [RequestPolicy] [POLICY] PolicyManager::loadSubscriptionRules: official / allow_extensions
> console.info: [RequestPolicy] [POLICY] PolicyManager::loadSubscriptionRules: official / allow_sameorg
> console.info: [RequestPolicy] [POLICY] PolicyManager::loadSubscriptionRules: official / allow_mozilla
> console.info: [RequestPolicy] Will update subscription: official allow_extensions
> console.info: [RequestPolicy] Will update subscription: official allow_sameorg
> console.info: [RequestPolicy] Will update subscription: official allow_mozilla
> console.info: [RequestPolicy] Will update list: official
> console.info: [RequestPolicy] Updating [SubscriptionList official https://raw.githubusercontent.com/RequestPolicyContinued/subscriptions/master/official.json]
> ```
> 
> Also, since today I'm getting this error message printed to console/syslog:
> ```
> console.error:
>   [RequestPolicy] Fatal Error:
> console.dir:
>   Message: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIURI.asciiHost]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://rpcontinued/content/lib/request.js :: Request.prototype.isInternal :: line 76"  data: no]
>   Stack:
>     Request.prototype.isInternal@chrome://rpcontinued/content/lib/request.js:76:1
> NormalRequest.prototype.isInternal@chrome://rpcontinued/content/lib/request.js:160:14
> self.process@chrome://rpcontinued/content/lib/request-processor.js:262:17
> self.shouldLoad@chrome://rpcontinued/content/main/content-policy.js:60:16
> ```
> This happened 5 times today, but I cannot tell you when it happened, i.e. I don't have a reproducer.

**Comment by myrdd** [comment]
@genodeftest a new nightly release is online. Please check if the issue is gone.

**Comment by genodeftest** [comment]
With 1.0.beta13.1.1867.r17458702.pre installed and firefox restarted, the first block is still present. The second block happens less often. It sometimes has a different traceback:
```
console.error: 
  [RequestPolicy] Fatal Error:
console.dir: 
  Message: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIURI.asciiHost]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://rpcontinued/content/lib/request.js :: Request.prototype.isInternal :: line 76"  data: no]
  Stack:
    Request.prototype.isInternal@chrome://rpcontinued/content/lib/request.js:76:1
NormalRequest.prototype.isInternal@chrome://rpcontinued/content/lib/request.js:160:14
self.process@chrome://rpcontinued/content/lib/request-processor.js:262:17
self.shouldLoad@chrome://rpcontinued/content/main/content-policy.js:60:16
yield@chrome://noscript/content/Thread.js?1brpos9f4rl5p11cm5b8:33:5
_spinInternal@chrome://noscript/content/Thread.js?1brpos9f4rl5p11cm5b8:22:9
spin@chrome://noscript/content/Thread.js?1brpos9f4rl5p11cm5b8:11:5
send@chrome://noscript/content/ABE.js?1brpos9f4rl5p11cm5b8:380:16
downloadRuleset@chrome://noscript/content/ABE.js?1brpos9f4rl5p11cm5b8:383:11
checkRequest@chrome://noscript/content/ABE.js?1brpos9f4rl5p11cm5b8:200:11
handleABE/res<@chrome://noscript/content/RequestWatchdog.js?1brqqu954ir6q0sm9r4k:180:18
run@chrome://noscript/content/RequestWatchdog.js?1brqqu954ir6q0sm9r4k:1114:44
handleABE@chrome://noscript/content/RequestWatchdog.js?1brqqu954ir6q0sm9r4k:179:19
onHttpStart@chrome://noscript/content/RequestWatchdog.js?1brqqu954ir6q0sm9r4k:162:9
observe@chrome://noscript/content/MainParent.js?1brpos9f4rl5p11cm5b8:83:24

console.error: 
  [RequestPolicy] Fatal Error:
console.dir: 
  Message: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIURI.asciiHost]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://rpcontinued/content/lib/request.js :: Request.prototype.isInternal :: line 76"  data: no]
  Stack:
    Request.prototype.isInternal@chrome://rpcontinued/content/lib/request.js:76:1
NormalRequest.prototype.isInternal@chrome://rpcontinued/content/lib/request.js:160:14
self.process@chrome://rpcontinued/content/lib/request-processor.js:262:17
self.shouldLoad@chrome://rpcontinued/content/main/content-policy.js:60:16
```

**Comment by myrdd** [comment]
That doesn't make sense, since I've removed all usages of asciiHost: https://github.com/RequestPolicyContinued/requestpolicy/commit/a0986747dad7539ba27ab284da6c0413e003f0ea

You can see there is no asciiHost in the source code: https://github.com/RequestPolicyContinued/requestpolicy/blob/174587025a7b030b1e58483dabdeea913159f595/src/content/lib/request.js

Did you restart your browser since the update?

**Comment by genodeftest** [comment]
> Did you restart your browser since the update?

I thought I did (I'm quite sure) but as I cannot reproduce the issue any more, I probably was wrong about that before. Thanks for having a look into it anyway. Sorry for the noise.
