### ISSUE TITLE
No changelog of changes between 1.13.0 and 1.13.1 

### ISSUE THREAD

**Issue by shirishag75** [RequestPolicyContinued/requestpolicy#855]
I was looking at https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-continued/versions/?page=1#version-1.0.beta13.1 . Looking for the changelog went to https://outgoing.prod.mozaws.net/v1/16f0d4252228177c5808006822d446a9c7276e94306ffd78956d856deb9dd6f2/https%3A//github.com/RequestPolicyContinued/requestpolicy/blob/v1.0.beta13.1/ChangeLog.md%23version-10beta131 and found a 404 . Saw the older version and understood that the changelog hasn't been written. Please do the needful.

**Comment by myrdd** [comment]
you are right, I forgot to push. The changes are now online.
