### ISSUE TITLE
RPC stable release is 1.13.1 while development channel says 1.0.beta13.0.1776.r3866608f.pre

### ISSUE THREAD

**Issue by shirishag75** [RequestPolicyContinued/requestpolicy#856]
Want to help with testing of multiprocess e10 and move to webextensions by testing but seems it is confusing. The latest release seems to be beta 1.13.1 while the development channel shares 1.0.beta13.0.1776.r3866608f.pre . It confuses people, could somebody put the record straight. 

Another query on the dev. channel is/would there be a migration path once things are smooth to stable or would have to keep an eye on https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-continued/ to get the latest stable release.

**Comment by myrdd** [comment]
sorry about that, the dev branch is currently failing. I'll release a new version dev version when the dev branch is fixed.

**Comment by myrdd** [comment]
a new nightly version is now online.
