### ISSUE TITLE
WE transition: URLs in "settings/" files

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/requestpolicy#866]
The URLs in the files in [`src/content/settings/`](https://github.com/RequestPolicyContinued/requestpolicy/tree/489ddf49eb1f218518080a53feae1a64fcddc833/src/content/settings) need to be changed:

Every link (e.g. [here](https://github.com/RequestPolicyContinued/requestpolicy/blob/489ddf49eb1f218518080a53feae1a64fcddc833/src/content/settings/basicprefs.html#L5-L13), [here](https://github.com/RequestPolicyContinued/requestpolicy/blob/489ddf49eb1f218518080a53feae1a64fcddc833/src/content/settings/basicprefs.html#L27-L42) and [here](https://github.com/RequestPolicyContinued/requestpolicy/blob/489ddf49eb1f218518080a53feae1a64fcddc833/src/content/settings/yourpolicy.html#L147)) …

* … should be **relative** for `EXTENSION_TYPE!='legacy'`
* … should be **absolute** for `EXTENSION_TYPE='legacy'` (as it is now)

---

Example:

```html
<a href="about:requestpolicy?oldrules" data-string="removeOldRules"></a>
```

will become

```html
<!-- @if EXTENSION_TYPE='legacy' -->
<a href="about:requestpolicy?oldrules" data-string="removeOldRules"></a>
<!-- @endif -->
<!-- @if EXTENSION_TYPE!='legacy' -->
<a href="./oldrules.html" data-string="removeOldRules"></a>
<!-- @endif -->
```

---

(PS: This is a quick and dirty solution, I know.)

**Comment by jrrdev** [comment]
Hi,
I have a question regarding those lines in [here](https://github.com/RequestPolicyContinued/requestpolicy/blob/489ddf49eb1f218518080a53feae1a64fcddc833/src/content/settings/basicprefs.html#L7-L11): 
```html
  <!-- @if EXTENSION_TYPE='legacy' -->
  <script src="chrome://rpcontinued/content/bootstrap/environments/settings.js"></script>
  <!-- @endif -->
  <!-- @if EXTENSION_TYPE!='legacy' -->
  <script src="chrome://rpcontinued/content/settings/main.js"></script>
  <!-- @endif -->
```

I guess that they should be modify to become : 
```html
  <!-- @if EXTENSION_TYPE='legacy' -->
  <script src="chrome://rpcontinued/content/bootstrap/environments/settings.js"></script>
  <!-- @endif -->
  <!-- @if EXTENSION_TYPE!='legacy' -->
  <script src="main.js"></script>
  <!-- @endif -->
```
If legacy, then loads settings.js else loads main.js. Is that right ?

In addition, I don't find main.js in the settings directory. Is that an existing mistake in the current code or I'm missing something ?

**Comment by myrdd** [comment]
Hi @jrrdev I just realized the non-legacy line needs to be:

```html
<script data-main="{JS file name}" src="../lib/third-party/require.min.js"></script>
```

where `{JS file name}` should be e.g. `basicprefs.js`, see [`<html id="{module name}">`](https://github.com/RequestPolicyContinued/requestpolicy/blob/489ddf49eb1f218518080a53feae1a64fcddc833/src/content/settings/basicprefs.html#L2) in each file.

`require.min.js` doesn't exist yet, I'll add it in a future commit. (I've got too many unpublished commits locally ;) )

**Comment by jrrdev** [comment]
I updated the PR to load requireJS on setting pages, see commit https://github.com/RequestPolicyContinued/requestpolicy/pull/868/commits/349160583b6b425744ee029068457a64a5dd3442

**Comment by myrdd** [comment]
PR merged: https://github.com/RequestPolicyContinued/requestpolicy/commit/5e70d115a1923084a86307a30f4913905738a7b0
