### ISSUE TITLE
WE transition: port the XUL menu pupup to a WebExtension browserAction popup

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/requestpolicy#871]
The XUL menupopup is currently described in [`xul-trees.js` (lines 109–299)](https://github.com/RequestPolicyContinued/requestpolicy/blob/489ddf49eb1f218518080a53feae1a64fcddc833/src/content/ui/xul-trees.js#L109-L299) and being added to the browser in [`xul.js` (entry point in lines 279–283)](https://github.com/RequestPolicyContinued/requestpolicy/blob/489ddf49eb1f218518080a53feae1a64fcddc833/src/content/lib/utils/xul.js#L279-L283).

The task is to **map the XUL** (only `<popupset id="rpcontinuedPopupset">` and its children!) **to HTML**. The current XUL tree, as said above, is in `xul-tree.js`. However, the old XUL (probably almost the same) might be helpful, it's available here: https://github.com/RequestPolicyContinued/requestpolicy/blob/23cb3cc15727d14e83ee967328dd8eae5765ae06/src/content/ui/overlay.xul#L71-L136

In `xul-trees.js` the following XUL tags are used:

- [`button`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/button)
- [`hbox`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/hbox)
- [`hbox`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/hbox)
- [`iframe`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/iframe)
- [`keyset`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/keyset)
- [`label`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/label)
- [`menu`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/menu)
- [`menuitem`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/menuitem)
- [`menupopup`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/menupopup)
- [`menuseparator`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/menuseparator)
- [`popupset`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/popupset)
- [`splitter`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/splitter)
- [`toolbar`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/toolbar)
- [`toolbarbutton`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/toolbarbutton)
- [`toolbox`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/toolbox)
- [`vbox`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/vbox)

**Implementation note:**

AFAIK HTML elements may be embedded into a XUL document. So if we're lucky, we simply need to modify `xul-trees.js` and use it for both the WE and the XUL/XPCOM version of the addon. If this is not possible, both `xul-trees.js` and a HTML page need to be maintained.

**Tasks:**

- [ ] Try to use only HTML elements in the  `<popupset id="rpcontinuedPopupset">` tree in `xul-trees.js`.

**Comment by myrdd** [comment]
@jrrdev are you ok to take this issue? I'm still busy with other issues.
If you've got any question, just ask. This is not the most straightforward issue.

**Comment by jrrdev** [comment]
No problem, I actually already started to write it in full HTML. But I will look at the option the keep the `xul-tree.js` file for XUL/XPCOM compatibilty to avoid maintaining two files

**Comment by jrrdev** [comment]
Btw, do you have some uncommit changes that makes RPC WE compatible (like embedded WE ) ? Because right now it is making testing difficult...

**Comment by jrrdev** [comment]
Btw, do you have already something do handle locale (i18n) in HTML WE files ? If yes, can you say what js file needed to be include and most importanly the key text format (like __MSG_key ?). Otherwise, I will try to do something about it

**Comment by myrdd** [comment]
I do not yet have done anything about i18n. The XPCOM i18n part is at [`src/content/lib/utils/strings.js`](https://github.com/RequestPolicyContinued/requestpolicy/blob/489ddf49eb1f218518080a53feae1a64fcddc833/src/content/lib/utils/strings.js).

**Comment by myrdd** [comment]
> do you have already something do handle locale (i18n) in HTML WE files ?

see https://github.com/RequestPolicyContinued/requestpolicy/issues/873

**Comment by jrrdev** [comment]
I came out with the solution to use a XUL's iframe to embedded the html page. A lot of struggles to adjust automatically the iframe but I solved this issue after all.
Now I needed to modify some JS to correctly populate the iframe's content and solve another bug. I hope to finish this task by 2-3 days and definitely by the end of the week.

**Comment by jrrdev** [comment]
Don't know why Github don't want to reference the PR I juste made, but it's done. See PR #875 :-)
