### ISSUE TITLE
Google Search Redirects

### ISSUE THREAD

**Issue by Zero3K** [RequestPolicyContinued/requestpolicy#888]
Read first: https://requestpolicycontinued.github.io/Contributing

__Browser and Add-ons:__

- Browser: Pale Moon 27.7.2
- RequestPolicy version: 1.0.beta13.2
- Other add-ons:
            [TEST] DownThemAll!	3.0.8
            [TEST] Firebug	2.0.19
            Autofill	3.6.1-signed.1-signed	
            Context Menu Image Saver	20130929.1-signed.1-let-fixed.1-signed	
            Decentraleyes	1.3.10	
            DOM Inspector	2.0.17.1	
            Expose Noisy Tabs	1.0.1	
            Extension Preferences Menu	2.13.19	
            FlashGot	1.5.6.14	true	{19503e42-ca3c-4c27-b1e2-9cdb2170ee34}
            Greasemonkey for Pale Moon	
            Greedy Cache	1.1.4	
            I don't care about cookies	2.7.8	
            Location-4-Evar	1.0.4	
            Lull The Tabs	1.3.4b2	
            Menu Wizard	5.10	
            Moon Tester Tool	1.1.4	
            More In Content UI +	2.2.1-signed.1-signed	
            Open Tabs Next to Current+	1.0.1	
            RequestPolicy Continued	1.0.beta13.2	
            S3.Google Translator	5.35	
            Secret Agent	1.35
            Secure Login	1.2.5	
            Session Manager	0.8.1.7
            Single Key Tab Switch	0.2.7	
            Space Advance	0.34.1	
            TryAgain	3.4.6.1-signed.1-signed	
            uBlock Origin	1.15.10
            uBlock Origin Updater	1.3.0
            uMatrix	1.1.4	
 
RequestPolicy settings:
              They are all at the default setting.

__Steps to reproduce:__

1. Search for something on Google.com
2. Click a link in the search results page.

__What happens?__

It asks you if you want to redirect and offers the ability to allow the redirecting of Google.com to the domain that is in the link that was clicked on.

__What should happen?__

It should offer another option that allows the redirecting of Google.com to any domain when a link in a search results page is clicked on. That or it should recognize when a user clicks on a link in a search page on the popular search engines and allow them by default.

**Comment by Zero3K** [comment]
I just learned that it already does allow the redirects of Google to other sites when clicking on a link on a search results page. So, you can ignore this issue. I just have one question for now. Should I replace uMatrix with NoScript since I have RequestPolicy Continued installed?

**Comment by myrdd** [comment]
> So, you can ignore this issue.

okay, I'll close it

> Should I replace uMatrix with NoScript since I have RequestPolicy Continued installed?

For security, it's a good idea to install NoScript, but of course not necessary. uMatrix is more like RPC than like NoScript. It's also not necessary to disable uMatrix, because you can use uM and RPC at the same time; however, you might want to set uM or RPC (or both) in default-allow mode to avoid double effort when getting websites to work.
