### ISSUE TITLE
reCAPTCHA is being blocked

### ISSUE THREAD

**Issue by Zero3K** [RequestPolicyContinued/requestpolicy#889]
Read first: https://requestpolicycontinued.github.io/Contributing

__Browser and Add-ons:__

- Browser: Pale Moon 27.7.2
- RequestPolicy version: 1.0.beta13.2
- Other add-ons:
            [TEST] DownThemAll!	3.0.8
            [TEST] Firebug	2.0.19
            Autofill	3.6.1-signed.1-signed	
            Context Menu Image Saver	20130929.1-signed.1-let-fixed.1-signed	
            Decentraleyes	1.3.10	
            DOM Inspector	2.0.17.1	
            Expose Noisy Tabs	1.0.1	
            Extension Preferences Menu	2.13.19	
            FlashGot	1.5.6.14	true	{19503e42-ca3c-4c27-b1e2-9cdb2170ee34}
            Greasemonkey for Pale Moon	
            Greedy Cache	1.1.4	
            I don't care about cookies	2.7.8	
            Location-4-Evar	1.0.4	
            Lull The Tabs	1.3.4b2	
            Menu Wizard	5.10	
            Moon Tester Tool	1.1.4	
            More In Content UI +	2.2.1-signed.1-signed	
            Open Tabs Next to Current+	1.0.1	
            RequestPolicy Continued	1.0.beta13.2	
            S3.Google Translator	5.35	
            Secret Agent	1.35
            Secure Login	1.2.5	
            Session Manager	0.8.1.7
            Single Key Tab Switch	0.2.7	
            Space Advance	0.34.1	
            TryAgain	3.4.6.1-signed.1-signed	
            uBlock Origin	1.15.10
            uBlock Origin Updater	1.3.0
            uMatrix	1.1.4	
 
RequestPolicy settings:
              They are all at the default setting.

__Steps to reproduce:__

Go to https://www.coinbase.com/users

__What happens?__

The reCAPTCHA is missing by default.

__What should happen?__

It should be showing without the user having to manually allow google.com and gstatic.com for each site that uses it.

**Comment by jrrdev** [comment]
Hi,
I guess it is normal behaviour here. If you are a user seeking for privacy, you won't allow requests to `*.google.com` or `*.gstatic.com` by default.
About the reCAPTCHA thing, it is true that blocking it breaks a lot of websites. But the problem is that the URL is `www.google.com/recaptcha/api.js` so it doesn't offer enough control because it is the same domain as others google's spyware. Maybe the best way should be to ask google to move it to a subdomain like `recaptcha.google.com` :smiley:

**Comment by Zero3K** [comment]
I don't think they will do that.

**Comment by myrdd** [comment]
Yes, RPC works as intended. As regards the usability issue, https://github.com/RequestPolicyContinued/subscriptions/issues/58 covers that, which depends on https://github.com/RequestPolicyContinued/requestpolicy/issues/338. I suggest you to upvote those issues.
