### ISSUE TITLE
[locale] respect browser locale settings

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/requestpolicy#890]
The seftings `general.useragent.locale` and `intl.locale.matchOS` are currently ignored.

We need to use this function:
https://dxr.mozilla.org/comm-esr45/source/mozilla/toolkit/mozapps/extensions/AddonManager.jsm#283-308

```js
const PREF_MATCH_OS_LOCALE            = "intl.locale.matchOS";
const PREF_SELECTED_LOCALE            = "general.useragent.locale";

/**
 * Gets the currently selected locale for display.
 * @return  the selected locale or "en-US" if none is selected
 */
function getLocale() {
  try {
    if (Services.prefs.getBoolPref(PREF_MATCH_OS_LOCALE))
      return Services.locale.getLocaleComponentForUserAgent();
  }
  catch (e) { }

  try {
    let locale = Services.prefs.getComplexValue(PREF_SELECTED_LOCALE,
                                                Ci.nsIPrefLocalizedString);
    if (locale)
      return locale;
  }
  catch (e) { }

  try {
    return Services.prefs.getCharPref(PREF_SELECTED_LOCALE);
  }
  catch (e) { }

  return "en-US";
}
```

(originally reported at https://github.com/RequestPolicyContinued/requestpolicy/issues/826#issuecomment-368224600)

**Comment by myrdd** [comment]
@wilkowy Are you using any of the pre-release versions? That is, something like `1.0.beta13.2.AAAA.rBBBBBBBBB.pre`?
(https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-continued/versions/beta)

**Comment by wilkowy** [comment]
Yes, I have 1.0.beta13.2.2128.r67d9fd50e.pre

**Comment by myrdd** [comment]
@wilkowy  the latest nightly release (https://sslsites.de/requestpolicy.256k.de/requestpolicy-nightly.xpi) respects the two settings. :)
