### ISSUE TITLE
Unable to view 3rd party requests to domain and nothing happening for temporary requests. 

### ISSUE THREAD

**Issue by shirishag75** [RequestPolicyContinued/requestpolicy#899]
Read first: https://requestpolicycontinued.github.io/Contributing

__Browser and Add-ons:__

- Browser: e.g. Firefox 52.9.0
- RequestPolicy version: 1.0.beta13.2.2447.r20582e0a6.pre
 - …

RequestPolicy settings:
- Default policy: "deny"

I am using an existing profile, have not  made a new profile. 
…

__What should happen?__

It should have given temporary respite and tell if any third-party requests are there. It doesn't  :(

…

**Comment by shirishag75** [comment]
![requestpolicy-issue](https://user-images.githubusercontent.com/727626/44629653-11828d80-a970-11e8-80cb-2f729754a009.png)

and even after giving the permission, get this - 

![request-policy-no-change](https://user-images.githubusercontent.com/727626/44629658-252df400-a970-11e8-99bf-c98a6852fbe3.png)

**Comment by myrdd** [comment]
The site
http://onehouronelife.com/forums/register.php
does not make any 3p requests:

![spectacle s30460](https://user-images.githubusercontent.com/4286829/44631408-4b04ca00-a96b-11e8-901e-d08616f30063.png)

if you think the menu should tell you there aren't any 3p requests, please create a new issue. closing.
