### ISSUE TITLE
allow wildcard subdomain whitelisting from menu when using stricter classification policies

### ISSUE THREAD

**Issue by msxfm** [RequestPolicyContinued/requestpolicy#9]
<a href="https://github.com/jsamuel"><img src="https://avatars.githubusercontent.com/u/1240282?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jsamuel](https://github.com/jsamuel)**
_Thursday Dec 22, 2011 at 18:45 GMT_
_Originally opened as https://github.com/RequestPolicy/requestpolicy/issues/9_

----

    imported trac ticket
    created: 2009-06-21 17:16:17
    reporter: justin

When using stricter classification policies, there are times when users want to whitelist all subdomains of the current domain. After #8 has been completed,  displaying menu items for wildcard subdomain whitelisting should either be enabled by default or should be an optional preference when using stricter classification policies.

**Comment by myrdd** [comment]
> displaying menu items for wildcard subdomain whitelisting should either be enabled by default or should be an optional preference when using stricter classification policies.

Wildcards are already implemented in v1.0. – Menu items like `*.site.com -> *.site.com` are available, apart from the `*.site.com -> subdomain.site.com` rules. Closing.
