### ISSUE TITLE
Fx 48 refuses to update to RPC14

### ISSUE THREAD

**Issue by wilkowy** [RequestPolicyContinued/requestpolicy#903]
Firefox 48.0.2
RPC: 1.0.beta13.2.2462.r2f19aa957.pre

I'm using non-amo version `rpcontinued@non-amo.requestpolicy.org.xpi` (downloaded xpi and installed from file, no building etc.). I can't find the original link and don't remember reason why, probably amo version had a bug and new version was not accepted yet. Anyway since then RPC updated few times through about:addons without any problem, however now I'm unable to update to 14.0.2471: https://i.postimg.cc/gYYK5x52/rp114-install1.jpg

Trying to download xpi within Fx: https://i.postimg.cc/Vz9RDqKh/rp114-install2.jpg (link https://requestpolicy.256k.de/requestpolicy-nightly.xpi)
(when trying to download using https://sslsites.de/requestpolicy.256k.de/requestpolicy-nightly.xpi link with RPC enabled the message is different https://i.postimg.cc/6WjxjHV6/rp114-install4.jpg)

I've downloaded xpi with other browser and tried to "install from file": https://i.postimg.cc/8NwkM5WV/rp114-install3.jpg

Settings `xpinstall.whitelist.required;false` and `xpinstall.signatures.required;false` does not solve the problem (domains were added to allowed sites as well)
Suggested settings `app.update.auto` and `app.update.enabled` are already set to `false`.

**Comment by wilkowy** [comment]
OK, I have found out how to solve this Mozilla's mess. Follow this instructions https://superuser.com/a/1191271

**Comment by myrdd** [comment]
> https://sslsites.de/requestpolicy.256k.de/requestpolicy-nightly.xpi

Oh! That url is not valid anymore. I've now corrected the url on some important issue posts at github.
Should be https://requestpolicy.256k.de/requestpolicy-nightly.xpi

> I'm using non-amo version […]. I can't find the original link

https://requestpolicy.256k.de/archive/
documented here: https://github.com/RequestPolicyContinued/requestpolicy/wiki/Downloading

> I've downloaded xpi with other browser and tried to "install from file": https://i.postimg.cc/8NwkM5WV/rp114-install3.jpg

This is weird. The xpi provided at https://requestpolicy.256k.de/requestpolicy-nightly.xpi should actually be recognized as signed. Still, I'm glad you were able to fix it.
