### ISSUE TITLE
Your link:  0.5 version still available on Addons for Firefox

### ISSUE THREAD

**Issue by synaeus888** [RequestPolicyContinued/requestpolicy#908]
Read first: https://requestpolicycontinued.github.io/Contributing

__Browser and Add-ons:__

- Browser: e.g. Firefox 52.2.0
- RequestPolicy version: e.g. 1.0.beta12.4
- Other add-ons:
  - Example Add-on v1.2.3 -- https://addons.mozilla.org/en-US/firefox/addon/example-addon/versions/1.2.3
  - …

RequestPolicy settings:
- Default policy: "allow" / "deny"

__Steps to reproduce:__

1. Create a new browser profile
2. install above add-ons
3. configure the add-ons as described above
4. …
5. … Be as detailed as possible.

__What happens?__
Link is dead. It goes here: https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-legacy/
…

__What should happen?__
Not this.
…

**Comment by myrdd** [comment]
>  Link is dead. It goes here: https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-legacy/

I fixed the links on the wiki. It's  
https://addons.thunderbird.net/en-US/seamonkey/addon/requestpolicy-legacy/
and https://addons.thunderbird.net/en-US/seamonkey/addon/requestpolicy-continued/
